# Development Configuration Override
# Use this file for local development to enable development mode
# This ensures assets are loaded from the project directory instead of system paths

deployment:
  develop: true
  # Override base path to point to project root when running from src/rust/daemon directory
  base_path: "/Users/chris/dev/ai/claude-code-cfg/mcp/workspace-qdrant-mcp"

# Override specific settings for development
logging:
  level: "debug"
  json_format: false