# Default Configuration for Workspace Qdrant MCP
# This file provides sane defaults for typical user installations
#
# Copy this file to ~/.workspace-qdrant-mcp/config/default.yaml
# or specify a custom location with --config-file

# Server configuration
host: "127.0.0.1"
port: 8000
debug: false

# Qdrant database configuration
qdrant:
  url: "http://localhost:6333"  # Local Qdrant instance
  api_key: null  # Set to your API key for Qdrant Cloud
  timeout: 30
  prefer_grpc: false
  # Connection pool settings
  max_retries: 3
  retry_delay: 1.0

# Embedding configuration
embedding:
  model: "sentence-transformers/all-MiniLM-L6-v2"  # Fast, good quality model
  enable_sparse_vectors: true  # Better search quality
  chunk_size: 800  # Good balance of context and processing speed
  chunk_overlap: 120  # Prevent information loss at chunk boundaries
  batch_size: 50  # Efficient batch processing
  # Model caching
  cache_dir: "~/.cache/huggingface/transformers"

# Workspace configuration
workspace:
  # Default collection suffixes - adjust based on your workflow
  collection_suffixes: 
    - "project"    # Main project files
    - "docs"       # Documentation
    - "notes"      # Personal notes and research
  
  global_collections: []  # Shared across all projects
  github_user: null  # Set to your GitHub username for better project detection
  collection_prefix: ""  # Optional prefix for all collection names
  max_collections: 100  # Prevent runaway collection creation
  
  # Project detection settings
  project_indicators:
    - ".git"
    - "package.json"
    - "pyproject.toml"
    - "Cargo.toml"
    - "pom.xml"
    - "build.gradle"

# Auto-ingestion configuration - optimized for development workflows
auto_ingestion:
  enabled: true  # Enable automatic file ingestion
  auto_create_watches: true  # Watch for file changes
  
  # File type inclusion
  include_common_files: true  # Documentation, README, etc.
  include_source_files: true  # Source code files
  
  # Processing settings
  target_collection_suffix: "project"  # Default target for auto-ingestion
  max_files_per_batch: 5  # Prevent system overload
  batch_delay_seconds: 2.0  # Allow system breathing room
  max_file_size_mb: 50  # Skip very large files
  recursive_depth: 5  # Reasonable directory traversal depth
  debounce_seconds: 10  # Avoid processing rapidly changing files
  
  # File patterns to include (case-insensitive)
  include_patterns:
    # Documentation
    - "*.md"
    - "*.txt" 
    - "*.rst"
    - "*.pdf"
    - "README*"
    - "CHANGELOG*"
    - "LICENSE*"
    - "*.adoc"
    
    # Code files
    - "*.py"
    - "*.js"
    - "*.ts"
    - "*.jsx"
    - "*.tsx"
    - "*.java"
    - "*.c"
    - "*.cpp"
    - "*.h"
    - "*.hpp"
    - "*.rs"
    - "*.go"
    - "*.php"
    - "*.rb"
    - "*.swift"
    - "*.kt"
    - "*.scala"
    
    # Configuration and data
    - "*.json"
    - "*.yaml" 
    - "*.yml"
    - "*.toml"
    - "*.xml"
    - "*.ini"
    - "*.cfg"
    - "*.conf"
    - "*.env"
    
    # Web and markup
    - "*.html"
    - "*.css"
    - "*.scss"
    - "*.sass"
    - "*.less"
    - "*.vue"
    - "*.svelte"
    
  # File patterns to exclude
  exclude_patterns:
    # Version control and build artifacts
    - ".git/*"
    - ".svn/*"
    - "node_modules/*"
    - "target/*"
    - "build/*"
    - "dist/*"
    - "__pycache__/*"
    - ".pytest_cache/*"
    - ".coverage"
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - ".DS_Store"
    - "Thumbs.db"
    
    # IDE and editor files
    - ".vscode/*"
    - ".idea/*"
    - "*.swp"
    - "*.swo"
    - "*~"
    - ".#*"
    
    # Log and temporary files
    - "*.log"
    - "*.tmp"
    - "*.temp"
    - "*.cache"
    - ".venv/*"
    - "venv/*"
    
    # Large binary files
    - "*.exe"
    - "*.dll"
    - "*.so"
    - "*.dylib"
    - "*.a"
    - "*.lib"
    - "*.zip"
    - "*.tar.gz"
    - "*.tgz"
    - "*.rar"
    - "*.7z"
    
    # Media files
    - "*.jpg"
    - "*.jpeg"
    - "*.png"
    - "*.gif"
    - "*.bmp"
    - "*.ico"
    - "*.svg"
    - "*.mp3"
    - "*.mp4"
    - "*.avi"
    - "*.mkv"
    - "*.wav"
    - "*.flac"

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "~/.workspace-qdrant-mcp/logs/workspace-qdrant-mcp.log"
  max_size: "100MB"  # Rotate when log reaches this size
  backup_count: 5  # Keep 5 old log files
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Component-specific logging levels
  loggers:
    "workspace_qdrant_mcp.ingestion": "INFO"
    "workspace_qdrant_mcp.server": "INFO"
    "workspace_qdrant_mcp.search": "INFO"
    "qdrant_client": "WARNING"  # Reduce Qdrant client verbosity
    "sentence_transformers": "WARNING"  # Reduce embedding model verbosity

# Performance and resource management
performance:
  # Memory management
  max_memory_mb: 2048  # Maximum memory usage before cleanup
  cleanup_threshold: 0.8  # Trigger cleanup at 80% of max memory
  
  # Processing limits
  max_concurrent_requests: 10
  request_timeout_seconds: 300  # 5 minutes
  
  # Cache settings
  enable_result_cache: true
  cache_size: 1000  # Number of search results to cache
  cache_ttl_seconds: 3600  # 1 hour

# Development and debugging options
development:
  enable_debug_endpoints: false  # Only enable in development
  log_request_details: false  # Log full request/response details
  enable_profiling: false  # Performance profiling
  mock_embedding_service: false  # Use fake embeddings for testing

# Security settings
security:
  enable_cors: true  # Allow cross-origin requests
  allowed_origins:
    - "http://localhost:*"
    - "http://127.0.0.1:*"
  max_request_size_mb: 100  # Maximum request body size
  rate_limit_requests_per_minute: 1000  # Per-client rate limiting

# Feature flags
features:
  enable_web_crawling: true  # Allow ingestion from URLs
  enable_pdf_processing: true  # Process PDF files
  enable_docx_processing: true  # Process Word documents
  enable_code_analysis: true  # Enhanced code file processing
  enable_git_integration: true  # Git repository integration
  enable_real_time_sync: true  # Real-time file watching