# Example YAML configuration for workspace-qdrant-mcp
# This file demonstrates the structure and available configuration options

# Server configuration
host: "127.0.0.1"
port: 8000
debug: false

# Qdrant database configuration
qdrant:
  url: "http://localhost:6333"
  api_key: null  # Set to your API key for Qdrant Cloud
  timeout: 30
  prefer_grpc: false

# Embedding configuration
embedding:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  enable_sparse_vectors: true
  chunk_size: 800
  chunk_overlap: 120
  batch_size: 50

# Workspace configuration
workspace:
  collection_types: []  # Project-specific collection types created as {project}-{type}
  global_collections: []  # Collections available across all projects
  github_user: null  # Set to your GitHub username for improved project detection
  auto_create_collections: false  # Whether to automatically create project collections on startup
  memory_collection_name: "__memory"  # Name for the system memory collection
  code_collection_name: "__code"  # Name for the system code collection

# gRPC configuration for Rust engine integration
grpc:
  enabled: false  # Enable gRPC connection to high-performance Rust engine
  host: "127.0.0.1"  # gRPC server host address
  port: 50051  # gRPC server port
  fallback_to_direct: true  # Fall back to direct Qdrant access if gRPC fails

# Auto-ingestion configuration
auto_ingestion:
  enabled: true  # Enable automatic file ingestion on server startup
  auto_create_watches: true  # Automatically create file watches for project directories
  include_common_files: true  # Include common document types (*.md, *.txt, *.pdf, etc.)
  include_source_files: false  # Include source code files (*.py, *.js, *.ts, etc.)
  target_collection_suffix: ""  # Which collection type to use for auto-ingested files (must be one of collection_types)
  max_files_per_batch: 5  # Maximum files to process simultaneously
  batch_delay_seconds: 2.0  # Delay between processing batches
  max_file_size_mb: 50  # Maximum file size to process
  debounce_seconds: 10  # File change debounce time for watches