# Workspace Qdrant MCP Configuration
# TOML format for memexd daemon

# Logging configuration
log_file = "/Users/chris/Library/Logs/memexd.log"

# Processing engine configuration
max_concurrent_tasks = 4
default_timeout_ms = 30000
enable_preemption = true
chunk_size = 1000
enable_lsp = true
log_level = "debug"
enable_metrics = true
metrics_interval_secs = 60

# Auto-ingestion configuration
[auto_ingestion]
enabled = true
auto_create_watches = true
include_common_files = true
include_source_files = true
target_collection_suffix = "scratchbook"
max_files_per_batch = 5
batch_delay_seconds = 2.0
max_file_size_mb = 50
recursive_depth = 5
debounce_seconds = 10

# Workspace directory (auto-detected from current working directory)
project_path = "/Users/chris/Dropbox/dev/ai/claude-code-cfg/mcp/workspace-qdrant-mcp"

# Qdrant connection configuration
[qdrant]
url = "http://localhost:6333"
transport = "Grpc"  # Using gRPC with improved HTTP/2 configuration
timeout_ms = 30000
max_retries = 3
retry_delay_ms = 1000
pool_size = 10
tls = false
dense_vector_size = 1536
check_compatibility = false  # Skip version check during startup

# HTTP/2 settings for gRPC compatibility
[qdrant.http2]
# Conservative frame sizes compatible with most Qdrant configurations
max_frame_size = 8192          # Reduced from default 16384
initial_window_size = 32768    # Conservative window size
max_header_list_size = 8192    # Conservative header list size
enable_push = false            # Disable server push
# Connection settings
tcp_keepalive = true
keepalive_interval_ms = 30000
keepalive_timeout_ms = 5000
http2_adaptive_window = false  # Disable adaptive window sizing

# Enhanced logging configuration
[logging]
# Add connection lifecycle events to INFO level
info_includes_connection_events = true
info_includes_transport_details = true
info_includes_retry_attempts = true
info_includes_fallback_behavior = true
# Add more granular error context
error_includes_stack_trace = true
error_includes_connection_state = true