# Workspace Qdrant MCP Configuration
# TOML format for memexd daemon

# Logging configuration
log_file = "/Users/chris/Library/Logs/memexd.log"

# Processing engine configuration
max_concurrent_tasks = 4
default_timeout_ms = 30000
enable_preemption = true
chunk_size = 1000
enable_lsp = true
log_level = "debug"
enable_metrics = true
metrics_interval_secs = 60

# Auto-ingestion configuration
[auto_ingestion]
enabled = true
auto_create_watches = true
include_common_files = true
include_source_files = true
target_collection_suffix = "scratchbook"
max_files_per_batch = 5
batch_delay_seconds = 2.0
max_file_size_mb = 50
recursive_depth = 5
debounce_seconds = 10

# Workspace directory (auto-detected from current working directory)
project_path = "/Users/chris/Dropbox/dev/ai/claude-code-cfg/mcp/workspace-qdrant-mcp"