//! Design tokens for the wqm TUI, transcribed from VISUAL-LANGUAGE.md r02.
//!
//! This module is the SSOT for the storyboard's neutrals and reserved hues. Widgets never
//! spell a colour literal — they name a rung on the emphasis ladder or a highlight role,
//! so a change here propagates to every frame and to the pantry's Styles tab.
//!
//! # Where a colour comes from is a choice, and [`Palette`] is that choice
//!
//! This module opened on a stricter promise: *no token emits absolute RGB* — every colour an
//! ANSI slot or a 256-table index, so a wqm screen sat inside the terminal the user configured
//! rather than overriding it. Two of the four sources below now break it deliberately, and the
//! reasoning that got there is the reason [`Palette`] exists as an enum rather than as a
//! constant.
//!
//! The promise costs something, and [`Palette`] is where the cost is made explicit.
//! Hues (selector, health) are always the 16 theme slots: those are exactly the colours a
//! theme redefines, so honouring the theme is both possible and correct. Neutrals are the
//! problem — r02 asks for eleven distinguishable greys (four emphasis rungs, two
//! structural rules, a header, two highlight fills, two layer backgrounds) and the 16-slot
//! palette contains **four** (black, bright-black, white, bright-white). The four modes are
//! the four honest answers to that shortfall; see each variant. **[`Palette::Bundled`] is the
//! default and what ships** (§15): the shortfall goes away when the colours arrive as data.
//!
//! # Two measured defects the modes answer to
//!
//! Both were found against ghostty running Catppuccin Mocha (`background = #1e1e2e`,
//! `foreground = #cdd6f4`), and both are properties of the design, not of that theme:
//!
//! 1. **[`Palette::Theme`] collapses roles.** Three pairs r02 insists must never share a
//!    treatment emit byte-identical SGR: cursor-mark/muted both `37`, faint/rule-internal
//!    both `90`, cursor-fill/layer-1 both `40`. Worse, that shared fill is slot 0, so on a
//!    black terminal the data cursor paints the background and the row vanishes — the
//!    exact failure §3 exists to prevent.
//! 2. **[`Palette::Indexed`]'s neutrals are neutral in a room where nothing else is.** A
//!    theme redefines only slots 0–15, so the 232–255 ramp stays true grey. Against a
//!    blue-violet field, simultaneous contrast makes true grey read as its opponent —
//!    yellow (Chris, 20260730). The ramp is not tinted; it is the only untinted thing on
//!    screen. Independently, r02's dark rungs assume a near-black background: `neutral(15)`
//!    resolves to `#262626`, which is *darker in blue* than Mocha's own background, so the
//!    layer fills and the cursor tint sink into the base rather than floating above it.
//!
//! [`Palette::Derived`] answers both, at the price named on the variant, and
//! [`Palette::Bundled`] answers them from a theme's own anchors instead of the terminal's.
//!
//! # A palette is a preference; what the terminal can emit is not
//!
//! [`Palette`] is only half the question. It says where a colour comes *from*; it cannot say
//! whether the stream can carry it. That second axis lives in [`crate::encoding`], is probed
//! rather than chosen, and caps this one: every token below resolves through [`family()`],
//! which is the lesser of the two. So `Derived` on a 16-colour login shell renders the
//! authored 16-colour ladder — not an approximation of the derived one.

use std::sync::atomic::{AtomicU8, Ordering};
use std::sync::RwLock;

use ratatui::style::{Color, Modifier, Style};
use ratatui::text::Span;
use ratatui_themes::ThemePalette;

use crate::encoding::{Encoding, Family};
use crate::terminal::{Endpoints, Rgb};

pub mod modal;

pub use modal::{under_modal, ModalScope};

/// How neutrals are sourced. Hues are unaffected — they are always theme slots.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Palette {
    /// Only the 16 theme slots. Maximally theme-adaptive: a user who restyles their
    /// terminal restyles wqm with it, greys included. The cost is collapse — eleven
    /// specified neutrals map onto four available slots, so the emphasis ladder loses
    /// rungs and several roles that r02 separates end up sharing a colour.
    Theme,
    /// Theme slots for hues, the xterm 256-table greyscale ramp (indices 232–255) for
    /// neutrals. Still terminal-resolved indices rather than absolute RGB, and still
    /// downgrades cleanly, but the ramp is standard rather than theme-defined — so the
    /// eleven rungs survive at the price of greys that do not follow the user's theme.
    Indexed,
    /// Neutrals generated by interpolating between the terminal's *own* background and
    /// foreground, which [`crate::terminal`] asks it for.
    ///
    /// This is the only mode that answers both defects above: the endpoints carry the
    /// theme's hue, so every rung inherits it and none reads as yellow; and anchoring 0%
    /// at the real background guarantees each rung is ordered above the base rather than
    /// sinking into it.
    ///
    /// It costs the module's opening promise: these tokens **do** emit absolute RGB. The
    /// mitigation is that the values are read off the user's terminal rather than chosen
    /// here, which is arguably a stronger form of honouring a theme than picking slots
    /// from it. It also costs r02's percentages their absolute meaning — under this mode a
    /// rung is a position on the terminal's contrast range, not a byte value. Needs
    /// truecolor and a terminal that answers `OSC 11`/`OSC 10`; without both, falls back
    /// to [`ENDPOINT_FALLBACK`].
    Derived,
    /// **§15's answer, and the default.** Everything comes from the bundled theme chosen with
    /// [`set_theme`]: the neutrals interpolate between the theme's own `bg` and `fg`, and the
    /// roles are the theme's own semantic fields rather than ANSI slots.
    ///
    /// This is [`Palette::Derived`] with the endpoints handed over as *data* instead of asked
    /// of the terminal, which is why it needs no `OSC` round trip and works with no terminal
    /// at all — a capture, a pipe, a CI run. It also answers the one thing `Derived` could
    /// not: `Derived` knows the terminal's two endpoints and nothing else, so `healthy` stayed
    /// an ANSI slot and could land anywhere the user had put green. A theme names all ten.
    ///
    /// It costs what `Derived` costs — absolute RGB — plus one thing more: the screen stops
    /// being *the terminal's* and becomes the theme's. §15 accepts that explicitly (*"full
    /// paint — the theme owns the background"*, superseding r02 §6), which is why
    /// [`screen_bg`] paints under this source and under no other.
    ///
    /// With no theme chosen it is [`Palette::Derived`] exactly: the terminal's endpoints, the
    /// slot hues, and layer 0 left alone. A default has to work before anyone configures it.
    Bundled,
}

/// What [`Palette::Derived`] interpolates between when the terminal was never asked, or
/// declined to answer.
///
/// Black to white: the assumption r02 was authored under, so the fallback reproduces the
/// authored ladder rather than inventing a third one.
pub const ENDPOINT_FALLBACK: Endpoints = Endpoints {
    background: Rgb::new(0, 0, 0),
    foreground: Rgb::new(255, 255, 255),
};

/// The rung the terminal's foreground *is*.
///
/// r02 puts `normal` at grey85 and [`normal()`] renders it as `Color::Reset` — the
/// terminal's own foreground. So under [`Palette::Derived`] the foreground endpoint is the
/// 85% rung, not the 100% one, and anchoring it at 100% compresses the whole ladder
/// downward. Measured on Catppuccin Mocha, that compression cost `faint` 5, `muted` 13 and
/// `cursor_mark` 20 luma against the [`Palette::Indexed`] ramp — the gap Chris saw as "not
/// as good as Indexed" (20260730). Anchoring here restores it and lets `strong` extrapolate
/// *past* the foreground, which is what a rung above the baseline has to do.
pub(crate) const NORMAL_RUNG: u8 = 85;

static ENDPOINTS: RwLock<Endpoints> = RwLock::new(ENDPOINT_FALLBACK);

/// Installs the endpoints [`Palette::Derived`] interpolates between.
///
/// Call once at startup, before a TUI takes the terminal — see
/// [`crate::terminal::detect`]. Rendering never queries, so a frame costs no round trip.
pub fn set_endpoints(endpoints: Endpoints) {
    if let Ok(mut slot) = ENDPOINTS.write() {
        *slot = endpoints;
    }
}

/// The endpoints currently in force.
pub fn endpoints() -> Endpoints {
    ENDPOINTS.read().map(|e| *e).unwrap_or(ENDPOINT_FALLBACK)
}

/// The source in force. **`Bundled` by default** (§15): the crate ships inside `wqm`, where a
/// theme is always chosen, and the three older sources are now comparisons rather than the
/// shipping answer. The default used to be [`Palette::Theme`], which meant every frame anyone
/// judged in the pantry was rendered through the six-of-eleven rung collapse §8.5 measured.
static ACTIVE: AtomicU8 = AtomicU8::new(Palette::Bundled as u8);

impl Palette {
    /// The palette every token currently resolves against.
    pub fn current() -> Palette {
        match ACTIVE.load(Ordering::Relaxed) {
            0 => Palette::Theme,
            1 => Palette::Indexed,
            2 => Palette::Derived,
            _ => Palette::Bundled,
        }
    }

    /// Every mode, in the order the sheet compares them.
    pub const ALL: [Palette; 4] = [
        Palette::Theme,
        Palette::Indexed,
        Palette::Derived,
        Palette::Bundled,
    ];

    /// The name this mode is spelled with in the pantry and in VISUAL-LANGUAGE.md.
    pub const fn label(self) -> &'static str {
        match self {
            Palette::Theme => "Theme",
            Palette::Indexed => "Indexed",
            Palette::Derived => "Derived",
            Palette::Bundled => "Bundled",
        }
    }

    /// Switch palettes. Lets one pantry render both modes so the trade-off is judged from
    /// a pair of frames rather than from an argument.
    pub fn set(palette: Palette) {
        ACTIVE.store(palette as u8, Ordering::Relaxed);
    }

    /// The family this source *wants* to be emitted in. What it actually gets is
    /// [`family()`], which is this capped by the encoding.
    pub const fn family(self) -> Family {
        match self {
            Palette::Theme => Family::Slots,
            Palette::Indexed => Family::Ramp,
            Palette::Derived | Palette::Bundled => Family::Rgb,
        }
    }
}

/// The two colours the neutral ladder is interpolated between — **the theme's when one is
/// chosen and the source is [`Palette::Bundled`], the terminal's otherwise.**
///
/// One function rather than a branch at every call site: the ladder, the wash and the layer
/// fills all read the base, and a base read from two different places is a base that can
/// disagree with itself. It is also the whole of what `Bundled` changes about neutrals —
/// `Derived`'s interpolation is reused verbatim, which is §15's *"nothing is thrown away"*.
fn ladder_endpoints() -> Endpoints {
    match (Palette::current(), theme()) {
        (Palette::Bundled, Some(palette)) => Endpoints {
            background: Rgb::from_color(palette.bg).unwrap_or_else(|| endpoints().background),
            foreground: Rgb::from_color(palette.fg).unwrap_or_else(|| endpoints().foreground),
        },
        _ => endpoints(),
    }
}

/// The bundled theme, but only where it is the thing being rendered from.
///
/// A theme that has been *chosen* is not the same as a theme that is *in force*: the pantry
/// sets one at startup and then renders the palette comparisons, and a `Theme`-sourced frame
/// that quietly picked up the bundled hues would make that comparison a lie. So every
/// role below asks through here, and every source other than [`Palette::Bundled`] gets `None`.
///
/// Public because [`crate::styles::palette`] renders the theme's own fields, and it has to
/// obey the same rule the roles do — a vocabulary frame that showed the bundled hues while a
/// slot palette was in force would be describing a screen nobody is looking at.
pub fn active_theme() -> Option<ThemePalette> {
    match Palette::current() {
        Palette::Bundled => theme(),
        _ => None,
    }
}

/// How every token below is emitted: **the lesser of what the source wants and what the
/// encoding permits**.
///
/// This one comparison is the whole Source × Encoding split. A preference cannot exceed a
/// capability, and a capability never dictates a preference below it — asking for
/// [`Palette::Theme`] on a truecolor terminal still gets theme slots, because slots are what
/// was asked for.
///
/// Degradation drops to the next family's **own** ladder rather than approximating the one
/// above it; [`crate::encoding`] carries the measurement that forced that rule.
pub fn family() -> Family {
    Palette::current()
        .family()
        .min(Encoding::current().family())
}

/// A reserved hue — or nothing if the encoding refuses colour, or the muted rung if a modal
/// owns the input.
///
/// The design anticipates the first: r02 §3 asks for a structural signature first with colour
/// reserved, and [`Health::glyph`] already carries state as shape. So dropping the hue costs
/// emphasis, not information.
///
/// The second is VL §6, and this is the whole of its implementation. **Every** reserved hue in
/// the vocabulary is emitted through here — [`selector`], [`selector_fg`], and everything
/// [`role`] answers: [`healthy`], [`degraded`], [`offline`], [`accent`], [`in_flight`], and so
/// [`Health::color`] with them. A widget therefore cannot forget the rule, because a widget
/// never sees it; see [`modal`] for the per-widget flag this replaced and why it leaked.
fn hue(color: Color) -> Color {
    match family() {
        Family::None => Color::Reset,
        _ => modal::or_muted(color),
    }
}

/// A neutral, named by the luminance percentage r02 specifies for it.
///
/// The percentage is the authored value; [`family()`] decides which ladder it is read off.
/// [`Family::Ramp`] picks the nearest step on the xterm greyscale ramp, whose steps run
/// 8, 18, … 238 at indices 232–255; [`Family::Slots`] collapses onto the nearest of the four
/// available slots; [`Family::None`] emits nothing, leaving the cell to whatever the terminal
/// is already painting.
///
/// Note what this does *not* do: it never converts one family's answer into another's. A
/// rung is always computed from its percentage, so degrading is choosing a different ladder
/// rather than approximating the one above — see [`crate::encoding`] for the measurement.
fn neutral(percent: u8) -> Color {
    match family() {
        Family::None => Color::Reset,
        Family::Slots => match percent {
            0..=24 => Color::Black,
            25..=55 => Color::DarkGray,
            56..=92 => Color::Gray,
            _ => Color::White,
        },
        Family::Ramp => {
            let target = percent as u16 * 255 / 100;
            match target {
                // Below the ramp's first step and above its last, the cube's true black
                // and true white are the closer answers.
                0..=7 => Color::Indexed(16),
                243..=255 => Color::Indexed(231),
                _ => {
                    let step = ((target - 8) as f32 / 10.0).round() as u16;
                    Color::Indexed(232 + step.min(23) as u8)
                }
            }
        }
        Family::Rgb => match active_theme() {
            // Four anchors when the theme names four; the chord when it names two.
            Some(theme) => along_curve(percent, &theme),
            None => along_chord(percent, ladder_endpoints()),
        },
    }
}


/// The ladder as a **straight chord** between two endpoints.
///
/// What every source but [`Palette::Bundled`] gets, because two endpoints is all they have:
/// [`crate::terminal::detect`] reads `OSC 11`/`OSC 10` and that is a background and a
/// foreground, full stop.
fn along_chord(percent: u8, endpoints: Endpoints) -> Color {
    let Endpoints {
        background,
        foreground,
    } = endpoints;
    let t = percent as f32 / NORMAL_RUNG as f32;
    let raw = [
        lerp(background.r, foreground.r, t),
        lerp(background.g, foreground.g, t),
        lerp(background.b, foreground.b, t),
    ];
    into_gamut([background.r, background.g, background.b], raw)
}

/// The ladder as a **piecewise curve through all four neutrals the theme names**.
///
/// # Why a curve and not a chord (Chris, 20260801)
///
/// *"Why would they not be anchored on theme.bg/selection/muted/fg, either on two points or
/// more if possible (though I can imagine that bg/selection/muted/fg is on a curve rather than
/// a line)"* — and he is right on both counts. §15 adopted a source that names **four**
/// neutrals and the ladder was using **two**, so a theme whose interior anchors sit off the
/// chord had its own neutral character straightened out by us.
///
/// Measured as perpendicular distance from the chord in Lab: Catppuccin Mocha's anchors sit
/// essentially *on* it (ΔE 0.1 and 0.6), which is why nothing looked wrong there — but
/// Dracula's `muted` is **25.5** off it, Cyberpunk's `selection` **25.2**, Kanagawa's `muted`
/// **15.5**. That is exactly the *"error some other palettes than catppuccin might surface"*.
/// So this is a no-op where a theme is linear and a correction where it is not.
///
/// # The anchors keep their MEASURED positions, and the rungs keep r02's
///
/// An anchor sits where its luminance puts it — `selection` at 9% on Mocha, `muted` at 38% —
/// and a rung stays at the percentage r02 names it with. The curve is the map between them, so
/// this changes what colour a rung *is*, never where it sits. `neutral(NORMAL_RUNG)` still
/// lands exactly on `fg` and `neutral(0)` still lands exactly on `bg`, which is what
/// [`normal`] and [`screen_bg`] rest on.
fn along_curve(percent: u8, theme: &ThemePalette) -> Color {
    let anchors = anchors(theme);
    let p = percent as f32;

    // Past the last anchor there is nothing to interpolate toward, so `strong` continues along
    // the ladder's overall axis — see `into_gamut` for what stops it from turning warm.
    let (base, target, span_start, span_len) = match anchors
        .windows(2)
        .find(|w| p >= w[0].0 && p <= w[1].0)
    {
        Some(w) => (w[0].1, w[1].1, w[0].0, w[1].0 - w[0].0),
        None => {
            let first = anchors[0];
            let last = anchors[anchors.len() - 1];
            (first.1, last.1, first.0, last.0 - first.0)
        }
    };

    let t = if span_len > 0.0 {
        (p - span_start) / span_len
    } else {
        0.0
    };
    let raw = [
        lerp(base[0], target[0], t),
        lerp(base[1], target[1], t),
        lerp(base[2], target[2], t),
    ];
    into_gamut(base, raw)
}

/// The theme's four neutrals as `(position on r02's scale, rgb)`, in ladder order.
///
/// Positions are **measured**, not assumed: `selection` and `muted` are wherever their
/// luminance puts them, which differs per theme and is the whole reason the curve is not a
/// chord. `theme_sheet::every_theme_gives_ten_distinct_roles_and_four_ordered_neutrals`
/// guarantees they are strictly ordered inside `[bg, fg]`, so the windows below always bracket.
fn anchors(theme: &ThemePalette) -> [(f32, [u8; 3]); 4] {
    let channels = |colour: Color| match Rgb::from_color(colour) {
        Some(rgb) => [rgb.r, rgb.g, rgb.b],
        None => [0, 0, 0],
    };
    let at = |colour: Color| rung_of(colour, theme);
    [
        (0.0, channels(theme.bg)),
        (at(theme.selection), channels(theme.selection)),
        (at(theme.muted), channels(theme.muted)),
        (NORMAL_RUNG as f32, channels(theme.fg)),
    ]
}

/// Relative luminance — the measure r02 names its rungs in.
fn luminance(colour: Color) -> f32 {
    match Rgb::from_color(colour) {
        Some(rgb) => 0.2126 * rgb.r as f32 + 0.7152 * rgb.g as f32 + 0.0722 * rgb.b as f32,
        None => 0.0,
    }
}

/// Where a colour sits on r02's ladder — **measured**, not assumed.
///
/// `bg` is 0 and `fg` is [`NORMAL_RUNG`] by definition, and everything else lands wherever its
/// luminance puts it. This is the unit the design names its rungs in, so it is also the unit a
/// question like *"is this brighter than `normal`?"* has to be asked in.
///
/// Extracted because it was written out three times — inside [`anchors`], inside a test, and a
/// fourth time it was about to be written in [`crate::styles::strong`]. A measure with three
/// copies is a measure that can disagree with itself.
///
/// ⚠ **This has a direction and [`delta_e`] does not**, which is the whole reason it is here.
/// ΔE said the accent-tinted `strong` candidates were well clear of body text; they sit at rungs
/// 80 and 77 against `normal` at 85, i.e. *darker* than the text they have to out-shout. A
/// distance cannot express "brighter than".
pub(crate) fn rung_of(colour: Color, theme: &ThemePalette) -> f32 {
    let (bg, fg) = (luminance(theme.bg), luminance(theme.fg));
    if (fg - bg).abs() < f32::EPSILON {
        0.0
    } else {
        NORMAL_RUNG as f32 * (luminance(colour) - bg) / (fg - bg)
    }
}

/// Bring an extrapolated colour back into gamut **without turning it**.
///
/// # The defect this fixes, which Chris saw by eye
///
/// *"Even for catppuccin, the strong is clearly a tad warmer than all the other greys."* He was
/// right, and the cause is exact: `strong` is rung 100 on a scale whose foreground is 85, so it
/// is extrapolated *past* `fg`, and clamping each channel independently at 255 stops whichever
/// channel saturates first while the others keep climbing. Mocha's foreground is blue-tinted,
/// so **blue** hits the ceiling and red and green carry on — the loudest rung on the screen
/// drifts warm exactly where it is most visible.
///
/// Measured over the fifteen bundled themes: **8 clamp at least one channel**, and on four of
/// them the hue shift is plainly visible — Mocha ΔE 11.1, TokyoNight 12.5, RosePine 11.5,
/// GruvboxDark 5.8 (2.3 is a just-noticeable difference).
///
/// The fix keeps the *direction* and gives up only distance: if any channel overshoots, the
/// whole offset from the base is scaled back by the largest overshoot, so the result is the
/// brightest colour still on that line and in gamut. A theme whose foreground is already near
/// white loses almost nothing (Dracula ΔE 1.5); a tinted one keeps its tint.
pub(crate) fn into_gamut(base: [u8; 3], raw: [f32; 3]) -> Color {
    // How far each channel wanted to travel, and how far it *could* before hitting the wall it
    // is heading for. The ratio of the two is how much this channel overreached; the largest
    // of the three is how far back the whole offset has to be scaled.
    //
    // **The ratio is offset-to-headroom, not value-to-255**, and the difference is not
    // academic: the first version of this divided by `raw / 255` and left Dracula's `strong`
    // 3.1 units off the axis — a channel that starts at 40 and wants to reach 285 has
    // overreached by 245/215, not by 285/255. `strong_stays_on_the_themes_own_axis…` is what
    // said so, which is the whole reason it measures colinearity instead of eyeballing a hex.
    let overreach = (0..3).fold(1.0f32, |worst, i| {
        let (base, raw) = (base[i] as f32, raw[i]);
        let headroom = if raw > 255.0 {
            255.0 - base
        } else if raw < 0.0 {
            -base
        } else {
            return worst;
        };
        // A channel already at the wall cannot travel at all; nothing can be scaled to fit, so
        // leave it to the final clamp rather than dividing by zero.
        if headroom.abs() < f32::EPSILON {
            worst
        } else {
            worst.max((raw - base) / headroom)
        }
    });

    let scale = |base: u8, value: f32| {
        (base as f32 + (value - base as f32) / overreach)
            .round()
            .clamp(0.0, 255.0) as u8
    };
    Color::Rgb(
        scale(base[0], raw[0]),
        scale(base[1], raw[1]),
        scale(base[2], raw[2]),
    )
}

/// CIE76 perceptual distance — **the unit every colour distance in this crate is recorded in**.
///
/// Public to the crate because it stopped being a test-only concern: `styles::strong` needs it
/// at render time to back a candidate off the hues §3 reserves, and a second implementation of
/// a colour metric is a second set of numbers that can disagree with the documented ones. The
/// recurring bug this crate has paid for twice is a threshold compared in the wrong unit
/// (`WASH_MIX`'s 11-14 read as byte distance, a band asserted in sRGB), so there is one
/// function and the numbers in the documents all mean it.
///
/// Rule of thumb: **2.3 is a just-noticeable difference**; above 5 is plainly a different
/// colour.
///
/// CIELAB rather than sRGB bytes, so a difference between two colours can be compared to a
/// difference between two others. Byte distance cannot do that — it makes two dark colours look
/// closer than two light ones that are equally distinguishable.
pub(crate) fn lab(colour: Color) -> (f32, f32, f32) {
    let (r, g, b) = match colour {
        Color::Rgb(r, g, b) => (r as f32 / 255.0, g as f32 / 255.0, b as f32 / 255.0),
        other => panic!("expected RGB, got {other:?}"),
    };
    let linear = |u: f32| {
        if u <= 0.04045 {
            u / 12.92
        } else {
            ((u + 0.055) / 1.055).powf(2.4)
        }
    };
    let (r, g, b) = (linear(r), linear(g), linear(b));
    // sRGB → XYZ (D65), normalised by the white point.
    let x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047;
    let y = 0.2126 * r + 0.7152 * g + 0.0722 * b;
    let z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883;
    let f = |t: f32| {
        if t > 0.008856 {
            t.cbrt()
        } else {
            7.787 * t + 16.0 / 116.0
        }
    };
    let (fx, fy, fz) = (f(x), f(y), f(z));
    (116.0 * fy - 16.0, 500.0 * (fx - fy), 200.0 * (fy - fz))
}


/// Both ends of the ladder are the theme's own colours, exactly, on every theme.
///
/// [`screen_bg`] returns `bg` and [`normal`] returns `fg`, and both are *documented* as
/// landing on the anchors by construction — `NORMAL_RUNG` exists for no other reason. That
/// was true of the chord and it has to stay true of the curve, because a rounding error at
/// either end would put the screen's full paint one byte off the theme's background and
/// nothing on screen would say so.
#[test]
fn the_ladder_still_begins_and_ends_exactly_on_the_themes_own_anchors() {
    let _serial = crate::global_state_lock();
    let restore = (Palette::current(), Encoding::current());
    Palette::set(Palette::Bundled);
    Encoding::set(Encoding::TrueColor);

    for name in ratatui_themes::ThemeName::all() {
        let theme = name.palette();
        set_theme(theme);
        assert_eq!(neutral(0), theme.bg, "{name:?}: rung 0 is not the background");
        assert_eq!(
            neutral(NORMAL_RUNG),
            theme.fg,
            "{name:?}: rung {NORMAL_RUNG} is not the foreground"
        );
    }

    Palette::set(restore.0);
    Encoding::set(restore.1);
}

/// `strong` keeps the theme's tint instead of drifting warm — the defect Chris saw by eye.
///
/// *"Even for catppuccin, the strong is clearly a tad warmer than all the other greys."* It
/// was: rung 100 extrapolates past the foreground, and clamping each channel independently
/// at 255 stopped whichever saturated first — blue, on a blue-tinted theme — while red and
/// green carried on. Mocha's `strong` was `#ecf6ff` against a hue-preserving `#dae4ff`,
/// **ΔE 11.1**, on the loudest rung the design has.
///
/// The property asserted is the one [`into_gamut`] actually guarantees: `strong` stays on
/// the ray from the background through the foreground. Distance may be given up; direction
/// may not. Checked on every theme, because the eight that clamp are not the same eight on
/// any other palette.
#[test]
fn strong_stays_on_the_themes_own_axis_rather_than_clamping_toward_warm() {
    let _serial = crate::global_state_lock();
    let restore = (Palette::current(), Encoding::current());
    Palette::set(Palette::Bundled);
    Encoding::set(Encoding::TrueColor);

    for name in ratatui_themes::ThemeName::all() {
        let theme = name.palette();
        set_theme(theme);

        let channels = |colour: Color| {
            let rgb = Rgb::from_color(colour).expect("a bundled theme is RGB");
            [rgb.r as f32, rgb.g as f32, rgb.b as f32]
        };
        let top = strong();
        let (bg, fg, top_ch) = (channels(theme.bg), channels(theme.fg), channels(top));
        let axis = [fg[0] - bg[0], fg[1] - bg[1], fg[2] - bg[2]];
        let reached = [
            top_ch[0] - bg[0],
            top_ch[1] - bg[1],
            top_ch[2] - bg[2],
        ];

        // Colinearity: the cross product of the two offsets is zero when `strong` lies on
        // the axis. Scaled by the axis length so the tolerance means the same on a theme
        // with a short ladder as on one with a long one.
        let cross = [
            axis[1] * reached[2] - axis[2] * reached[1],
            axis[2] * reached[0] - axis[0] * reached[2],
            axis[0] * reached[1] - axis[1] * reached[0],
        ];
        let length = (axis[0] * axis[0] + axis[1] * axis[1] + axis[2] * axis[2]).sqrt();
        let off_axis =
            (cross[0] * cross[0] + cross[1] * cross[1] + cross[2] * cross[2]).sqrt() / length;

        // One byte of rounding per channel, no more. The clamped version was 20+ off here.
        assert!(
            off_axis < 2.0,
            "{name:?}: strong is {off_axis:.1} off the bg->fg axis — it clamped and turned"
        );
        assert!(
            delta_e(top, theme.fg) > 1.0,
            "{name:?}: strong collapsed onto the foreground, so the top rung says nothing"
        );
    }

    Palette::set(restore.0);
    Encoding::set(restore.1);
}

/// The ladder follows the theme's own curve, not the chord between its ends.
///
/// Chris, 20260801: *"why would they not be anchored on theme.bg/selection/muted/fg … I can
/// imagine that bg/selection/muted/fg is on a curve rather than a line."* They are, on some
/// themes: measured as perpendicular distance from the chord in Lab, Mocha's interior
/// anchors sit essentially *on* it (0.1 and 0.6) while **Dracula's `muted` is 25.5 off**.
///
/// Dracula is therefore the theme this can be asserted on — on Mocha a curve and a chord
/// are the same thing and the test would pass without the feature existing, which is
/// exactly the shape of guard this crate keeps being bitten by. At `muted`'s own position
/// the curve must land on `muted`; the chord lands somewhere else entirely.
#[test]
fn a_rung_at_an_anchors_position_lands_on_that_anchor() {
    let _serial = crate::global_state_lock();
    let restore = (Palette::current(), Encoding::current());
    Palette::set(Palette::Bundled);
    Encoding::set(Encoding::TrueColor);

    let theme = ratatui_themes::ThemeName::Dracula.palette();
    set_theme(theme);

    let position = rung_of(theme.muted, &theme).round() as u8;

    let curved = neutral(position);
    let chord = along_chord(
        position,
        Endpoints {
            background: Rgb::from_color(theme.bg).expect("rgb"),
            foreground: Rgb::from_color(theme.fg).expect("rgb"),
        },
    );

    assert!(
        delta_e(curved, theme.muted) < delta_e(chord, theme.muted),
        "the curve ({:?}, ΔE {:.1}) is no nearer Dracula's muted than the chord ({:?}, ΔE \
         {:.1}) — the anchors are not being used",
        curved,
        delta_e(curved, theme.muted),
        chord,
        delta_e(chord, theme.muted)
    );
    assert!(
        delta_e(curved, theme.muted) < 3.0,
        "at muted's own position the ladder should BE muted, not {curved:?} (ΔE {:.1})",
        delta_e(curved, theme.muted)
    );

    Palette::set(restore.0);
    Encoding::set(restore.1);
}

/// CIE76 ΔE — the measure every colour distance in this module is recorded in.
pub(crate) fn delta_e(a: Color, b: Color) -> f32 {
    let (l1, a1, b1) = lab(a);
    let (l2, a2, b2) = lab(b);
    ((l1 - l2).powi(2) + (a1 - a2).powi(2) + (b1 - b2).powi(2)).sqrt()
}

/// One channel of the derived ladder.
///
/// Interpolated in sRGB byte space rather than in linear light, because r02's rung names
/// are byte values — its `grey19` means byte 48, which is what [`Palette::Indexed`] also
/// resolves it to. Interpolating in linear light would honour the *percentages* as
/// luminance and lift the dark rungs far off the base: measured on Catppuccin Mocha it put
/// `layer1_bg` at `#5a5e6f`, a mid-grey, where §6 asks for "dark but distinctly above the
/// base". Byte-space keeps the authored spacing and only re-anchors its ends.
fn lerp(from: u8, to: u8, t: f32) -> f32 {
    from as f32 + (to as f32 - from as f32) * t
}

/// One channel of a plain two-colour blend, rounded into a byte.
///
/// The wash's mix, which never leaves the segment between its two ends and so cannot overshoot
/// — unlike the ladder, whose top rung extrapolates past the foreground and needs
/// [`into_gamut`] to come back without turning.
fn mix(from: u8, to: u8, t: f32) -> u8 {
    lerp(from, to, t).round().clamp(0.0, 255.0) as u8
}

/// One rung of the ladder, by the luminance percentage r02 names it with.
///
/// The named tokens below are how widgets should reach a rung — `faint()` says why the
/// colour was chosen, `neutral_at(50)` does not. This exists for the reference sheet, which
/// has the opposite job: enumerating the ladder as a ladder, including the rungs no token
/// is named after.
pub fn neutral_at(percent: u8) -> Color {
    neutral(percent)
}

// --- §2 emphasis ladder -------------------------------------------------------------
// Default posture: most of the screen is muted or faint. Normal is the zone you are in;
// strong is the few things that matter.

/// De-emphasised metadata that must still be legible (default-column values).
pub fn faint() -> Color {
    neutral(50)
}
/// Inactive tabs, unfocused zone bodies, timestamps, paths, key hints.
pub fn muted() -> Color {
    neutral(62)
}
/// Body text of the focused zone; the baseline.
///
/// This rung is the terminal's own foreground in every mode. The baseline is precisely the
/// text that should look like everything else the user reads in that window.
///
/// # Under `Derived` it says so explicitly, and that is not a change of intent
///
/// `Color::Reset` asks the terminal for its foreground. [`Palette::Derived`] has already
/// *been told* the foreground — that is what [`crate::terminal::detect`] read — and
/// [`NORMAL_RUNG`] is defined so that `neutral(NORMAL_RUNG)` interpolates to exactly that
/// endpoint. So the two are the same colour by construction, and emitting it directly only
/// makes this rung consistent with the other ten, which are already baked RGB.
///
/// It buys a real property: a renderer with no terminal to ask cannot resolve `Reset`, and
/// invents something instead. `soft_ratatui` resolves a `Reset` foreground to a fixed
/// `#ccccff` — near enough to be invisible against a dark theme and badly wrong against a
/// light one — so before this, [`crate::capture`] produced frames whose baseline text was
/// the one rung not derived from the theme. Under the slot-sourced palettes there is
/// nothing better to reach for, so they keep `Reset`.
///
/// # Under a modal it is [`muted`]
///
/// VL §6 says a page beneath a modal carries no emphasis at all (Chris, 2026-09-07: *"we still
/// have colors on the screen while all should be muted"*). The baseline is the brightest text a
/// page wears by default, so it is the first thing to go — routed through
/// [`crate::tokens::modal::or_muted`] like every other bright text rung, so a widget that draws
/// its body with [`normal`] asks no question about modals.
pub fn normal() -> Color {
    modal::or_muted(match family() {
        Family::Rgb => neutral(NORMAL_RUNG),
        _ => Color::Reset,
    })
}
/// Primary figures, and any value that differs from its default. Weight does the work;
/// the colour only stops it receding.
///
/// # The slot-based answer is measurably wrong
///
/// Under the two slot-sourced palettes this is `Color::White` — ANSI slot 15 — because
/// there is nothing brighter available. But a theme is free to place slot 15 *below* its
/// foreground, and Catppuccin Mocha does exactly that: slot 15 is `#bac2de` (luma 194)
/// against a foreground of `#cdd6f4` (luma 214), so the ladder's loudest rung renders 20
/// luma **darker** than its baseline and only the bold modifier hides it.
///
/// [`Palette::Derived`] can do better, because it is not picking from a fixed set: it
/// extrapolates past the foreground and gets a rung that is genuinely above `normal`.
///
/// # Under a modal it is [`muted`]
///
/// The loudest rung on the screen is the one a modal is most obliged to quiet — emphasis is a
/// highlight too (VL §6), so [`strong`] collapses onto [`muted`] with the rest of the bright
/// text rungs.
pub fn strong() -> Color {
    modal::or_muted(match family() {
        Family::Rgb => neutral(100),
        // Nothing brighter than slot 15 exists to reach for, and under `None` the bold
        // modifier in `strong_style` is the entire signal — which r02 says it mostly is
        // anyway ("weight does the work").
        Family::None => Color::Reset,
        _ => Color::White,
    })
}

// --- §2 / §6 structure --------------------------------------------------------------

/// Top and bottom frame rules — lighter, because they underline the screen.
pub fn rule_frame() -> Color {
    neutral(54)
}
/// Internal zone separators — darker, because they divide within.
pub fn rule_internal() -> Color {
    neutral(30)
}
/// Column headers are structure, not data: the body-text foreground, in italics.
///
/// A header is not bold (Chris, 2026-09-07) — that reads as a heading rather than as a label
/// under it — so it keeps the SAME foreground the body text wears and marks itself with
/// [`Modifier::ITALIC`] instead of weight. The italic is added by the tables that draw the
/// header ([`crate::panes::cell::table`]); this returns the colour, which is [`normal`]
/// exactly, so a header can never land on a rung the data beneath it does not use.
pub fn header() -> Color {
    normal()
}

// --- §3 highlight roles -------------------------------------------------------------

/// The reserved selector hue. Cyan appears in NOTHING else: if it is a cyan block, it is
/// what you have selected. A theme slot, so a user who has retuned cyan retunes the
/// selector with it.
pub fn selector() -> Color {
    match active_theme() {
        // §15 left this field to us: `accent` or `info`. `info` is measured blue/cyan in
        // every bundled theme while `accent` swings purple→pink→cyan, and §3 reserves the
        // selector ABSOLUTELY — a selector that lands on the theme's error hue breaks the one
        // rule the whole highlight system rests on. `tokens::tests` measures the collision.
        Some(palette) => hue(palette.info),
        None => hue(Color::Cyan),
    }
}
/// Text sitting inside an inverted selector block.
pub fn selector_fg() -> Color {
    hue(Color::Black)
}

/// An inverted highlight block — a hue fill with dark text on it.
///
/// Where the encoding refuses colour, this becomes reverse video, which is what an inverted
/// block structurally *is*: the selector survives as a swapped foreground and background
/// rather than disappearing. Without it, `fill` and the text on it both resolve to
/// `Color::Reset` and a selected row becomes indistinguishable from an unselected one —
/// which is the same class of failure as [`Palette::Theme`]'s invisible cursor row.
///
/// # Under a modal there is no block at all
///
/// A fill IS the highlight, so §6 takes it whole: the block becomes bold muted text, keeping
/// its own padding so nothing on the row moves. That is the treatment the tab bar and the
/// Dashboard's cell headings each used to spell for themselves; stating it here is what lets
/// both of them stop asking whether a modal is open. Modifiers a caller adds are patched on
/// top of this style as they are on top of the fill, so a block that was bold stays bold.
pub fn inverted(fill: Color) -> Style {
    if under_modal() {
        return muted_style().add_modifier(Modifier::BOLD);
    }
    match family() {
        Family::None => Style::default().add_modifier(Modifier::REVERSED),
        _ => Style::default().fg(selector_fg()).bg(fill),
    }
}
/// The data cursor's row tint — a subtle darker fill, deliberately not an inverse block.
pub fn cursor_bg() -> Color {
    neutral(19)
}

/// The glyph a selected row wears in its gutter (Chris, 20260907, ruling 10).
///
/// A left half-block rather than a full one: it marks the row's edge without becoming a column
/// of its own, and it survives an encoding that refuses colour, which is the whole reason the
/// ruling names a glyph AND a hue rather than a hue alone.
pub const SELECTED_BAR: char = '▎';

/// The **selection** hue — the gutter bar's colour, and what the row's wash is mixed toward.
///
/// Catppuccin's `lavender` on a flavour, `secondary` on every other theme; the rule itself is
/// [`crate::categorical::selected_of`], because deciding it means knowing what a flavour is.
/// Magenta is the slot-family stand-in, chosen the way every other slot value is: a hue no role
/// in the ten already spends.
///
/// Through [`hue`] like every reserved field, so a modal takes it away with everything else
/// (VL §6) — a selection is a highlight, not a system condition.
pub fn selected() -> Color {
    match active_theme() {
        Some(palette) => hue(crate::categorical::selected_of(&palette)),
        None => hue(Color::Magenta),
    }
}

/// A selected row's fill: the terminal's own background pulled toward [`selected`] by
/// [`WASH_MIX`] — the same strength, and the same reasoning, as the unreachable-daemon wash.
///
/// # [`None`] below RGB, and the bar carries the selection alone
///
/// Only [`Family::Rgb`] can express "this background, but more lavender". A fixed substitute
/// would be a full-row fill chosen without knowing the theme's polarity, which is unreadable
/// exactly where it matters most. So below RGB this returns [`None`] and [`SELECTED_BAR`] is
/// the whole of the mark — structure first, colour reserved, which is the rule the condition
/// wash already follows.
pub fn selected_bg() -> Option<Color> {
    if family() != Family::Rgb {
        return None;
    }
    let bg = ladder_endpoints().background;
    // The same fallback shape as the condition wash: a named slot colour has no channels to mix,
    // so where the hue cannot be read as RGB the mix goes toward a written-down lavender. It is
    // reached only with no bundled theme in force, where `selected()` itself is the slot
    // stand-in — the bar is then magenta over a lavender wash, which is two stand-ins agreeing
    // about what they stand for.
    let toward = Rgb::from_color(selected()).unwrap_or(Rgb::new(0xb4, 0xbe, 0xfe));
    Some(Color::Rgb(
        mix(bg.r, toward.r, WASH_MIX),
        mix(bg.g, toward.g, WASH_MIX),
        mix(bg.b, toward.b, WASH_MIX),
    ))
}
/// The leading `▸` marker on the data cursor row.
///
/// # Under a modal it is [`muted`]
///
/// The mark sits above the muted rung to distinguish the cursor row from the rows around it,
/// which makes it one of the bright text rungs — and a bright rung is exactly what a modal
/// takes away (VL §6).
pub fn cursor_mark() -> Color {
    modal::or_muted(neutral(70))
}
/// The editing cell fill — lighter than the cursor tint, so it reads as "you type HERE".
pub fn edit_bg() -> Color {
    neutral(35)
}

// --- §4 health ----------------------------------------------------------------------
// Only the glyph carries colour; the surrounding label stays muted.

// §15: a bundled theme names these directly, so they stop being a guess about where the user
// put green. The mapping is role-for-role — our language asks for *offline*, never for red,
// and `error`/`warning`/`success` are the theme's words for the same three ideas.
pub fn healthy() -> Color {
    role(|palette| palette.success, Color::Green)
}
pub fn degraded() -> Color {
    role(|palette| palette.warning, Color::Yellow)
}
pub fn offline() -> Color {
    role(|palette| palette.error, Color::Red)
}

/// A reserved hue from the theme when one is in force, and its ANSI slot otherwise.
fn role(from_theme: fn(&ThemePalette) -> Color, slot: Color) -> Color {
    match active_theme() {
        Some(palette) => hue(from_theme(&palette)),
        None => hue(slot),
    }
}

// --- the hues beyond the health three --------------------------------------------
// §10 left `accent` and `secondary` carrying no role — "unclaimed — headroom". The constant
// top spends `accent` on the jump digit, which is free. `info` is NOT free, and the one
// datum that spends it is named and dated below.

/// The **jump digit** on a tab (`1` in `1 Dashboard`, `0` in `10 Service`).
///
/// §3 keeps the number outside the selector block because it is a jump hint rather than part
/// of the selection, and until now it recited that intent in muted grey — the same rung as the
/// label it precedes, which says "this is metadata" and not "this is the key you press".
/// `accent` is the field §10 measured as *unclaimed headroom*, and it is the right one to
/// spend here precisely because it is not reserved: a digit painted in the selector's `info`
/// would read as a selection, and one painted in a health hue would read as an alarm.
///
/// No underline, but **bold** with it (Chris, 20260907: *"so that they are more visible on the
/// screen"*) — superseding 20260906's *"the hue is the whole signal"*, which left the digit
/// quieter than the block beside it and, at one column wide, quieter than it needed to be. The
/// weight survives a modal; the hue does not (VL §6).
///
/// Magenta where no theme is chosen: the bare-library fallbacks are ANSI slots, and magenta is
/// the only one left after cyan (the selector) and green/yellow/red (the three health states).
pub fn accent() -> Color {
    role(|palette| palette.accent, Color::Magenta)
}

/// **Work in flight** — the queue's `in progress` count, and any future datum whose meaning is
/// *this is happening now*.
///
/// Chris, 20260907: *"can we use sapphire for in-progress since it is a categorical color
/// now?"* — and the answer is that it resolves in two ways, because only some themes have a
/// sapphire to spend.
///
/// # The one-day history is the whole justification, so it is written down
///
/// On 20260906 this datum was `info` — the selector's own field — as a **dated, deliberate
/// exception** to §3's absolute reservation. Chris was told plainly that blue is the
/// selector's hue and asked for blue anyway. The exception was uncomfortable and stayed
/// narrow, and a day later the categorical tier gave it somewhere better to go: a Catppuccin
/// flavour ships a `sapphire` that carries no role, so on those four themes this hue is its
/// own and §3 is absolute again. On the other eleven there is still nothing spare, so they
/// keep the exception.
///
/// The rule lives in [`crate::categorical::in_flight_of`], not here: choosing between the two
/// means knowing what a Catppuccin flavour *is*, and that is the tier's knowledge rather than
/// this module's. This is the accessor; that is the decision. §10 in VISUAL-LANGUAGE.md
/// carries both.
///
/// Blue where no theme is chosen at all — the same fallback the retired `info()` accessor had,
/// since a bare library has neither a flavour nor a role table to consult.
pub fn in_flight() -> Color {
    role(crate::categorical::in_flight_of, Color::Blue)
}

// --- §6 layers, and the one condition that repaints layer 0 --------------------------

/// A screen-wide condition — the state of the *system*, not of a widget.
///
/// Chris, 20260731: **when the daemon is unreachable the whole TUI carries a red wash, on
/// every tab, until it comes back.** That is a sustained condition, and it is exactly what a
/// toast cannot express: a toast announces a transition and then expires, while "nothing you
/// see is live" has to stay said for as long as it is true. The two are complementary — the
/// transition toasts, the condition washes.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Condition {
    Nominal,
    /// The liveness master is not answering (VISUAL-LANGUAGE §7). Every reading on screen is
    /// stale by definition, which is why this is a whole-screen signal rather than one zone's.
    DaemonUnreachable,
}

static CONDITION: AtomicU8 = AtomicU8::new(Condition::Nominal as u8);

impl Condition {
    pub fn current() -> Condition {
        match CONDITION.load(Ordering::Relaxed) {
            0 => Condition::Nominal,
            _ => Condition::DaemonUnreachable,
        }
    }

    pub fn set(condition: Condition) {
        CONDITION.store(condition as u8, Ordering::Relaxed);
    }
}

/// How far the wash pulls the terminal's own background toward red.
///
/// **Subtle, deliberately** (Chris, 20260731: *"it should be subtle as not destroy visibility
/// across the window"*). The wash sits behind every glyph on screen, and the text under it is
/// exactly the text the user needs in order to see what broke — so the tint's job is to be
/// noticed peripherally, not to be looked at. The first cut was 0.22, which read as a red
/// screen rather than a red-tinted one.
///
/// # Not configurable (Chris, 20260731)
///
/// This is a **design constant, not a knob**, and it is the one number on this surface that is
/// deliberately not going to N7. A user who can soften the wash can switch off the only signal
/// that says *nothing on this screen is live* — and the moment it matters is exactly the moment
/// they cannot be asked to have configured it correctly. The dwell, the sound and the settling
/// window stay configurable (`UIQ-006`, `UIQ-007`, `UIQ-008`); this does not.
///
/// Judge it, do not argue it: `cargo pantry dump "Surface" --variant "Wash Strengths"` puts
/// the candidates side by side with real text on them.
///
/// # Why 0.14 and not the 0.10 that looked right
///
/// Chris chose it *"to be consistent for both"* (20260731) — for the wash as it is today and
/// for the wash after `OSC 4`. Today the tint is mixed toward **pure** red; once the terminal's
/// own sixteen slots can be queried it mixes toward the **theme's** red, which is a gentler
/// move from the same background. Measured as CIE76 distance from the base:
///
/// | | 0.10 | 0.14 |
/// |---|---|---|
/// | toward pure red (today) | ΔE 11–14 | ΔE 16–19 |
/// | toward the theme's red (after `OSC 4`) | ΔE 8–10 | **ΔE 11–14** |
///
/// So 0.14 after `OSC 4` is what 0.10 is now, and the constant does not move when that decision
/// lands. The cost is paid in the interim: until then the wash is one step louder than the
/// value that was called perfect.
pub const WASH_MIX: f32 = 0.14;

/// Layer 0's background: [`None`] normally — §6 says a full screen keeps the terminal's own
/// and is never repainted — and the wash while the daemon is unreachable.
///
/// **The wash answers "dark or light red?" with "whichever the user's terminal is."** It is
/// the terminal's *own* background pulled toward red by [`WASH_MIX`], so a dark theme gets a
/// dark red and a light theme a light one, and the polarity the user chose is preserved
/// rather than overridden.
///
/// # It needs RGB, and below that the wash is not attempted
///
/// Only [`Family::Rgb`] can express "this background, but redder". The slot and ramp families
/// would have to substitute a *fixed* red — ANSI red as a full-screen fill is unreadable, and
/// an indexed dark red assumes a polarity those families cannot know. So below RGB this
/// returns [`None`] and the structural marker carries the condition alone, which is r02 §3's
/// own rule: structure first, colour reserved. `crate::widgets::surface` draws both.
pub fn layer0_bg() -> Option<Color> {
    wash(Condition::current())
}

/// [`layer0_bg`] for a *stated* condition rather than the process-global one.
///
/// A frame has to be able to render the unreachable screen without the process being in that
/// state — the pantry does exactly this, and so does a capture. The global exists so a widget
/// deep in a render tree can ask without being handed a context; every renderer that takes a
/// condition as a parameter must reach the token through this, or it renders one condition
/// while asking about another. That failure is not hypothetical: it is what the surface tests
/// caught the first time this was wired, and it is the same shape as the two-globals rule
/// already recorded for `Palette` and `Encoding`.
pub fn wash(condition: Condition) -> Option<Color> {
    wash_at(condition, WASH_MIX)
}

/// [`wash`] at a stated strength, so candidate values can be put side by side in one frame
/// rather than compared across two runs of the same binary.
///
/// The comparison is the point: "subtle" is not a number anyone can argue their way to, and a
/// tint judged alone always looks reasonable.
pub fn wash_at(condition: Condition, mix_toward_red: f32) -> Option<Color> {
    match (condition, family()) {
        (Condition::Nominal, _) => None,
        (Condition::DaemonUnreachable, Family::Rgb) => {
            let bg = ladder_endpoints().background;
            // §15 item 4: toward the THEME's error rather than toward pure red — a gentler
            // move from the same base, which is what WASH_MIX 0.14 was chosen to survive.
            // Pure red where no theme names one, which is the value r02 was measured against.
            let red = active_theme()
                .and_then(|palette| Rgb::from_color(palette.error))
                .unwrap_or(Rgb::new(255, 0, 0));
            let strength = mix_toward_red.clamp(0.0, 1.0);
            Some(Color::Rgb(
                mix(bg.r, red.r, strength),
                mix(bg.g, red.g, strength),
                mix(bg.b, red.b, strength),
            ))
        }
        (Condition::DaemonUnreachable, _) => None,
    }
}

/// Layer 1 — a modal over a full screen: dark, but distinctly above the base.
pub fn layer1_bg() -> Color {
    neutral(15)
}
/// Layer 2 — a modal over a modal: distinct and lighter, so the stack stays legible.
pub fn layer2_bg() -> Color {
    neutral(23)
}

/// The bundled theme in force, or [`None`] while nothing has chosen one.
///
/// A `RwLock` rather than an atomic because a [`ThemePalette`] is ten colours; it is written
/// once at startup and read on every cell, which is what `RwLock` is for.
static THEME: RwLock<Option<ThemePalette>> = RwLock::new(None);

/// Choose the bundled theme every screen paints from.
pub fn set_theme(palette: ThemePalette) {
    *THEME.write().expect("theme lock") = Some(palette);
}

/// The bundled theme, if one has been chosen.
pub fn theme() -> Option<ThemePalette> {
    *THEME.read().expect("theme lock")
}

/// The colour a **full screen** paints under everything — §15's *"full paint: the theme owns
/// the background"*, which supersedes r02 §6's *"layer 0 is never repainted"*.
///
/// [`None`] under every source but [`Palette::Bundled`], and under that one only once a theme
/// has been chosen. Then §6's old rule still applies: the screen keeps the terminal's own
/// background and nothing is painted, which is what keeps every widget preview and every
/// slot-sourced frame rendering exactly as it did.
///
/// # The probe is over, and this is the first anchor now
///
/// It returned the theme's *second* anchor (`selection`) on Chris's instruction (20260731), so
/// that any cell the paint failed to reach would show up as a hole rather than blend in. It
/// did its job — measured on the Service view at 125×34, every cell painted, none left at the
/// terminal's default — so the deliberate wrong colour is retired and this is `bg`.
/// `views::service::tests` keeps the coverage claim as a test, which is what a one-off
/// measurement has to become if it is going to keep being true.
pub fn screen_bg() -> Option<Color> {
    active_theme().map(|palette| palette.bg)
}

/// The three store states, role-first per §7.
///
/// **The declaration order is the severity order, and `Ord` says so.** A screen that rolls
/// several components up into one dot has to answer "which of these is worst", and deriving
/// that from the ordering keeps the answer in one place — see [`crate::health::SystemHealth::rollup`].
/// Without the ordering every caller writes its own `match`, and the third one disagrees.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum Health {
    Healthy,
    Degraded,
    Offline,
}

/// The one mark a RAG state is drawn with (Chris, 20260906: *"I've asked not to use other
/// symbol than the disc for the RAG."*).
///
/// §4 shipped a three-shape ladder — `● ▲ ○` — so that state survived a colourless terminal.
/// It cost something on every *other* terminal: three different marks in a column read as
/// three different kinds of thing, when they are one thing in three states. The hue already
/// says which, so the shape is spent on nothing.
pub const DISC: &str = "●";

impl Health {
    /// The mark for this state: [`DISC`] wherever the stream can carry a hue, and the old
    /// shape ladder where it cannot.
    ///
    /// The fallback is not a leftover — it is the whole reason the ladder was there. Under
    /// [`Family::None`] every [`Health::color`] resolves to `Color::Reset`, so one disc for
    /// all three states would say precisely nothing, and §3's *"structural signature first"*
    /// is the only channel left. See [`Health::shape`].
    pub fn glyph(self) -> &'static str {
        match family() {
            Family::None => self.shape(),
            _ => DISC,
        }
    }

    /// §4's original glyph table — the shape ladder, unconditionally.
    ///
    /// Kept and named rather than inlined into the fallback above because it is a claim about
    /// the *design*, not about a terminal: these are the three marks that carry Healthy,
    /// Degraded and Offline when nothing else can, and a caller that genuinely needs the
    /// distinction without asking the encoding should be able to say so out loud.
    pub const fn shape(self) -> &'static str {
        match self {
            Health::Healthy => "●",
            Health::Degraded => "▲",
            Health::Offline => "○",
        }
    }

    /// The hue for this state, or nothing where the encoding refuses colour — in which case
    /// [`Health::glyph`] is carrying the state on its own, as §4 always intended it could.
    pub fn color(self) -> Color {
        match self {
            Health::Healthy => healthy(),
            Health::Degraded => degraded(),
            Health::Offline => offline(),
        }
    }
}

/// Emphasis rungs as ready-made styles.
pub fn faint_style() -> Style {
    Style::default().fg(faint())
}
pub fn muted_style() -> Style {
    Style::default().fg(muted())
}
pub fn normal_style() -> Style {
    Style::default().fg(normal())
}
pub fn strong_style() -> Style {
    Style::default().fg(strong()).add_modifier(Modifier::BOLD)
}

/// The separator between one key hint and the next. Wide enough that a hint reads as one
/// unit rather than as a run of words.
const HINT_GAP: &str = "   ";

/// A row of `key label` hints: the key at the normal rung, what it does muted.
///
/// §5 puts the available action *"on the bottom key-hint line"*, and §6's modal draws the
/// same pair at the foot of its box. Two sites spelling the pair separately is how the two
/// drift, so the idiom lives here with the rest of the visual vocabulary and both call it.
/// Used by [`crate::widgets::chrome::StatusLine`] and `widgets::modal`.
pub fn key_hints<K: AsRef<str>, L: AsRef<str>>(hints: &[(K, L)]) -> Vec<Span<'static>> {
    let mut spans = Vec::with_capacity(hints.len() * 3);
    for (i, (key, label)) in hints.iter().enumerate() {
        if i > 0 {
            spans.push(Span::styled(HINT_GAP, muted_style()));
        }
        spans.push(Span::styled(key.as_ref().to_string(), normal_style()));
        spans.push(Span::styled(format!(" {}", label.as_ref()), muted_style()));
    }
    spans
}

/// The display width [`key_hints`] will occupy, for a caller that has to right-align it.
pub fn key_hints_width<K: AsRef<str>, L: AsRef<str>>(hints: &[(K, L)]) -> usize {
    key_hints(hints)
        .iter()
        .map(|span| span.content.chars().count())
        .sum()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Puts the globals back however the test ends, so a failure does not cascade into every
    /// later test as a wrong palette.
    struct Restore(Palette, Encoding);

    impl Restore {
        fn set(palette: Palette, encoding: Encoding) -> Self {
            let restore = Restore(Palette::current(), Encoding::current());
            Palette::set(palette);
            Encoding::set(encoding);
            restore
        }
    }

    impl Drop for Restore {
        fn drop(&mut self) {
            Palette::set(self.0);
            Encoding::set(self.1);
        }
    }

    /// A selected row is tinted toward the selection hue and stays legible: a WASH, not a fill.
    ///
    /// The two ends are what this pins. It must not be the background (nothing would show) and
    /// it must be far nearer the background than the hue itself (a full lavender row would put
    /// the theme's text on a colour nothing was tuned against). [`WASH_MIX`] is the same
    /// strength the condition wash was chosen at, and this is the guard that says so.
    #[test]
    fn a_selected_rows_fill_is_the_background_pulled_toward_the_selection_hue() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Bundled, Encoding::TrueColor);
        set_theme(ratatui_themes::ThemeName::CatppuccinMocha.palette());

        let fill = selected_bg().expect("RGB can express a wash");
        let background = neutral(0);
        assert_ne!(fill, background, "the wash is invisible");
        assert!(
            delta_e(fill, background) < delta_e(fill, selected()),
            "the fill is nearer the selection hue than the background — that is a fill, not a wash"
        );
    }

    /// Below RGB there is no wash at all, and the gutter bar carries the selection alone.
    ///
    /// The same rule the condition wash follows: a substitute fill would be chosen without
    /// knowing the theme's polarity, which is unreadable exactly where it matters.
    #[test]
    fn below_rgb_a_selection_has_no_wash_and_only_its_bar() {
        let _serial = crate::global_state_lock();
        for encoding in [Encoding::Ansi16, Encoding::Ansi256] {
            let _restore = Restore::set(Palette::Theme, encoding);
            assert_eq!(
                selected_bg(),
                None,
                "{encoding:?} cannot express a wash and must not invent one"
            );
        }
    }

    /// A selection is a highlight, so a modal takes it away with every other colour (VL §6).
    #[test]
    fn a_modal_takes_the_selection_hue_with_everything_else() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Bundled, Encoding::TrueColor);
        set_theme(ratatui_themes::ThemeName::CatppuccinMocha.palette());

        let live = selected();
        let under = {
            let _scope = modal::ModalScope::enter();
            selected()
        };
        assert_ne!(under, live, "the selection kept its hue under a modal");
        assert_eq!(under, muted(), "a quietened highlight is the muted rung");
    }

    #[test]
    fn a_rung_is_emitted_in_the_lesser_of_source_and_encoding() {
        let _serial = crate::global_state_lock();
        // The whole Source x Encoding rule, stated as a table so a change to either axis has
        // to come past it.
        let cases = [
            (Palette::Derived, Encoding::TrueColor, Family::Rgb),
            (Palette::Derived, Encoding::Ansi256, Family::Ramp),
            (Palette::Derived, Encoding::Ansi16, Family::Slots),
            (Palette::Derived, Encoding::NoColor, Family::None),
            (Palette::Derived, Encoding::NoTty, Family::None),
            // A capable encoding never promotes a source: asking for theme slots on a
            // truecolor terminal still gets theme slots.
            (Palette::Theme, Encoding::TrueColor, Family::Slots),
            (Palette::Indexed, Encoding::TrueColor, Family::Ramp),
            (Palette::Indexed, Encoding::Ansi16, Family::Slots),
        ];
        for (palette, encoding, expected) in cases {
            let _restore = Restore::set(palette, encoding);
            assert_eq!(family(), expected, "{palette:?} under {encoding:?}");
        }
    }

    #[test]
    fn degrading_picks_the_lower_ladder_rather_than_quantising_the_higher_one() {
        let _serial = crate::global_state_lock();
        // The measured rule from `crate::encoding`: per-rung quantisation of the tinted
        // ladder into the 256 palette collided `faint` and `rule_frame` on one index. Under
        // the ramp family each rung is recomputed from its own percentage, so the eleven
        // rungs that survive under `Indexed` survive here too.
        let ramp_rungs = |palette| {
            let _restore = Restore::set(palette, Encoding::Ansi256);
            [15u8, 19, 23, 30, 35, 50, 54, 62, 70].map(neutral_at)
        };
        assert_eq!(
            ramp_rungs(Palette::Derived),
            ramp_rungs(Palette::Indexed),
            "a degraded derived ladder must be the authored 256 ladder, not an approximation"
        );

        let _restore = Restore::set(Palette::Derived, Encoding::Ansi256);
        assert_ne!(
            neutral_at(50),
            neutral_at(54),
            "faint and rule_frame collided — the rejected per-rung quantisation is back"
        );
    }

    #[test]
    fn no_colour_leaves_shape_and_weight_carrying_the_state() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Derived, Encoding::NoColor);

        // Every hue and every neutral goes quiet...
        for colour in [
            selector(),
            selector_fg(),
            Health::Healthy.color(),
            Health::Degraded.color(),
            Health::Offline.color(),
            faint(),
            muted(),
            normal(),
            strong(),
            cursor_bg(),
            layer1_bg(),
        ] {
            assert_eq!(colour, Color::Reset, "a colour survived NoColor");
        }

        // ...but the two channels r02 reserves for exactly this case do not.
        assert!(strong_style().add_modifier.contains(Modifier::BOLD));
        assert!(
            inverted(selector())
                .add_modifier
                .contains(Modifier::REVERSED),
            "an inverted block must survive as reverse video or the selector vanishes"
        );
        assert_ne!(Health::Healthy.glyph(), Health::Offline.glyph());
    }

    /// Chris, 20260906: *"I've asked not to use other symbol than the disc for the RAG."*
    ///
    /// So where the stream can carry a hue, the hue is the entire signal and all three states
    /// are one disc. The shape ladder survives only under an encoding that refuses colour,
    /// where a single `●` would say nothing at all — which is the case the test below covers
    /// and the reason [`Health::shape`] still exists.
    #[test]
    fn the_rag_is_one_disc_wherever_colour_can_carry_the_state() {
        let _serial = crate::global_state_lock();

        for encoding in [Encoding::Ansi16, Encoding::Ansi256, Encoding::TrueColor] {
            let _restore = Restore::set(Palette::Bundled, encoding);
            for health in [Health::Healthy, Health::Degraded, Health::Offline] {
                assert_eq!(
                    health.glyph(),
                    DISC,
                    "{health:?} is not a disc under {}",
                    encoding.label()
                );
            }
            // The hue is doing the work, so the three must still differ from each other.
            assert_ne!(Health::Healthy.color(), Health::Offline.color());
        }
    }

    /// The fallback, and the only place three shapes are still drawn.
    #[test]
    fn an_encoding_that_refuses_colour_gets_the_shape_ladder_back() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Bundled, Encoding::NoColor);

        assert_eq!(Health::Healthy.glyph(), "●");
        assert_eq!(Health::Degraded.glyph(), "▲");
        assert_eq!(Health::Offline.glyph(), "○");
    }

    #[test]
    fn the_derived_baseline_is_the_foreground_it_was_given() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Derived, Encoding::TrueColor);
        let previous = endpoints();
        set_endpoints(Endpoints {
            background: Rgb::new(0x1e, 0x1e, 0x2e),
            foreground: Rgb::new(0xcd, 0xd6, 0xf4),
        });

        // NORMAL_RUNG exists so that the 85% rung lands exactly on the foreground endpoint.
        // If it drifts, every rung below it is compressed and nothing else notices.
        assert_eq!(normal(), Color::Rgb(0xcd, 0xd6, 0xf4));
        assert_eq!(neutral_at(0), Color::Rgb(0x1e, 0x1e, 0x2e));

        set_endpoints(previous);
    }

    /// Every bundled theme, so a claim about "the themes" is measured over all fifteen rather
    /// than over the one this crate was authored against.
    fn each_theme() -> impl Iterator<Item = (&'static str, ThemePalette)> {
        ratatui_themes::ThemeName::all()
            .iter()
            .map(|name| (name.display_name(), name.palette()))
    }

    /// How close a colour comes to the nearest of the three health hues — the number that
    /// decides whether a field can carry the reserved selector.
    fn nearest_health(colour: Color, palette: &ThemePalette) -> f32 {
        [palette.success, palette.warning, palette.error]
            .iter()
            .map(|hue| delta_e(colour, *hue))
            .fold(f32::MAX, f32::min)
    }

    struct WithTheme(Option<ThemePalette>);

    impl WithTheme {
        fn set(palette: ThemePalette) -> Self {
            let restore = WithTheme(theme());
            set_theme(palette);
            restore
        }
    }

    impl Drop for WithTheme {
        fn drop(&mut self) {
            *THEME.write().expect("theme lock") = self.0;
        }
    }

    #[test]
    fn a_bundled_ladder_is_interpolated_from_the_theme_not_the_terminal() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Bundled, Encoding::TrueColor);
        let previous = endpoints();
        // Deliberately nothing like any theme: if a rung came from here rather than from the
        // theme, it says so in the assertion instead of coincidentally agreeing.
        set_endpoints(Endpoints {
            background: Rgb::new(0, 0, 0),
            foreground: Rgb::new(255, 255, 255),
        });

        for (label, palette) in each_theme() {
            let _theme = WithTheme::set(palette);
            assert_eq!(
                neutral_at(0),
                palette.bg,
                "{label}: 0% is the theme's own bg"
            );
            assert_eq!(
                normal(),
                palette.fg,
                "{label}: the baseline is the theme's own fg"
            );
        }

        set_endpoints(previous);
    }

    #[test]
    fn a_bundled_role_is_the_themes_semantic_field_not_an_ansi_slot() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Bundled, Encoding::TrueColor);

        for (label, palette) in each_theme() {
            let _theme = WithTheme::set(palette);
            assert_eq!(Health::Healthy.color(), palette.success, "{label}");
            assert_eq!(Health::Degraded.color(), palette.warning, "{label}");
            assert_eq!(Health::Offline.color(), palette.error, "{label}");
            assert_eq!(selector(), palette.info, "{label}");
        }
    }

    #[test]
    fn the_selector_is_info_because_it_keeps_the_most_distance_from_the_health_hues() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Bundled, Encoding::TrueColor);

        // §15 left this field to us: `accent` or `info`. §3 reserves the selector ABSOLUTELY
        // — "if it is a cyan block, it is what you have selected" — so the field that carries
        // it is the one that stays furthest from the three health hues in the WORST theme,
        // not on average and not in the theme this crate happens to be authored against.
        //
        // Measured over all fifteen, as CIE76 ΔE to the nearest health hue:
        //
        //   worst `info`   — Catppuccin Mocha, 27.9
        //   worst `accent` — Everforest,       14.7   (then Gruvbox 28.7, Rosé Pine 35.4)
        //
        // So `accent` does not *collide* anywhere; it simply comes twice as close, and a
        // reserved hue is defended at its worst case. That is the entire argument, and this
        // test is it — if a future theme set moves the two worst cases together, the choice
        // was arbitrary and belongs back in front of Chris rather than in a comment.
        let (mut worst_info, mut worst_accent) = (f32::MAX, f32::MAX);
        let mut worst_theme = "";

        for (label, palette) in each_theme() {
            let _theme = WithTheme::set(palette);
            let info = nearest_health(selector(), &palette);
            assert_eq!(selector(), palette.info, "{label}");
            if info < worst_info {
                worst_info = info;
                worst_theme = label;
            }
            worst_accent = worst_accent.min(nearest_health(palette.accent, &palette));
        }

        // A full-field hue and a glyph-sized one at ΔE 15 are the same colour at a glance,
        // which is the failure §4 exists to forbid.
        assert!(
            worst_info > 20.0,
            "{worst_theme}: the selector comes within ΔE {worst_info:.1} of a health hue"
        );
        assert!(
            worst_info > worst_accent * 1.5,
            "`info` no longer keeps meaningfully more distance than `accent` \
             (worst case ΔE {worst_info:.1} vs {worst_accent:.1}) — re-open the choice"
        );
    }

    #[test]
    fn the_bundled_wash_pulls_the_themes_own_background_toward_its_own_error() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Bundled, Encoding::TrueColor);

        // §15 item 4: the wash mixes toward the theme's `error`, not toward pure red, and
        // WASH_MIX 0.14 was chosen so that move lands where 0.10 toward pure red did.
        // Re-measured here across all fifteen themes rather than asserted from that note.
        let mut band = (f32::MAX, f32::MIN);
        for (label, palette) in each_theme() {
            let _theme = WithTheme::set(palette);
            let base = screen_bg().expect("a bundled screen paints its own base");
            let washed = wash(Condition::DaemonUnreachable).expect("RGB can express a wash");
            assert_eq!(base, palette.bg, "{label}");

            // Toward the theme's error, which is the direction; the distance is the strength.
            let moved = delta_e(base, washed);
            band = (band.0.min(moved), band.1.max(moved));
            assert!(
                delta_e(washed, palette.error) < delta_e(base, palette.error),
                "{label}: the wash must move TOWARD the theme's error"
            );
        }

        // Measured across the fifteen: **ΔE 7.2 (Nord) to 18.5 (Cyberpunk)**, against 12.4–19.7
        // for the same constant mixed toward pure red. §15 predicted that softening — the
        // theme's error is a shorter move from the theme's own background than pure red is —
        // and 0.14 was chosen so the softened move lands where 0.10 toward pure red did.
        //
        // The band is a guard on the constant, not a fit to the data: below ΔE 5 a full-screen
        // tint stops being noticed at all, and above 25 it reads as a red screen rather than a
        // red-tinted one (the rejected first cut, 0.22 toward pure red, sat there).
        //
        // ⚠ Nord and Solarized Dark come in at 7.2 and 7.7 — just under the ΔE 8–10 Chris
        // called right. Recorded rather than corrected: WASH_MIX is his number and is
        // deliberately not a knob.
        assert!(
            band.0 >= 5.0 && band.1 <= 25.0,
            "the wash left its band across the bundled themes: ΔE {:.1}–{:.1}",
            band.0,
            band.1
        );
    }

    #[test]
    fn only_a_bundled_screen_paints_its_own_layer_zero() {
        let _serial = crate::global_state_lock();
        let _theme = WithTheme::set(ratatui_themes::ThemeName::CatppuccinMocha.palette());

        {
            let _restore = Restore::set(Palette::Bundled, Encoding::TrueColor);
            assert_eq!(
                screen_bg(),
                Some(ratatui_themes::ThemeName::CatppuccinMocha.palette().bg),
                "§15: the theme owns the background, and it is the FIRST anchor — the probe \
                 that deliberately painted `selection` has done its job"
            );
        }

        // Every other source keeps r02 §6's rule: layer 0 is the terminal's own and is never
        // repainted. A theme being *available* is not a decision to paint with it.
        for palette in [Palette::Theme, Palette::Indexed, Palette::Derived] {
            let _restore = Restore::set(palette, Encoding::TrueColor);
            assert_eq!(screen_bg(), None, "{palette:?} repainted layer 0");
        }
    }

    #[test]
    fn a_bundled_palette_with_no_theme_chosen_falls_back_rather_than_failing() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Bundled, Encoding::TrueColor);
        let _theme = WithTheme(theme());
        *THEME.write().expect("theme lock") = None;

        let previous = endpoints();
        set_endpoints(Endpoints {
            background: Rgb::new(0x1e, 0x1e, 0x2e),
            foreground: Rgb::new(0xcd, 0xd6, 0xf4),
        });

        // With no theme there is nothing to source from, so the ladder is the terminal's —
        // which is exactly `Derived`. The default palette is `Bundled`, so this path is what
        // every caller that never chooses a theme gets, and it must be a working screen.
        assert_eq!(neutral_at(0), Color::Rgb(0x1e, 0x1e, 0x2e));
        assert_eq!(normal(), Color::Rgb(0xcd, 0xd6, 0xf4));
        assert_eq!(
            screen_bg(),
            None,
            "nothing to paint with, so nothing painted"
        );
        assert_eq!(Health::Offline.color(), Color::Red, "back to the slot hue");

        set_endpoints(previous);
    }
}
