//! Design tokens for the wqm TUI, transcribed from VISUAL-LANGUAGE.md r02.
//!
//! This module is the SSOT for the storyboard's neutrals and reserved hues. Widgets never
//! spell a colour literal — they name a rung on the emphasis ladder or a highlight role,
//! so a change here propagates to every frame and to the pantry's Styles tab.
//!
//! # Everything resolves through the terminal's palette
//!
//! No token emits absolute RGB. Every colour is an ANSI slot or a 256-table index, so the
//! user's theme decides what is actually painted — a wqm screen sits inside the terminal
//! the user configured rather than overriding it.
//!
//! That commitment costs something, and [`Palette`] is where the cost is made explicit.
//! Hues (selector, health) are always the 16 theme slots: those are exactly the colours a
//! theme redefines, so honouring the theme is both possible and correct. Neutrals are the
//! problem — r02 asks for eleven distinguishable greys (four emphasis rungs, two
//! structural rules, a header, two highlight fills, two layer backgrounds) and the 16-slot
//! palette contains **four** (black, bright-black, white, bright-white). The three modes
//! are the three honest answers to that shortfall; see each variant.
//!
//! # Two measured defects the modes answer to
//!
//! Both were found against ghostty running Catppuccin Mocha (`background = #1e1e2e`,
//! `foreground = #cdd6f4`), and both are properties of the design, not of that theme:
//!
//! 1. **[`Palette::Theme`] collapses roles.** Three pairs r02 insists must never share a
//!    treatment emit byte-identical SGR: cursor-mark/muted both `37`, faint/rule-internal
//!    both `90`, cursor-fill/layer-1 both `40`. Worse, that shared fill is slot 0, so on a
//!    black terminal the data cursor paints the background and the row vanishes — the
//!    exact failure §3 exists to prevent.
//! 2. **[`Palette::Indexed`]'s neutrals are neutral in a room where nothing else is.** A
//!    theme redefines only slots 0–15, so the 232–255 ramp stays true grey. Against a
//!    blue-violet field, simultaneous contrast makes true grey read as its opponent —
//!    yellow (Chris, 20260730). The ramp is not tinted; it is the only untinted thing on
//!    screen. Independently, r02's dark rungs assume a near-black background: `neutral(15)`
//!    resolves to `#262626`, which is *darker in blue* than Mocha's own background, so the
//!    layer fills and the cursor tint sink into the base rather than floating above it.
//!
//! [`Palette::Derived`] answers both, at the price named on the variant.
//!
//! # A palette is a preference; what the terminal can emit is not
//!
//! [`Palette`] is only half the question. It says where a colour comes *from*; it cannot say
//! whether the stream can carry it. That second axis lives in [`crate::encoding`], is probed
//! rather than chosen, and caps this one: every token below resolves through [`family()`],
//! which is the lesser of the two. So `Derived` on a 16-colour login shell renders the
//! authored 16-colour ladder — not an approximation of the derived one.

use std::sync::RwLock;
use std::sync::atomic::{AtomicU8, Ordering};

use ratatui::style::{Color, Modifier, Style};

use crate::encoding::{Encoding, Family};
use crate::terminal::{Endpoints, Rgb};

/// How neutrals are sourced. Hues are unaffected — they are always theme slots.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Palette {
    /// Only the 16 theme slots. Maximally theme-adaptive: a user who restyles their
    /// terminal restyles wqm with it, greys included. The cost is collapse — eleven
    /// specified neutrals map onto four available slots, so the emphasis ladder loses
    /// rungs and several roles that r02 separates end up sharing a colour.
    Theme,
    /// Theme slots for hues, the xterm 256-table greyscale ramp (indices 232–255) for
    /// neutrals. Still terminal-resolved indices rather than absolute RGB, and still
    /// downgrades cleanly, but the ramp is standard rather than theme-defined — so the
    /// eleven rungs survive at the price of greys that do not follow the user's theme.
    Indexed,
    /// Neutrals generated by interpolating between the terminal's *own* background and
    /// foreground, which [`crate::terminal`] asks it for.
    ///
    /// This is the only mode that answers both defects above: the endpoints carry the
    /// theme's hue, so every rung inherits it and none reads as yellow; and anchoring 0%
    /// at the real background guarantees each rung is ordered above the base rather than
    /// sinking into it.
    ///
    /// It costs the module's opening promise: these tokens **do** emit absolute RGB. The
    /// mitigation is that the values are read off the user's terminal rather than chosen
    /// here, which is arguably a stronger form of honouring a theme than picking slots
    /// from it. It also costs r02's percentages their absolute meaning — under this mode a
    /// rung is a position on the terminal's contrast range, not a byte value. Needs
    /// truecolor and a terminal that answers `OSC 11`/`OSC 10`; without both, falls back
    /// to [`ENDPOINT_FALLBACK`].
    Derived,
}

/// What [`Palette::Derived`] interpolates between when the terminal was never asked, or
/// declined to answer.
///
/// Black to white: the assumption r02 was authored under, so the fallback reproduces the
/// authored ladder rather than inventing a third one.
pub const ENDPOINT_FALLBACK: Endpoints = Endpoints {
    background: Rgb::new(0, 0, 0),
    foreground: Rgb::new(255, 255, 255),
};

/// The rung the terminal's foreground *is*.
///
/// r02 puts `normal` at grey85 and [`normal()`] renders it as `Color::Reset` — the
/// terminal's own foreground. So under [`Palette::Derived`] the foreground endpoint is the
/// 85% rung, not the 100% one, and anchoring it at 100% compresses the whole ladder
/// downward. Measured on Catppuccin Mocha, that compression cost `faint` 5, `muted` 13 and
/// `cursor_mark` 20 luma against the [`Palette::Indexed`] ramp — the gap Chris saw as "not
/// as good as Indexed" (20260730). Anchoring here restores it and lets `strong` extrapolate
/// *past* the foreground, which is what a rung above the baseline has to do.
const NORMAL_RUNG: u8 = 85;

static ENDPOINTS: RwLock<Endpoints> = RwLock::new(ENDPOINT_FALLBACK);

/// Installs the endpoints [`Palette::Derived`] interpolates between.
///
/// Call once at startup, before a TUI takes the terminal — see
/// [`crate::terminal::detect`]. Rendering never queries, so a frame costs no round trip.
pub fn set_endpoints(endpoints: Endpoints) {
    if let Ok(mut slot) = ENDPOINTS.write() {
        *slot = endpoints;
    }
}

/// The endpoints currently in force.
pub fn endpoints() -> Endpoints {
    ENDPOINTS.read().map(|e| *e).unwrap_or(ENDPOINT_FALLBACK)
}

static ACTIVE: AtomicU8 = AtomicU8::new(Palette::Theme as u8);

impl Palette {
    /// The palette every token currently resolves against.
    pub fn current() -> Palette {
        match ACTIVE.load(Ordering::Relaxed) {
            0 => Palette::Theme,
            1 => Palette::Indexed,
            _ => Palette::Derived,
        }
    }

    /// Every mode, in the order the sheet compares them.
    pub const ALL: [Palette; 3] = [Palette::Theme, Palette::Indexed, Palette::Derived];

    /// The name this mode is spelled with in the pantry and in VISUAL-LANGUAGE.md.
    pub const fn label(self) -> &'static str {
        match self {
            Palette::Theme => "Theme",
            Palette::Indexed => "Indexed",
            Palette::Derived => "Derived",
        }
    }

    /// Switch palettes. Lets one pantry render both modes so the trade-off is judged from
    /// a pair of frames rather than from an argument.
    pub fn set(palette: Palette) {
        ACTIVE.store(palette as u8, Ordering::Relaxed);
    }

    /// The family this source *wants* to be emitted in. What it actually gets is
    /// [`family()`], which is this capped by the encoding.
    pub const fn family(self) -> Family {
        match self {
            Palette::Theme => Family::Slots,
            Palette::Indexed => Family::Ramp,
            Palette::Derived => Family::Rgb,
        }
    }
}

/// How every token below is emitted: **the lesser of what the source wants and what the
/// encoding permits**.
///
/// This one comparison is the whole Source × Encoding split. A preference cannot exceed a
/// capability, and a capability never dictates a preference below it — asking for
/// [`Palette::Theme`] on a truecolor terminal still gets theme slots, because slots are what
/// was asked for.
///
/// Degradation drops to the next family's **own** ladder rather than approximating the one
/// above it; [`crate::encoding`] carries the measurement that forced that rule.
pub fn family() -> Family {
    Palette::current()
        .family()
        .min(Encoding::current().family())
}

/// A reserved hue, or nothing if the encoding refuses colour.
///
/// The design anticipates this: r02 §3 asks for a structural signature first with colour
/// reserved, and [`Health::glyph`] already carries state as shape. So dropping the hue costs
/// emphasis, not information.
fn hue(color: Color) -> Color {
    match family() {
        Family::None => Color::Reset,
        _ => color,
    }
}

/// A neutral, named by the luminance percentage r02 specifies for it.
///
/// The percentage is the authored value; [`family()`] decides which ladder it is read off.
/// [`Family::Ramp`] picks the nearest step on the xterm greyscale ramp, whose steps run
/// 8, 18, … 238 at indices 232–255; [`Family::Slots`] collapses onto the nearest of the four
/// available slots; [`Family::None`] emits nothing, leaving the cell to whatever the terminal
/// is already painting.
///
/// Note what this does *not* do: it never converts one family's answer into another's. A
/// rung is always computed from its percentage, so degrading is choosing a different ladder
/// rather than approximating the one above — see [`crate::encoding`] for the measurement.
fn neutral(percent: u8) -> Color {
    match family() {
        Family::None => Color::Reset,
        Family::Slots => match percent {
            0..=24 => Color::Black,
            25..=55 => Color::DarkGray,
            56..=92 => Color::Gray,
            _ => Color::White,
        },
        Family::Ramp => {
            let target = percent as u16 * 255 / 100;
            match target {
                // Below the ramp's first step and above its last, the cube's true black
                // and true white are the closer answers.
                0..=7 => Color::Indexed(16),
                243..=255 => Color::Indexed(231),
                _ => {
                    let step = ((target - 8) as f32 / 10.0).round() as u16;
                    Color::Indexed(232 + step.min(23) as u8)
                }
            }
        }
        Family::Rgb => {
            let Endpoints {
                background,
                foreground,
            } = endpoints();
            let t = percent.min(100) as f32 / NORMAL_RUNG as f32;
            Color::Rgb(
                mix(background.r, foreground.r, t),
                mix(background.g, foreground.g, t),
                mix(background.b, foreground.b, t),
            )
        }
    }
}

/// One channel of the derived ladder.
///
/// Interpolated in sRGB byte space rather than in linear light, because r02's rung names
/// are byte values — its `grey19` means byte 48, which is what [`Palette::Indexed`] also
/// resolves it to. Interpolating in linear light would honour the *percentages* as
/// luminance and lift the dark rungs far off the base: measured on Catppuccin Mocha it put
/// `layer1_bg` at `#5a5e6f`, a mid-grey, where §6 asks for "dark but distinctly above the
/// base". Byte-space keeps the authored spacing and only re-anchors its ends.
fn mix(from: u8, to: u8, t: f32) -> u8 {
    (from as f32 + (to as f32 - from as f32) * t)
        .round()
        .clamp(0.0, 255.0) as u8
}

/// One rung of the ladder, by the luminance percentage r02 names it with.
///
/// The named tokens below are how widgets should reach a rung — `faint()` says why the
/// colour was chosen, `neutral_at(50)` does not. This exists for the reference sheet, which
/// has the opposite job: enumerating the ladder as a ladder, including the rungs no token
/// is named after.
pub fn neutral_at(percent: u8) -> Color {
    neutral(percent)
}

// --- §2 emphasis ladder -------------------------------------------------------------
// Default posture: most of the screen is muted or faint. Normal is the zone you are in;
// strong is the few things that matter.

/// De-emphasised metadata that must still be legible (default-column values).
pub fn faint() -> Color {
    neutral(50)
}
/// Inactive tabs, unfocused zone bodies, timestamps, paths, key hints.
pub fn muted() -> Color {
    neutral(62)
}
/// Body text of the focused zone; the baseline.
///
/// This rung is the terminal's own foreground in every mode. The baseline is precisely the
/// text that should look like everything else the user reads in that window.
///
/// # Under `Derived` it says so explicitly, and that is not a change of intent
///
/// `Color::Reset` asks the terminal for its foreground. [`Palette::Derived`] has already
/// *been told* the foreground — that is what [`crate::terminal::detect`] read — and
/// [`NORMAL_RUNG`] is defined so that `neutral(NORMAL_RUNG)` interpolates to exactly that
/// endpoint. So the two are the same colour by construction, and emitting it directly only
/// makes this rung consistent with the other ten, which are already baked RGB.
///
/// It buys a real property: a renderer with no terminal to ask cannot resolve `Reset`, and
/// invents something instead. `soft_ratatui` resolves a `Reset` foreground to a fixed
/// `#ccccff` — near enough to be invisible against a dark theme and badly wrong against a
/// light one — so before this, [`crate::capture`] produced frames whose baseline text was
/// the one rung not derived from the theme. Under the slot-sourced palettes there is
/// nothing better to reach for, so they keep `Reset`.
pub fn normal() -> Color {
    match family() {
        Family::Rgb => neutral(NORMAL_RUNG),
        _ => Color::Reset,
    }
}
/// Primary figures, and any value that differs from its default. Weight does the work;
/// the colour only stops it receding.
///
/// # The slot-based answer is measurably wrong
///
/// Under the two slot-sourced palettes this is `Color::White` — ANSI slot 15 — because
/// there is nothing brighter available. But a theme is free to place slot 15 *below* its
/// foreground, and Catppuccin Mocha does exactly that: slot 15 is `#bac2de` (luma 194)
/// against a foreground of `#cdd6f4` (luma 214), so the ladder's loudest rung renders 20
/// luma **darker** than its baseline and only the bold modifier hides it.
///
/// [`Palette::Derived`] can do better, because it is not picking from a fixed set: it
/// extrapolates past the foreground and gets a rung that is genuinely above `normal`.
pub fn strong() -> Color {
    match family() {
        Family::Rgb => neutral(100),
        // Nothing brighter than slot 15 exists to reach for, and under `None` the bold
        // modifier in `strong_style` is the entire signal — which r02 says it mostly is
        // anyway ("weight does the work").
        Family::None => Color::Reset,
        _ => Color::White,
    }
}

// --- §2 / §6 structure --------------------------------------------------------------

/// Top and bottom frame rules — lighter, because they underline the screen.
pub fn rule_frame() -> Color {
    neutral(54)
}
/// Internal zone separators — darker, because they divide within.
pub fn rule_internal() -> Color {
    neutral(30)
}
/// Column headers are CAPS at this depth: structure, not data.
pub fn header() -> Color {
    neutral(62)
}

// --- §3 highlight roles -------------------------------------------------------------

/// The reserved selector hue. Cyan appears in NOTHING else: if it is a cyan block, it is
/// what you have selected. A theme slot, so a user who has retuned cyan retunes the
/// selector with it.
pub fn selector() -> Color {
    hue(Color::Cyan)
}
/// Text sitting inside an inverted selector block.
pub fn selector_fg() -> Color {
    hue(Color::Black)
}

/// An inverted highlight block — a hue fill with dark text on it.
///
/// Where the encoding refuses colour, this becomes reverse video, which is what an inverted
/// block structurally *is*: the selector survives as a swapped foreground and background
/// rather than disappearing. Without it, `fill` and the text on it both resolve to
/// `Color::Reset` and a selected row becomes indistinguishable from an unselected one —
/// which is the same class of failure as [`Palette::Theme`]'s invisible cursor row.
pub fn inverted(fill: Color) -> Style {
    match family() {
        Family::None => Style::default().add_modifier(Modifier::REVERSED),
        _ => Style::default().fg(selector_fg()).bg(fill),
    }
}
/// The data cursor's row tint — a subtle darker fill, deliberately not an inverse block.
pub fn cursor_bg() -> Color {
    neutral(19)
}
/// The leading `▸` marker on the data cursor row.
pub fn cursor_mark() -> Color {
    neutral(70)
}
/// The editing cell fill — lighter than the cursor tint, so it reads as "you type HERE".
pub fn edit_bg() -> Color {
    neutral(35)
}

// --- §4 health ----------------------------------------------------------------------
// Only the glyph carries colour; the surrounding label stays muted.

pub fn healthy() -> Color {
    hue(Color::Green)
}
pub fn degraded() -> Color {
    hue(Color::Yellow)
}
pub fn offline() -> Color {
    hue(Color::Red)
}

// --- §6 layers, and the one condition that repaints layer 0 --------------------------

/// A screen-wide condition — the state of the *system*, not of a widget.
///
/// Chris, 20260731: **when the daemon is unreachable the whole TUI carries a red wash, on
/// every tab, until it comes back.** That is a sustained condition, and it is exactly what a
/// toast cannot express: a toast announces a transition and then expires, while "nothing you
/// see is live" has to stay said for as long as it is true. The two are complementary — the
/// transition toasts, the condition washes.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Condition {
    Nominal,
    /// The liveness master is not answering (VISUAL-LANGUAGE §7). Every reading on screen is
    /// stale by definition, which is why this is a whole-screen signal rather than one zone's.
    DaemonUnreachable,
}

static CONDITION: AtomicU8 = AtomicU8::new(Condition::Nominal as u8);

impl Condition {
    pub fn current() -> Condition {
        match CONDITION.load(Ordering::Relaxed) {
            0 => Condition::Nominal,
            _ => Condition::DaemonUnreachable,
        }
    }

    pub fn set(condition: Condition) {
        CONDITION.store(condition as u8, Ordering::Relaxed);
    }
}

/// How far the wash pulls the terminal's own background toward red.
///
/// **Subtle, deliberately** (Chris, 20260731: *"it should be subtle as not destroy visibility
/// across the window"*). The wash sits behind every glyph on screen, and the text under it is
/// exactly the text the user needs in order to see what broke — so the tint's job is to be
/// noticed peripherally, not to be looked at. The first cut was 0.22, which read as a red
/// screen rather than a red-tinted one.
///
/// Judge it, do not argue it: `cargo pantry dump "Surface" --variant "Wash Strengths"` puts
/// the candidates side by side with real text on them.
///
/// # Why 0.14 and not the 0.10 that looked right
///
/// Chris chose it *"to be consistent for both"* (20260731) — for the wash as it is today and
/// for the wash after `OSC 4`. Today the tint is mixed toward **pure** red; once the terminal's
/// own sixteen slots can be queried it mixes toward the **theme's** red, which is a gentler
/// move from the same background. Measured as CIE76 distance from the base:
///
/// | | 0.10 | 0.14 |
/// |---|---|---|
/// | toward pure red (today) | ΔE 11–14 | ΔE 16–19 |
/// | toward the theme's red (after `OSC 4`) | ΔE 8–10 | **ΔE 11–14** |
///
/// So 0.14 after `OSC 4` is what 0.10 is now, and the constant does not move when that decision
/// lands. The cost is paid in the interim: until then the wash is one step louder than the
/// value that was called perfect.
pub const WASH_MIX: f32 = 0.14;

/// Layer 0's background: [`None`] normally — §6 says a full screen keeps the terminal's own
/// and is never repainted — and the wash while the daemon is unreachable.
///
/// **The wash answers "dark or light red?" with "whichever the user's terminal is."** It is
/// the terminal's *own* background pulled toward red by [`WASH_MIX`], so a dark theme gets a
/// dark red and a light theme a light one, and the polarity the user chose is preserved
/// rather than overridden.
///
/// # It needs RGB, and below that the wash is not attempted
///
/// Only [`Family::Rgb`] can express "this background, but redder". The slot and ramp families
/// would have to substitute a *fixed* red — ANSI red as a full-screen fill is unreadable, and
/// an indexed dark red assumes a polarity those families cannot know. So below RGB this
/// returns [`None`] and the structural marker carries the condition alone, which is r02 §3's
/// own rule: structure first, colour reserved. `crate::widgets::surface` draws both.
pub fn layer0_bg() -> Option<Color> {
    wash(Condition::current())
}

/// [`layer0_bg`] for a *stated* condition rather than the process-global one.
///
/// A frame has to be able to render the unreachable screen without the process being in that
/// state — the pantry does exactly this, and so does a capture. The global exists so a widget
/// deep in a render tree can ask without being handed a context; every renderer that takes a
/// condition as a parameter must reach the token through this, or it renders one condition
/// while asking about another. That failure is not hypothetical: it is what the surface tests
/// caught the first time this was wired, and it is the same shape as the two-globals rule
/// already recorded for `Palette` and `Encoding`.
pub fn wash(condition: Condition) -> Option<Color> {
    wash_at(condition, WASH_MIX)
}

/// [`wash`] at a stated strength, so candidate values can be put side by side in one frame
/// rather than compared across two runs of the same binary.
///
/// The comparison is the point: "subtle" is not a number anyone can argue their way to, and a
/// tint judged alone always looks reasonable.
pub fn wash_at(condition: Condition, mix_toward_red: f32) -> Option<Color> {
    match (condition, family()) {
        (Condition::Nominal, _) => None,
        (Condition::DaemonUnreachable, Family::Rgb) => {
            let bg = endpoints().background;
            let strength = mix_toward_red.clamp(0.0, 1.0);
            Some(Color::Rgb(
                mix(bg.r, 255, strength),
                mix(bg.g, 0, strength),
                mix(bg.b, 0, strength),
            ))
        }
        (Condition::DaemonUnreachable, _) => None,
    }
}

/// Layer 1 — a modal over a full screen: dark, but distinctly above the base.
pub fn layer1_bg() -> Color {
    neutral(15)
}
/// Layer 2 — a modal over a modal: distinct and lighter, so the stack stays legible.
pub fn layer2_bg() -> Color {
    neutral(23)
}

/// The three store states, role-first per §7.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Health {
    Healthy,
    Degraded,
    Offline,
}

impl Health {
    /// §4 glyph table. Shape carries the state as well as hue, so the encoding survives
    /// `NO_COLOR` and the low colour depths (UX-06).
    pub const fn glyph(self) -> &'static str {
        match self {
            Health::Healthy => "●",
            Health::Degraded => "▲",
            Health::Offline => "○",
        }
    }

    /// The hue for this state, or nothing where the encoding refuses colour — in which case
    /// [`Health::glyph`] is carrying the state on its own, as §4 always intended it could.
    pub fn color(self) -> Color {
        match self {
            Health::Healthy => healthy(),
            Health::Degraded => degraded(),
            Health::Offline => offline(),
        }
    }
}

/// Emphasis rungs as ready-made styles.
pub fn faint_style() -> Style {
    Style::default().fg(faint())
}
pub fn muted_style() -> Style {
    Style::default().fg(muted())
}
pub fn normal_style() -> Style {
    Style::default().fg(normal())
}
pub fn strong_style() -> Style {
    Style::default().fg(strong()).add_modifier(Modifier::BOLD)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Puts the globals back however the test ends, so a failure does not cascade into every
    /// later test as a wrong palette.
    struct Restore(Palette, Encoding);

    impl Restore {
        fn set(palette: Palette, encoding: Encoding) -> Self {
            let restore = Restore(Palette::current(), Encoding::current());
            Palette::set(palette);
            Encoding::set(encoding);
            restore
        }
    }

    impl Drop for Restore {
        fn drop(&mut self) {
            Palette::set(self.0);
            Encoding::set(self.1);
        }
    }

    #[test]
    fn a_rung_is_emitted_in_the_lesser_of_source_and_encoding() {
        let _serial = crate::global_state_lock();
        // The whole Source x Encoding rule, stated as a table so a change to either axis has
        // to come past it.
        let cases = [
            (Palette::Derived, Encoding::TrueColor, Family::Rgb),
            (Palette::Derived, Encoding::Ansi256, Family::Ramp),
            (Palette::Derived, Encoding::Ansi16, Family::Slots),
            (Palette::Derived, Encoding::NoColor, Family::None),
            (Palette::Derived, Encoding::NoTty, Family::None),
            // A capable encoding never promotes a source: asking for theme slots on a
            // truecolor terminal still gets theme slots.
            (Palette::Theme, Encoding::TrueColor, Family::Slots),
            (Palette::Indexed, Encoding::TrueColor, Family::Ramp),
            (Palette::Indexed, Encoding::Ansi16, Family::Slots),
        ];
        for (palette, encoding, expected) in cases {
            let _restore = Restore::set(palette, encoding);
            assert_eq!(family(), expected, "{palette:?} under {encoding:?}");
        }
    }

    #[test]
    fn degrading_picks_the_lower_ladder_rather_than_quantising_the_higher_one() {
        let _serial = crate::global_state_lock();
        // The measured rule from `crate::encoding`: per-rung quantisation of the tinted
        // ladder into the 256 palette collided `faint` and `rule_frame` on one index. Under
        // the ramp family each rung is recomputed from its own percentage, so the eleven
        // rungs that survive under `Indexed` survive here too.
        let ramp_rungs = |palette| {
            let _restore = Restore::set(palette, Encoding::Ansi256);
            [15u8, 19, 23, 30, 35, 50, 54, 62, 70].map(neutral_at)
        };
        assert_eq!(
            ramp_rungs(Palette::Derived),
            ramp_rungs(Palette::Indexed),
            "a degraded derived ladder must be the authored 256 ladder, not an approximation"
        );

        let _restore = Restore::set(Palette::Derived, Encoding::Ansi256);
        assert_ne!(
            neutral_at(50),
            neutral_at(54),
            "faint and rule_frame collided — the rejected per-rung quantisation is back"
        );
    }

    #[test]
    fn no_colour_leaves_shape_and_weight_carrying_the_state() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Derived, Encoding::NoColor);

        // Every hue and every neutral goes quiet...
        for colour in [
            selector(),
            selector_fg(),
            Health::Healthy.color(),
            Health::Degraded.color(),
            Health::Offline.color(),
            faint(),
            muted(),
            normal(),
            strong(),
            cursor_bg(),
            layer1_bg(),
        ] {
            assert_eq!(colour, Color::Reset, "a colour survived NoColor");
        }

        // ...but the two channels r02 reserves for exactly this case do not.
        assert!(strong_style().add_modifier.contains(Modifier::BOLD));
        assert!(
            inverted(selector())
                .add_modifier
                .contains(Modifier::REVERSED),
            "an inverted block must survive as reverse video or the selector vanishes"
        );
        assert_ne!(Health::Healthy.glyph(), Health::Offline.glyph());
    }

    #[test]
    fn the_derived_baseline_is_the_foreground_it_was_given() {
        let _serial = crate::global_state_lock();
        let _restore = Restore::set(Palette::Derived, Encoding::TrueColor);
        let previous = endpoints();
        set_endpoints(Endpoints {
            background: Rgb::new(0x1e, 0x1e, 0x2e),
            foreground: Rgb::new(0xcd, 0xd6, 0xf4),
        });

        // NORMAL_RUNG exists so that the 85% rung lands exactly on the foreground endpoint.
        // If it drifts, every rung below it is compressed and nothing else notices.
        assert_eq!(normal(), Color::Rgb(0xcd, 0xd6, 0xf4));
        assert_eq!(neutral_at(0), Color::Rgb(0x1e, 0x1e, 0x2e));

        set_endpoints(previous);
    }
}
