//! Design tokens for the wqm TUI, transcribed from VISUAL-LANGUAGE.md r02.
//!
//! This module is the SSOT for the storyboard's neutrals and reserved hues. Widgets never
//! spell a colour literal — they name a rung on the emphasis ladder or a highlight role,
//! so a change here propagates to every frame and to the pantry's Styles tab.
//!
//! # Everything resolves through the terminal's palette
//!
//! No token emits absolute RGB. Every colour is an ANSI slot or a 256-table index, so the
//! user's theme decides what is actually painted — a wqm screen sits inside the terminal
//! the user configured rather than overriding it.
//!
//! That commitment costs something, and [`Palette`] is where the cost is made explicit.
//! Hues (selector, health) are always the 16 theme slots: those are exactly the colours a
//! theme redefines, so honouring the theme is both possible and correct. Neutrals are the
//! problem — r02 asks for eleven distinguishable greys (four emphasis rungs, two
//! structural rules, a header, two highlight fills, two layer backgrounds) and the 16-slot
//! palette contains **four** (black, bright-black, white, bright-white). The three modes
//! are the three honest answers to that shortfall; see each variant.
//!
//! # Two measured defects the modes answer to
//!
//! Both were found against ghostty running Catppuccin Mocha (`background = #1e1e2e`,
//! `foreground = #cdd6f4`), and both are properties of the design, not of that theme:
//!
//! 1. **[`Palette::Theme`] collapses roles.** Three pairs r02 insists must never share a
//!    treatment emit byte-identical SGR: cursor-mark/muted both `37`, faint/rule-internal
//!    both `90`, cursor-fill/layer-1 both `40`. Worse, that shared fill is slot 0, so on a
//!    black terminal the data cursor paints the background and the row vanishes — the
//!    exact failure §3 exists to prevent.
//! 2. **[`Palette::Indexed`]'s neutrals are neutral in a room where nothing else is.** A
//!    theme redefines only slots 0–15, so the 232–255 ramp stays true grey. Against a
//!    blue-violet field, simultaneous contrast makes true grey read as its opponent —
//!    yellow (Chris, 20260730). The ramp is not tinted; it is the only untinted thing on
//!    screen. Independently, r02's dark rungs assume a near-black background: `neutral(15)`
//!    resolves to `#262626`, which is *darker in blue* than Mocha's own background, so the
//!    layer fills and the cursor tint sink into the base rather than floating above it.
//!
//! [`Palette::Derived`] answers both, at the price named on the variant.

use std::sync::atomic::{AtomicU8, Ordering};
use std::sync::RwLock;

use ratatui::style::{Color, Modifier, Style};

use crate::terminal::{Endpoints, Rgb};

/// How neutrals are sourced. Hues are unaffected — they are always theme slots.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Palette {
    /// Only the 16 theme slots. Maximally theme-adaptive: a user who restyles their
    /// terminal restyles wqm with it, greys included. The cost is collapse — eleven
    /// specified neutrals map onto four available slots, so the emphasis ladder loses
    /// rungs and several roles that r02 separates end up sharing a colour.
    Theme,
    /// Theme slots for hues, the xterm 256-table greyscale ramp (indices 232–255) for
    /// neutrals. Still terminal-resolved indices rather than absolute RGB, and still
    /// downgrades cleanly, but the ramp is standard rather than theme-defined — so the
    /// eleven rungs survive at the price of greys that do not follow the user's theme.
    Indexed,
    /// Neutrals generated by interpolating between the terminal's *own* background and
    /// foreground, which [`crate::terminal`] asks it for.
    ///
    /// This is the only mode that answers both defects above: the endpoints carry the
    /// theme's hue, so every rung inherits it and none reads as yellow; and anchoring 0%
    /// at the real background guarantees each rung is ordered above the base rather than
    /// sinking into it.
    ///
    /// It costs the module's opening promise: these tokens **do** emit absolute RGB. The
    /// mitigation is that the values are read off the user's terminal rather than chosen
    /// here, which is arguably a stronger form of honouring a theme than picking slots
    /// from it. It also costs r02's percentages their absolute meaning — under this mode a
    /// rung is a position on the terminal's contrast range, not a byte value. Needs
    /// truecolor and a terminal that answers `OSC 11`/`OSC 10`; without both, falls back
    /// to [`ENDPOINT_FALLBACK`].
    Derived,
}

/// What [`Palette::Derived`] interpolates between when the terminal was never asked, or
/// declined to answer.
///
/// Black to white: the assumption r02 was authored under, so the fallback reproduces the
/// authored ladder rather than inventing a third one.
pub const ENDPOINT_FALLBACK: Endpoints = Endpoints {
    background: Rgb::new(0, 0, 0),
    foreground: Rgb::new(255, 255, 255),
};

/// The rung the terminal's foreground *is*.
///
/// r02 puts `normal` at grey85 and [`normal()`] renders it as `Color::Reset` — the
/// terminal's own foreground. So under [`Palette::Derived`] the foreground endpoint is the
/// 85% rung, not the 100% one, and anchoring it at 100% compresses the whole ladder
/// downward. Measured on Catppuccin Mocha, that compression cost `faint` 5, `muted` 13 and
/// `cursor_mark` 20 luma against the [`Palette::Indexed`] ramp — the gap Chris saw as "not
/// as good as Indexed" (20260730). Anchoring here restores it and lets `strong` extrapolate
/// *past* the foreground, which is what a rung above the baseline has to do.
const NORMAL_RUNG: u8 = 85;

static ENDPOINTS: RwLock<Endpoints> = RwLock::new(ENDPOINT_FALLBACK);

/// Installs the endpoints [`Palette::Derived`] interpolates between.
///
/// Call once at startup, before a TUI takes the terminal — see
/// [`crate::terminal::detect`]. Rendering never queries, so a frame costs no round trip.
pub fn set_endpoints(endpoints: Endpoints) {
    if let Ok(mut slot) = ENDPOINTS.write() {
        *slot = endpoints;
    }
}

/// The endpoints currently in force.
pub fn endpoints() -> Endpoints {
    ENDPOINTS.read().map(|e| *e).unwrap_or(ENDPOINT_FALLBACK)
}

static ACTIVE: AtomicU8 = AtomicU8::new(Palette::Theme as u8);

impl Palette {
    /// The palette every token currently resolves against.
    pub fn current() -> Palette {
        match ACTIVE.load(Ordering::Relaxed) {
            0 => Palette::Theme,
            1 => Palette::Indexed,
            _ => Palette::Derived,
        }
    }

    /// Every mode, in the order the sheet compares them.
    pub const ALL: [Palette; 3] = [Palette::Theme, Palette::Indexed, Palette::Derived];

    /// The name this mode is spelled with in the pantry and in VISUAL-LANGUAGE.md.
    pub const fn label(self) -> &'static str {
        match self {
            Palette::Theme => "Theme",
            Palette::Indexed => "Indexed",
            Palette::Derived => "Derived",
        }
    }

    /// Switch palettes. Lets one pantry render both modes so the trade-off is judged from
    /// a pair of frames rather than from an argument.
    pub fn set(palette: Palette) {
        ACTIVE.store(palette as u8, Ordering::Relaxed);
    }
}

/// A neutral, named by the luminance percentage r02 specifies for it.
///
/// Under [`Palette::Indexed`] the percentage picks the nearest step on the xterm greyscale
/// ramp, whose steps run 8, 18, … 238 at indices 232–255. Under [`Palette::Theme`] it
/// collapses onto the nearest of the four available slots.
fn neutral(percent: u8) -> Color {
    match Palette::current() {
        Palette::Theme => match percent {
            0..=24 => Color::Black,
            25..=55 => Color::DarkGray,
            56..=92 => Color::Gray,
            _ => Color::White,
        },
        Palette::Indexed => {
            let target = percent as u16 * 255 / 100;
            match target {
                // Below the ramp's first step and above its last, the cube's true black
                // and true white are the closer answers.
                0..=7 => Color::Indexed(16),
                243..=255 => Color::Indexed(231),
                _ => {
                    let step = ((target - 8) as f32 / 10.0).round() as u16;
                    Color::Indexed(232 + step.min(23) as u8)
                }
            }
        }
        Palette::Derived => {
            let Endpoints {
                background,
                foreground,
            } = endpoints();
            let t = percent.min(100) as f32 / NORMAL_RUNG as f32;
            Color::Rgb(
                mix(background.r, foreground.r, t),
                mix(background.g, foreground.g, t),
                mix(background.b, foreground.b, t),
            )
        }
    }
}

/// One channel of the derived ladder.
///
/// Interpolated in sRGB byte space rather than in linear light, because r02's rung names
/// are byte values — its `grey19` means byte 48, which is what [`Palette::Indexed`] also
/// resolves it to. Interpolating in linear light would honour the *percentages* as
/// luminance and lift the dark rungs far off the base: measured on Catppuccin Mocha it put
/// `layer1_bg` at `#5a5e6f`, a mid-grey, where §6 asks for "dark but distinctly above the
/// base". Byte-space keeps the authored spacing and only re-anchors its ends.
fn mix(from: u8, to: u8, t: f32) -> u8 {
    (from as f32 + (to as f32 - from as f32) * t)
        .round()
        .clamp(0.0, 255.0) as u8
}

/// One rung of the ladder, by the luminance percentage r02 names it with.
///
/// The named tokens below are how widgets should reach a rung — `faint()` says why the
/// colour was chosen, `neutral_at(50)` does not. This exists for the reference sheet, which
/// has the opposite job: enumerating the ladder as a ladder, including the rungs no token
/// is named after.
pub fn neutral_at(percent: u8) -> Color {
    neutral(percent)
}

// --- §2 emphasis ladder -------------------------------------------------------------
// Default posture: most of the screen is muted or faint. Normal is the zone you are in;
// strong is the few things that matter.

/// De-emphasised metadata that must still be legible (default-column values).
pub fn faint() -> Color {
    neutral(50)
}
/// Inactive tabs, unfocused zone bodies, timestamps, paths, key hints.
pub fn muted() -> Color {
    neutral(62)
}
/// Body text of the focused zone; the baseline.
///
/// This rung is the terminal's own foreground in both modes. The baseline is precisely
/// the text that should look like everything else the user reads in that window.
pub fn normal() -> Color {
    Color::Reset
}
/// Primary figures, and any value that differs from its default. Weight does the work;
/// the colour only stops it receding.
///
/// # The slot-based answer is measurably wrong
///
/// Under the two slot-sourced palettes this is `Color::White` — ANSI slot 15 — because
/// there is nothing brighter available. But a theme is free to place slot 15 *below* its
/// foreground, and Catppuccin Mocha does exactly that: slot 15 is `#bac2de` (luma 194)
/// against a foreground of `#cdd6f4` (luma 214), so the ladder's loudest rung renders 20
/// luma **darker** than its baseline and only the bold modifier hides it.
///
/// [`Palette::Derived`] can do better, because it is not picking from a fixed set: it
/// extrapolates past the foreground and gets a rung that is genuinely above `normal`.
pub fn strong() -> Color {
    match Palette::current() {
        Palette::Derived => neutral(100),
        _ => Color::White,
    }
}

// --- §2 / §6 structure --------------------------------------------------------------

/// Top and bottom frame rules — lighter, because they underline the screen.
pub fn rule_frame() -> Color {
    neutral(54)
}
/// Internal zone separators — darker, because they divide within.
pub fn rule_internal() -> Color {
    neutral(30)
}
/// Column headers are CAPS at this depth: structure, not data.
pub fn header() -> Color {
    neutral(62)
}

// --- §3 highlight roles -------------------------------------------------------------

/// The reserved selector hue. Cyan appears in NOTHING else: if it is a cyan block, it is
/// what you have selected. A theme slot, so a user who has retuned cyan retunes the
/// selector with it.
pub const SELECTOR: Color = Color::Cyan;
/// Text sitting inside an inverted selector block.
pub const SELECTOR_FG: Color = Color::Black;
/// The data cursor's row tint — a subtle darker fill, deliberately not an inverse block.
pub fn cursor_bg() -> Color {
    neutral(19)
}
/// The leading `▸` marker on the data cursor row.
pub fn cursor_mark() -> Color {
    neutral(70)
}
/// The editing cell fill — lighter than the cursor tint, so it reads as "you type HERE".
pub fn edit_bg() -> Color {
    neutral(35)
}

// --- §4 health ----------------------------------------------------------------------
// Only the glyph carries colour; the surrounding label stays muted.

pub const HEALTHY: Color = Color::Green;
pub const DEGRADED: Color = Color::Yellow;
pub const OFFLINE: Color = Color::Red;

// --- §6 layers ----------------------------------------------------------------------

/// Layer 0 keeps the terminal background and is never repainted, so it has no token.
/// Layer 1 — a modal over a full screen: dark, but distinctly above the base.
pub fn layer1_bg() -> Color {
    neutral(15)
}
/// Layer 2 — a modal over a modal: distinct and lighter, so the stack stays legible.
pub fn layer2_bg() -> Color {
    neutral(23)
}

/// The three store states, role-first per §7.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Health {
    Healthy,
    Degraded,
    Offline,
}

impl Health {
    /// §4 glyph table. Shape carries the state as well as hue, so the encoding survives
    /// `NO_COLOR` and the low colour depths (UX-06).
    pub const fn glyph(self) -> &'static str {
        match self {
            Health::Healthy => "●",
            Health::Degraded => "▲",
            Health::Offline => "○",
        }
    }

    pub const fn color(self) -> Color {
        match self {
            Health::Healthy => HEALTHY,
            Health::Degraded => DEGRADED,
            Health::Offline => OFFLINE,
        }
    }
}

/// Emphasis rungs as ready-made styles.
pub fn faint_style() -> Style {
    Style::default().fg(faint())
}
pub fn muted_style() -> Style {
    Style::default().fg(muted())
}
pub fn normal_style() -> Style {
    Style::default().fg(normal())
}
pub fn strong_style() -> Style {
    Style::default().fg(strong()).add_modifier(Modifier::BOLD)
}
