//! DocumentService RPC wrappers for [`DaemonClient`].
//!
//! Implements direct text ingestion, mirroring the TS `ingestText()` call in
//! `rules-mutation-helpers.ts` (lines 190-196, 275-280).
//!
//! | Rust method   | Proto RPC                    | TS equivalent  |
//! |---------------|------------------------------|----------------|
//! | `ingest_text` | `DocumentService::IngestText`| `ingestText()` |
//!
//! # document_id contract (load-bearing asymmetry)
//!
//! The `document_id` parameter is **not generated here**.  The caller is
//! responsible for supplying the correct value:
//!
//! - **ADD** (new rule): caller passes `randomUUID()` — a fresh UUID each time,
//!   so the daemon creates a brand-new Qdrant point.
//!   (TS: `rules-mutation-helpers.ts:194` — `document_id: randomUUID()`)
//!
//! - **UPDATE** (existing rule): caller passes the rule's stable **label** string,
//!   so the daemon can locate and replace the existing point by that ID.
//!   (TS: `rules-mutation-helpers.ts:279` — `document_id: label`)
//!
//! This wrapper **forwards** `document_id` verbatim.  It does **not** generate
//! UUIDs or impose any naming policy.  The asymmetry is the caller's concern.

use std::collections::HashMap;

use tonic::Status;

use wqm_proto::workspace_daemon::{IngestTextRequest, IngestTextResponse};

use super::client::DaemonClient;

impl DaemonClient {
    /// Ingest text content directly — mirrors TS `ingestText()`.
    ///
    /// Calls `DocumentService::IngestText` with the provided fields.
    ///
    /// # document_id semantics (see module doc)
    ///
    /// - For **ADD** operations: pass a fresh UUID (generated by the *caller*,
    ///   e.g. via `uuid::Uuid::new_v4().to_string()`).
    /// - For **UPDATE** operations: pass the rule's stable label string so the
    ///   daemon targets the correct existing Qdrant point.
    ///
    /// # Arguments
    /// * `content`             — text to embed and store
    /// * `collection_basename` — e.g. `"rules"` or `"scratchbook"`
    /// * `tenant_id`           — multi-tenant identifier
    /// * `document_id`         — supplied by caller; never generated here
    /// * `metadata`            — additional key/value metadata (e.g. `scope`,
    ///                           `label`, `rule_type` for rules)
    ///
    /// # Errors
    /// Propagates any [`Status`] error from the daemon (or timeout).
    pub async fn ingest_text(
        &mut self,
        content: String,
        collection_basename: String,
        tenant_id: String,
        document_id: String,
        metadata: HashMap<String, String>,
    ) -> Result<IngestTextResponse, Status> {
        let client = self.document.clone();
        self.call("ingestText", None, move || {
            let mut c = client.clone();
            let req = IngestTextRequest {
                content: content.clone(),
                collection_basename: collection_basename.clone(),
                tenant_id: tenant_id.clone(),
                document_id: Some(document_id.clone()),
                metadata: metadata.clone(),
                // chunk_text mirrors TS default (true): daemon decides chunking strategy.
                chunk_text: true,
            };
            async move {
                c.ingest_text(tonic::Request::new(req))
                    .await
                    .map(|r| r.into_inner())
            }
        })
        .await
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ── IngestTextRequest field-mapping ────────────────────────────────────────
    //
    // These tests validate the request construction logic against the TS
    // mapping at rules-mutation-helpers.ts:190-196 (ADD) and :275-280 (UPDATE)
    // without requiring a live daemon.

    fn make_add_metadata() -> HashMap<String, String> {
        // Mirrors buildAddMetadata() in rules-mutation-helpers.ts:152-158
        let mut m = HashMap::new();
        m.insert("scope".to_string(), "global".to_string());
        m.insert("rule_type".to_string(), "behavioral".to_string());
        m.insert("label".to_string(), "my-rule".to_string());
        m
    }

    fn make_update_metadata() -> HashMap<String, String> {
        // Mirrors buildUpdateMetadata() in rules-mutation-helpers.ts:221-234
        let mut m = HashMap::new();
        m.insert("label".to_string(), "my-rule".to_string());
        m.insert("scope".to_string(), "global".to_string());
        m
    }

    // --- ADD path: document_id is a UUID (opaque string from caller) ----------

    #[test]
    fn ingest_request_add_content_field() {
        let req = IngestTextRequest {
            content: "Always prefer composition over inheritance.".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            document_id: Some("550e8400-e29b-41d4-a716-446655440000".to_string()),
            metadata: make_add_metadata(),
            chunk_text: true,
        };
        assert_eq!(req.content, "Always prefer composition over inheritance.");
    }

    #[test]
    fn ingest_request_add_collection_basename_field() {
        let req = IngestTextRequest {
            content: "content".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            document_id: Some("some-uuid".to_string()),
            metadata: make_add_metadata(),
            chunk_text: true,
        };
        // TS: collection_basename: RULES_BASENAME (rules-mutation-helpers.ts:193)
        assert_eq!(req.collection_basename, "rules");
    }

    #[test]
    fn ingest_request_add_tenant_id_global() {
        let req = IngestTextRequest {
            content: "c".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            document_id: Some("uuid".to_string()),
            metadata: make_add_metadata(),
            chunk_text: true,
        };
        // TS: tenant_id: resolvedProjectId ?? TENANT_GLOBAL (rules-mutation-helpers.ts:193)
        assert_eq!(req.tenant_id, "global");
    }

    #[test]
    fn ingest_request_add_document_id_forwarded_verbatim() {
        let uuid = "550e8400-e29b-41d4-a716-446655440000";
        let req = IngestTextRequest {
            content: "c".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            document_id: Some(uuid.to_string()),
            metadata: make_add_metadata(),
            chunk_text: true,
        };
        // ADD: document_id is randomUUID() from caller (rules-mutation-helpers.ts:194)
        assert_eq!(req.document_id.as_deref(), Some(uuid));
    }

    #[test]
    fn ingest_request_add_metadata_contains_scope() {
        let meta = make_add_metadata();
        let req = IngestTextRequest {
            content: "c".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            document_id: Some("uuid".to_string()),
            metadata: meta,
            chunk_text: true,
        };
        // TS buildAddMetadata: m["scope"] = scope (rules-mutation-helpers.ts:153)
        assert_eq!(
            req.metadata.get("scope").map(String::as_str),
            Some("global")
        );
    }

    #[test]
    fn ingest_request_add_metadata_contains_rule_type() {
        let meta = make_add_metadata();
        let req = IngestTextRequest {
            content: "c".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            document_id: Some("uuid".to_string()),
            metadata: meta,
            chunk_text: true,
        };
        // TS buildAddMetadata: m["rule_type"] = "behavioral" (rules-mutation-helpers.ts:152)
        assert_eq!(
            req.metadata.get("rule_type").map(String::as_str),
            Some("behavioral")
        );
    }

    #[test]
    fn ingest_request_add_metadata_contains_label() {
        let meta = make_add_metadata();
        let req = IngestTextRequest {
            content: "c".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            document_id: Some("uuid".to_string()),
            metadata: meta,
            chunk_text: true,
        };
        // TS buildAddMetadata: m["label"] = label (rules-mutation-helpers.ts:152)
        assert_eq!(
            req.metadata.get("label").map(String::as_str),
            Some("my-rule")
        );
    }

    // --- UPDATE path: document_id is the stable label string ------------------

    #[test]
    fn ingest_request_update_document_id_is_label() {
        let label = "my-existing-rule";
        let req = IngestTextRequest {
            content: "Updated content.".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            // UPDATE: document_id = label (rules-mutation-helpers.ts:279)
            document_id: Some(label.to_string()),
            metadata: make_update_metadata(),
            chunk_text: true,
        };
        assert_eq!(req.document_id.as_deref(), Some(label));
    }

    #[test]
    fn ingest_request_update_tenant_id_resolves_to_project() {
        let req = IngestTextRequest {
            content: "c".to_string(),
            collection_basename: "rules".to_string(),
            // F-015: resolved project tenant for project-scoped UPDATE
            // (rules-mutation-helpers.ts:272)
            tenant_id: "abc123def456".to_string(),
            document_id: Some("my-rule".to_string()),
            metadata: make_update_metadata(),
            chunk_text: true,
        };
        assert_eq!(req.tenant_id, "abc123def456");
    }

    #[test]
    fn ingest_request_chunk_text_true_by_default() {
        let req = IngestTextRequest {
            content: "c".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "global".to_string(),
            document_id: Some("uuid".to_string()),
            metadata: HashMap::new(),
            chunk_text: true,
        };
        assert!(req.chunk_text);
    }

    #[test]
    fn ingest_request_metadata_optional_project_id() {
        let mut meta = make_add_metadata();
        meta.insert("project_id".to_string(), "abc123def456".to_string());
        let req = IngestTextRequest {
            content: "c".to_string(),
            collection_basename: "rules".to_string(),
            tenant_id: "abc123def456".to_string(),
            document_id: Some("uuid".to_string()),
            metadata: meta,
            chunk_text: true,
        };
        // TS buildAddMetadata: m[FIELD_PROJECT_ID] = resolvedProjectId (rules-mutation-helpers.ts:153)
        assert_eq!(
            req.metadata.get("project_id").map(String::as_str),
            Some("abc123def456")
        );
    }

    // ── DaemonClient construction (no live daemon) ────────────────────────────

    #[tokio::test]
    async fn daemon_client_constructs_for_document_calls() {
        let result = DaemonClient::new("http://127.0.0.1:50051");
        assert!(result.is_ok());
    }
}
