# Development Environment Configuration
# This configuration is optimized for local development with debugging enabled

# Server settings - development mode
server:
  host: "127.0.0.1"
  port: 8000
  debug: true
  reload: true
  log_level: "DEBUG"

# Qdrant database connection - local instance
qdrant:
  url: "http://localhost:6333"
  api_key: null
  timeout: 10  # Shorter timeout for development
  prefer_grpc: false
  health_check_interval: 5

# Embedding configuration - optimized for development speed
embedding:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  enable_sparse_vectors: true
  chunk_size: 500  # Smaller chunks for faster processing
  chunk_overlap: 50
  batch_size: 10   # Smaller batches to reduce memory usage
  cache_embeddings: true

# Workspace settings - development collections
workspace:
  collection_suffixes: ["project", "test-data"]
  global_collections: ["docs", "references", "dev-notes"]
  github_user: null
  collection_prefix: "dev_"
  max_collections: 20
  auto_create_collections: true
  cleanup_on_exit: true

# Development-specific features
development:
  hot_reload: true
  config_watch: true
  detailed_logging: true
  performance_metrics: true
  mock_external_services: false

# Security settings - relaxed for development
security:
  mask_sensitive_logs: false
  validate_ssl: false
  allow_http: true
  cors_enabled: true
  cors_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]