# Production Environment Configuration
# This configuration is optimized for production deployment with security and performance

# Server settings - production optimized
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  log_level: "WARNING"

# Qdrant database connection - production instance with high availability
qdrant:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY}"
  timeout: 60
  prefer_grpc: true
  health_check_interval: 60
  retry_attempts: 5
  connection_pool_size: 10

# Embedding configuration - production optimized
embedding:
  model: "${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}"
  enable_sparse_vectors: true
  chunk_size: 800
  chunk_overlap: 120
  batch_size: 100  # Larger batches for better throughput
  cache_embeddings: false
  embedding_timeout: 120
  max_concurrent_requests: 50

# Workspace settings - production environment
workspace:
  collections: ["project"]
  global_collections: ["docs", "references", "standards"]
  github_user: "${GITHUB_USER}"
  collection_prefix: ""
  max_collections: 1000
  auto_create_collections: false
  cleanup_on_exit: false

# Production-specific features
production:
  performance_monitoring: true
  error_tracking: true
  request_logging: false  # Disable for performance
  health_checks: true
  backup_enabled: true
  high_availability: true

# Security settings - maximum security
security:
  mask_sensitive_logs: true
  validate_ssl: true
  allow_http: false
  cors_enabled: true
  cors_origins: ["${ALLOWED_ORIGINS}"]
  rate_limiting: true
  max_requests_per_minute: 5000
  request_size_limit: 10485760  # 10MB
  authentication_required: true

# Monitoring and observability
monitoring:
  metrics_enabled: true
  tracing_enabled: true
  health_endpoint: "/health"
  metrics_endpoint: "/metrics"
  log_structured: true
  retention_days: 30
  alerts_enabled: true

# Performance optimization
performance:
  worker_processes: 4
  max_connections: 1000
  keepalive_timeout: 65
  request_timeout: 300
  memory_limit: "2GB"
  cpu_limit: 2.0

# Backup and disaster recovery
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 90
  encryption_enabled: true
  offsite_backup: true