//! Core types and constants for the MCP server.
//!
//! Mirrors `src/typescript/mcp-server/src/server-types.ts`:
//! - [`ServerMode`] enum (Stdio / Http)
//! - [`HttpTlsOptions`] struct
//! - [`HttpTransportOptions`] struct
//! - [`SessionState`] struct with lifecycle helpers
//! - Server identity constants ([`SERVER_NAME`], [`SERVER_VERSION`])
//! - Default HTTP listener constants ([`DEFAULT_HTTP_HOST`], [`DEFAULT_HTTP_PORT`],
//!   [`DEFAULT_HTTP_PATH`])
//! - Timing constant ([`HEARTBEAT_INTERVAL_MS`])
//!
//! # Drop-in parity
//! `SERVER_NAME` and `SERVER_VERSION` must match the TypeScript values so that
//! MCP clients that inspect `serverInfo` behave identically against both servers
//! (RISK-18 / CC-3).

use std::path::PathBuf;
use uuid::Uuid;

// ──────────────────────────────────────────────────────────────────────────────
// Server identity constants
// ──────────────────────────────────────────────────────────────────────────────

/// MCP server name sent in the `initialize` response (`serverInfo.name`).
///
/// Must match the TypeScript server's `SERVER_NAME` constant verbatim
/// (`src/typescript/mcp-server/src/server-types.ts`, line 14).
pub const SERVER_NAME: &str = "workspace-qdrant-mcp";

/// Server version string sent in the `initialize` response (`serverInfo.version`).
///
/// Mirrors the TypeScript pattern `"0.1.0-beta1 (${BUILD_NUMBER})"`.
/// The build number is a 4-digit upper-case hex string derived from the git
/// commit count (generated by `build.rs` and injected as `BUILD_NUMBER`).
///
/// OQ-4: exact byte equality of the version string is not required for
/// client compatibility (clients use name matching, not version matching),
/// so the base `"0.1.0-beta1"` is pinned here and the build suffix appended
/// at run-time via [`server_version_string`].
pub const SERVER_VERSION_BASE: &str = "0.1.0-beta1";

/// Build number injected by `build.rs` from git commit count (4-digit hex).
pub const BUILD_NUMBER: &str = env!("BUILD_NUMBER");

/// Compute the full version string `"0.1.0-beta1 (<build>)"` at run-time.
///
/// Matches the TypeScript pattern:
/// ```typescript
/// export const SERVER_VERSION = `0.1.0-beta1 (${BUILD_NUMBER})`;
/// ```
pub fn server_version_string() -> String {
    format!("{} ({})", SERVER_VERSION_BASE, BUILD_NUMBER)
}

/// Short `--help` text for the binary.
///
/// The server takes no positional arguments; its transport is selected from
/// `MCP_SERVER_MODE` (`stdio` default | `http`). This text documents that so a
/// `--help` invocation does not silently start the stdio server.
pub fn help_text() -> String {
    format!(
        "{name} {version}\n\
         \n\
         Project-scoped Qdrant MCP server. Reaches the memexd daemon over gRPC\n\
         and reads Qdrant directly; it is a read-only client.\n\
         \n\
         USAGE:\n    {name} [--version | --help]\n\
         \n\
         The transport is selected by environment, not flags:\n\
         \x20   MCP_SERVER_MODE=stdio   JSON-RPC over stdin/stdout (default)\n\
         \x20   MCP_SERVER_MODE=http    Streamable HTTP (see MCP_HTTP_* env vars)\n",
        name = SERVER_NAME,
        version = server_version_string(),
    )
}

/// Handle the early-exit CLI flags (`--version`/`-V`, `--help`/`-h`).
///
/// Returns `Some(output)` to print and exit when such a flag is present, or
/// `None` to proceed with normal env-driven startup. This exists because the
/// binary otherwise ignores argv and immediately launches the stdio/HTTP
/// server (which blocks on stdin) — so `--version` must be intercepted here
/// rather than starting the server.
pub fn cli_early_exit<I, S>(args: I) -> Option<String>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    for arg in args {
        match arg.as_ref() {
            "--version" | "-V" => {
                return Some(format!("{} {}", SERVER_NAME, server_version_string()));
            }
            "--help" | "-h" => return Some(help_text()),
            _ => {}
        }
    }
    None
}

// ──────────────────────────────────────────────────────────────────────────────
// HTTP defaults
// ──────────────────────────────────────────────────────────────────────────────

/// Default HTTP listener bind address.
///
/// Matches `DEFAULT_HTTP_HOST` in `server-types.ts` line 106.
/// Bind to `0.0.0.0` only inside a container.
pub const DEFAULT_HTTP_HOST: &str = "127.0.0.1";

/// Default HTTP listener port.
///
/// Matches `DEFAULT_HTTP_PORT` in `server-types.ts` line 107.
pub const DEFAULT_HTTP_PORT: u16 = 6335;

/// Default HTTP request path.
///
/// Matches `DEFAULT_HTTP_PATH` in `server-types.ts` line 108.
/// Follows the Streamable HTTP spec convention.
pub const DEFAULT_HTTP_PATH: &str = "/mcp";

/// Heartbeat interval in milliseconds.
///
/// Must be well under the daemon's orphan-cleanup timeout (120 s) to prevent
/// false deactivation.  30 s gives 4 missed heartbeats before deactivation.
///
/// Matches `HEARTBEAT_INTERVAL_MS` in `server-types.ts` line 11.
pub const HEARTBEAT_INTERVAL_MS: u64 = 30_000;

// ──────────────────────────────────────────────────────────────────────────────
// Transport mode
// ──────────────────────────────────────────────────────────────────────────────

/// Transport mode for the MCP server.
///
/// Mirrors the TypeScript `ServerMode` type (`server-types.ts` line 49).
///
/// - `Stdio`: MCP over stdin/stdout (default; Claude Desktop, `claude mcp …` CLI).
/// - `Http`: MCP Streamable HTTP transport.  Required for Docker deployments and
///   any client that cannot spawn a subprocess.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServerMode {
    /// JSON-RPC over stdin/stdout (default).
    Stdio,
    /// Streamable HTTP transport (requires `--http` flag or `MCP_HTTP` env var).
    Http,
}

impl Default for ServerMode {
    fn default() -> Self {
        Self::Stdio
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// TLS options
// ──────────────────────────────────────────────────────────────────────────────

/// Optional TLS configuration for the HTTP transport.
///
/// Mirrors `HttpTlsOptions` in `server-types.ts` lines 59–66.
///
/// When populated the server terminates TLS itself.  Recommended production
/// pattern is to run plain HTTP behind a reverse proxy (Caddy / Traefik /
/// nginx) and leave these fields unset; native TLS exists as a fallback for
/// deployments that do not want a proxy.
#[derive(Debug, Clone)]
pub struct HttpTlsOptions {
    /// Filesystem path to the server certificate in PEM format (chain ok).
    pub cert_path: PathBuf,
    /// Filesystem path to the server private key in PEM format.
    pub key_path: PathBuf,
    /// Optional PEM path for the CA bundle, for intermediate chain serving.
    pub ca_path: Option<PathBuf>,
}

// ──────────────────────────────────────────────────────────────────────────────
// HTTP transport options
// ──────────────────────────────────────────────────────────────────────────────

/// HTTP transport configuration.
///
/// Mirrors `HttpTransportOptions` in `server-types.ts` lines 75–81.
///
/// `host` defaults to `127.0.0.1` ([`DEFAULT_HTTP_HOST`]).
/// Bind to `0.0.0.0` only inside a container.
/// `path` defaults to `/mcp` ([`DEFAULT_HTTP_PATH`]).
#[derive(Debug, Clone)]
pub struct HttpTransportOptions {
    /// Bind address for the HTTP listener.
    pub host: String,
    /// Port number for the HTTP listener.
    pub port: u16,
    /// Request path (route).
    pub path: String,
    /// Optional native TLS termination.  `None` → plain HTTP.
    pub tls: Option<HttpTlsOptions>,
}

impl Default for HttpTransportOptions {
    fn default() -> Self {
        Self {
            host: DEFAULT_HTTP_HOST.to_string(),
            port: DEFAULT_HTTP_PORT,
            path: DEFAULT_HTTP_PATH.to_string(),
            tls: None,
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Session state
// ──────────────────────────────────────────────────────────────────────────────

/// Per-session state tracked by the MCP server.
///
/// Mirrors the `SessionState` interface in `server-types.ts` lines 17–37.
/// Each MCP session has exactly one `SessionState`; it is created at
/// connection time and dropped on disconnection.
///
/// # Field mapping
///
/// | TypeScript field       | Rust field          | Notes                        |
/// |------------------------|---------------------|------------------------------|
/// | `sessionId: string`    | `session_id: Uuid`  | UUID v4                      |
/// | `projectId: string \| null`  | `project_id: Option<String>` |               |
/// | `projectPath: string \| null`| `project_path: Option<PathBuf>` |            |
/// | `watchPath: string \| null`  | `watch_path: Option<PathBuf>` |              |
/// | `isWorktree: boolean`  | `is_worktree: bool` |                              |
/// | `daemonConnected: bool`| `daemon_connected: bool` |                        |
/// | `cleaned: boolean`     | `cleaned: bool`     | idempotence flag (F-049)     |
/// | `currentBranch: string \| null` | `current_branch: Option<String>` |       |
#[derive(Debug, Clone)]
pub struct SessionState {
    /// Unique identifier for this session (UUID v4).
    pub session_id: Uuid,
    /// Project ID registered with the daemon, if any.
    pub project_id: Option<String>,
    /// Filesystem path of the project root, if registered.
    pub project_path: Option<PathBuf>,
    /// Canonical watch path returned by the daemon (may differ from
    /// `project_path` due to symlink resolution).
    pub watch_path: Option<PathBuf>,
    /// Whether the project root is a git worktree (not the main worktree).
    pub is_worktree: bool,
    /// Whether the daemon gRPC connection is currently healthy.
    pub daemon_connected: bool,
    /// Idempotence flag for `cleanup_session` (F-049).
    /// Set to `true` on the first cleanup invocation; subsequent calls no-op.
    pub cleaned: bool,
    /// Idempotence flag for `initialize_session`. Set on the first `initialize`
    /// MCP request; subsequent calls no-op. Required because the HTTP transport
    /// shares a single `SessionState` across all per-connection handlers, so
    /// `initialize` may fire more than once against the same state.
    pub initialized: bool,
    /// Current git branch detected at session start.
    /// Used as the default branch filter for search and list tools.
    /// `None` when not inside a git repository.
    pub current_branch: Option<String>,
}

impl SessionState {
    /// Create a new session with a freshly generated UUID.
    pub fn new() -> Self {
        Self {
            session_id: Uuid::new_v4(),
            project_id: None,
            project_path: None,
            watch_path: None,
            is_worktree: false,
            daemon_connected: false,
            cleaned: false,
            initialized: false,
            current_branch: None,
        }
    }

    /// Update the daemon connection flag.
    pub fn set_daemon_connected(&mut self, connected: bool) {
        self.daemon_connected = connected;
    }

    /// Register a project: set `project_id`, `project_path`, and optional
    /// `watch_path` together as an atomic operation.
    pub fn set_project(&mut self, project_id: String, path: PathBuf, watch_path: Option<PathBuf>) {
        self.project_id = Some(project_id);
        self.project_path = Some(path.clone());
        self.watch_path = watch_path.or(Some(path));
    }

    /// Clear all project-related fields (project deregistered or session reset).
    pub fn clear_project(&mut self) {
        self.project_id = None;
        self.project_path = None;
        self.watch_path = None;
        self.is_worktree = false;
        self.current_branch = None;
    }

    /// Set the current git branch.
    pub fn set_branch(&mut self, branch: String) {
        self.current_branch = Some(branch);
    }

    /// Override the canonical watch path (e.g. after symlink resolution by daemon).
    pub fn set_watch_path(&mut self, path: PathBuf) {
        self.watch_path = Some(path);
    }

    /// Whether a project has been registered with the daemon.
    pub fn is_project_registered(&self) -> bool {
        self.project_id.is_some()
    }
}

impl Default for SessionState {
    fn default() -> Self {
        Self::new()
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
#[path = "server_types_tests.rs"]
mod tests;
