//! Core types and constants for the MCP server.
//!
//! Mirrors `src/typescript/mcp-server/src/server-types.ts`:
//! - [`ServerMode`] enum (Stdio / Http)
//! - [`HttpTlsOptions`] struct
//! - [`HttpTransportOptions`] struct
//! - [`SessionState`] struct with lifecycle helpers
//! - Server identity constants ([`SERVER_NAME`], [`SERVER_VERSION`])
//! - Default HTTP listener constants ([`DEFAULT_HTTP_HOST`], [`DEFAULT_HTTP_PORT`],
//!   [`DEFAULT_HTTP_PATH`])
//! - Timing constant ([`HEARTBEAT_INTERVAL_MS`])
//!
//! # Drop-in parity
//! `SERVER_NAME` and `SERVER_VERSION` must match the TypeScript values so that
//! MCP clients that inspect `serverInfo` behave identically against both servers
//! (RISK-18 / CC-3).

use std::path::PathBuf;
use uuid::Uuid;

// ──────────────────────────────────────────────────────────────────────────────
// Server identity constants
// ──────────────────────────────────────────────────────────────────────────────

/// MCP server name sent in the `initialize` response (`serverInfo.name`).
///
/// Must match the TypeScript server's `SERVER_NAME` constant verbatim
/// (`src/typescript/mcp-server/src/server-types.ts`, line 14).
pub const SERVER_NAME: &str = "workspace-qdrant-mcp";

/// Server version string sent in the `initialize` response (`serverInfo.version`).
///
/// Mirrors the TypeScript pattern `"0.1.0-beta1 (${BUILD_NUMBER})"`.
/// The build number is a 4-digit upper-case hex string derived from the git
/// commit count (generated by `build.rs` and injected as `BUILD_NUMBER`).
///
/// OQ-4: exact byte equality of the version string is not required for
/// client compatibility (clients use name matching, not version matching),
/// so the base `"0.1.0-beta1"` is pinned here and the build suffix appended
/// at run-time via [`server_version_string`].
pub const SERVER_VERSION_BASE: &str = "0.1.0-beta1";

/// Build number injected by `build.rs` from git commit count (4-digit hex).
pub const BUILD_NUMBER: &str = env!("BUILD_NUMBER");

/// Compute the full version string `"0.1.0-beta1 (<build>)"` at run-time.
///
/// Matches the TypeScript pattern:
/// ```typescript
/// export const SERVER_VERSION = `0.1.0-beta1 (${BUILD_NUMBER})`;
/// ```
pub fn server_version_string() -> String {
    format!("{} ({})", SERVER_VERSION_BASE, BUILD_NUMBER)
}

// ──────────────────────────────────────────────────────────────────────────────
// HTTP defaults
// ──────────────────────────────────────────────────────────────────────────────

/// Default HTTP listener bind address.
///
/// Matches `DEFAULT_HTTP_HOST` in `server-types.ts` line 106.
/// Bind to `0.0.0.0` only inside a container.
pub const DEFAULT_HTTP_HOST: &str = "127.0.0.1";

/// Default HTTP listener port.
///
/// Matches `DEFAULT_HTTP_PORT` in `server-types.ts` line 107.
pub const DEFAULT_HTTP_PORT: u16 = 6335;

/// Default HTTP request path.
///
/// Matches `DEFAULT_HTTP_PATH` in `server-types.ts` line 108.
/// Follows the Streamable HTTP spec convention.
pub const DEFAULT_HTTP_PATH: &str = "/mcp";

/// Heartbeat interval in milliseconds.
///
/// Must be well under the daemon's orphan-cleanup timeout (120 s) to prevent
/// false deactivation.  30 s gives 4 missed heartbeats before deactivation.
///
/// Matches `HEARTBEAT_INTERVAL_MS` in `server-types.ts` line 11.
pub const HEARTBEAT_INTERVAL_MS: u64 = 30_000;

// ──────────────────────────────────────────────────────────────────────────────
// Transport mode
// ──────────────────────────────────────────────────────────────────────────────

/// Transport mode for the MCP server.
///
/// Mirrors the TypeScript `ServerMode` type (`server-types.ts` line 49).
///
/// - `Stdio`: MCP over stdin/stdout (default; Claude Desktop, `claude mcp …` CLI).
/// - `Http`: MCP Streamable HTTP transport.  Required for Docker deployments and
///   any client that cannot spawn a subprocess.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServerMode {
    /// JSON-RPC over stdin/stdout (default).
    Stdio,
    /// Streamable HTTP transport (requires `--http` flag or `MCP_HTTP` env var).
    Http,
}

impl Default for ServerMode {
    fn default() -> Self {
        Self::Stdio
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// TLS options
// ──────────────────────────────────────────────────────────────────────────────

/// Optional TLS configuration for the HTTP transport.
///
/// Mirrors `HttpTlsOptions` in `server-types.ts` lines 59–66.
///
/// When populated the server terminates TLS itself.  Recommended production
/// pattern is to run plain HTTP behind a reverse proxy (Caddy / Traefik /
/// nginx) and leave these fields unset; native TLS exists as a fallback for
/// deployments that do not want a proxy.
#[derive(Debug, Clone)]
pub struct HttpTlsOptions {
    /// Filesystem path to the server certificate in PEM format (chain ok).
    pub cert_path: PathBuf,
    /// Filesystem path to the server private key in PEM format.
    pub key_path: PathBuf,
    /// Optional PEM path for the CA bundle, for intermediate chain serving.
    pub ca_path: Option<PathBuf>,
}

// ──────────────────────────────────────────────────────────────────────────────
// HTTP transport options
// ──────────────────────────────────────────────────────────────────────────────

/// HTTP transport configuration.
///
/// Mirrors `HttpTransportOptions` in `server-types.ts` lines 75–81.
///
/// `host` defaults to `127.0.0.1` ([`DEFAULT_HTTP_HOST`]).
/// Bind to `0.0.0.0` only inside a container.
/// `path` defaults to `/mcp` ([`DEFAULT_HTTP_PATH`]).
#[derive(Debug, Clone)]
pub struct HttpTransportOptions {
    /// Bind address for the HTTP listener.
    pub host: String,
    /// Port number for the HTTP listener.
    pub port: u16,
    /// Request path (route).
    pub path: String,
    /// Optional native TLS termination.  `None` → plain HTTP.
    pub tls: Option<HttpTlsOptions>,
}

impl Default for HttpTransportOptions {
    fn default() -> Self {
        Self {
            host: DEFAULT_HTTP_HOST.to_string(),
            port: DEFAULT_HTTP_PORT,
            path: DEFAULT_HTTP_PATH.to_string(),
            tls: None,
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Session state
// ──────────────────────────────────────────────────────────────────────────────

/// Per-session state tracked by the MCP server.
///
/// Mirrors the `SessionState` interface in `server-types.ts` lines 17–37.
/// Each MCP session has exactly one `SessionState`; it is created at
/// connection time and dropped on disconnection.
///
/// # Field mapping
///
/// | TypeScript field       | Rust field          | Notes                        |
/// |------------------------|---------------------|------------------------------|
/// | `sessionId: string`    | `session_id: Uuid`  | UUID v4                      |
/// | `projectId: string \| null`  | `project_id: Option<String>` |               |
/// | `projectPath: string \| null`| `project_path: Option<PathBuf>` |            |
/// | `watchPath: string \| null`  | `watch_path: Option<PathBuf>` |              |
/// | `isWorktree: boolean`  | `is_worktree: bool` |                              |
/// | `daemonConnected: bool`| `daemon_connected: bool` |                        |
/// | `cleaned: boolean`     | `cleaned: bool`     | idempotence flag (F-049)     |
/// | `currentBranch: string \| null` | `current_branch: Option<String>` |       |
#[derive(Debug, Clone)]
pub struct SessionState {
    /// Unique identifier for this session (UUID v4).
    pub session_id: Uuid,
    /// Project ID registered with the daemon, if any.
    pub project_id: Option<String>,
    /// Filesystem path of the project root, if registered.
    pub project_path: Option<PathBuf>,
    /// Canonical watch path returned by the daemon (may differ from
    /// `project_path` due to symlink resolution).
    pub watch_path: Option<PathBuf>,
    /// Whether the project root is a git worktree (not the main worktree).
    pub is_worktree: bool,
    /// Whether the daemon gRPC connection is currently healthy.
    pub daemon_connected: bool,
    /// Idempotence flag for `cleanup_session` (F-049).
    /// Set to `true` on the first cleanup invocation; subsequent calls no-op.
    pub cleaned: bool,
    /// Current git branch detected at session start.
    /// Used as the default branch filter for search and list tools.
    /// `None` when not inside a git repository.
    pub current_branch: Option<String>,
}

impl SessionState {
    /// Create a new session with a freshly generated UUID.
    pub fn new() -> Self {
        Self {
            session_id: Uuid::new_v4(),
            project_id: None,
            project_path: None,
            watch_path: None,
            is_worktree: false,
            daemon_connected: false,
            cleaned: false,
            current_branch: None,
        }
    }

    /// Update the daemon connection flag.
    pub fn set_daemon_connected(&mut self, connected: bool) {
        self.daemon_connected = connected;
    }

    /// Register a project: set `project_id`, `project_path`, and optional
    /// `watch_path` together as an atomic operation.
    pub fn set_project(&mut self, project_id: String, path: PathBuf, watch_path: Option<PathBuf>) {
        self.project_id = Some(project_id);
        self.project_path = Some(path.clone());
        self.watch_path = watch_path.or(Some(path));
    }

    /// Clear all project-related fields (project deregistered or session reset).
    pub fn clear_project(&mut self) {
        self.project_id = None;
        self.project_path = None;
        self.watch_path = None;
        self.is_worktree = false;
        self.current_branch = None;
    }

    /// Set the current git branch.
    pub fn set_branch(&mut self, branch: String) {
        self.current_branch = Some(branch);
    }

    /// Override the canonical watch path (e.g. after symlink resolution by daemon).
    pub fn set_watch_path(&mut self, path: PathBuf) {
        self.watch_path = Some(path);
    }

    /// Whether a project has been registered with the daemon.
    pub fn is_project_registered(&self) -> bool {
        self.project_id.is_some()
    }
}

impl Default for SessionState {
    fn default() -> Self {
        Self::new()
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Constants ──────────────────────────────────────────────────────────────

    #[test]
    fn server_name_matches_typescript() {
        // TS: export const SERVER_NAME = 'workspace-qdrant-mcp'; (server-types.ts:14)
        assert_eq!(SERVER_NAME, "workspace-qdrant-mcp");
    }

    #[test]
    fn server_version_base_matches_typescript() {
        // TS pattern: `0.1.0-beta1 (${BUILD_NUMBER})`
        assert_eq!(SERVER_VERSION_BASE, "0.1.0-beta1");
    }

    #[test]
    fn server_version_string_format() {
        let v = server_version_string();
        assert!(
            v.starts_with("0.1.0-beta1 ("),
            "version string should start with '0.1.0-beta1 (', got: {v:?}"
        );
        assert!(
            v.ends_with(')'),
            "version string should end with ')', got: {v:?}"
        );
        // Build number is a non-empty 4-digit hex string
        let build = &v["0.1.0-beta1 (".len()..v.len() - 1];
        assert!(!build.is_empty(), "build number must not be empty");
        assert!(
            build
                .chars()
                .all(|c| c.is_ascii_hexdigit() || c.is_ascii_uppercase()),
            "build number should be hex digits, got: {build:?}"
        );
    }

    #[test]
    fn build_number_is_non_empty() {
        assert!(!BUILD_NUMBER.is_empty());
    }

    #[test]
    fn default_http_host_matches_typescript() {
        // TS: export const DEFAULT_HTTP_HOST = '127.0.0.1'; (server-types.ts:106)
        assert_eq!(DEFAULT_HTTP_HOST, "127.0.0.1");
    }

    #[test]
    fn default_http_port_matches_typescript() {
        // TS: export const DEFAULT_HTTP_PORT = 6335; (server-types.ts:107)
        assert_eq!(DEFAULT_HTTP_PORT, 6335_u16);
    }

    #[test]
    fn default_http_path_matches_typescript() {
        // TS: export const DEFAULT_HTTP_PATH = '/mcp'; (server-types.ts:108)
        assert_eq!(DEFAULT_HTTP_PATH, "/mcp");
    }

    #[test]
    fn heartbeat_interval_matches_typescript() {
        // TS: export const HEARTBEAT_INTERVAL_MS = 30 * 1000; (server-types.ts:11)
        assert_eq!(HEARTBEAT_INTERVAL_MS, 30_000_u64);
    }

    // ── ServerMode ─────────────────────────────────────────────────────────────

    #[test]
    fn server_mode_default_is_stdio() {
        assert_eq!(ServerMode::default(), ServerMode::Stdio);
    }

    #[test]
    fn server_mode_variants_are_distinct() {
        assert_ne!(ServerMode::Stdio, ServerMode::Http);
    }

    #[test]
    fn server_mode_clone_and_copy() {
        let m = ServerMode::Http;
        let m2 = m;
        assert_eq!(m, m2);
        let m3 = m.clone();
        assert_eq!(m, m3);
    }

    // ── HttpTransportOptions ───────────────────────────────────────────────────

    #[test]
    fn http_transport_options_default_uses_constants() {
        let opts = HttpTransportOptions::default();
        assert_eq!(opts.host, DEFAULT_HTTP_HOST);
        assert_eq!(opts.port, DEFAULT_HTTP_PORT);
        assert_eq!(opts.path, DEFAULT_HTTP_PATH);
        assert!(opts.tls.is_none());
    }

    #[test]
    fn http_transport_options_with_tls() {
        let opts = HttpTransportOptions {
            host: "0.0.0.0".to_string(),
            port: 8443,
            path: "/mcp".to_string(),
            tls: Some(HttpTlsOptions {
                cert_path: PathBuf::from("/etc/ssl/cert.pem"),
                key_path: PathBuf::from("/etc/ssl/key.pem"),
                ca_path: None,
            }),
        };
        assert!(opts.tls.is_some());
        let tls = opts.tls.unwrap();
        assert_eq!(tls.cert_path, PathBuf::from("/etc/ssl/cert.pem"));
        assert!(tls.ca_path.is_none());
    }

    #[test]
    fn http_tls_options_with_ca_path() {
        let tls = HttpTlsOptions {
            cert_path: PathBuf::from("/cert.pem"),
            key_path: PathBuf::from("/key.pem"),
            ca_path: Some(PathBuf::from("/ca.pem")),
        };
        assert_eq!(tls.ca_path, Some(PathBuf::from("/ca.pem")));
    }

    // ── SessionState ───────────────────────────────────────────────────────────

    #[test]
    fn session_state_new_has_unique_uuid() {
        let s1 = SessionState::new();
        let s2 = SessionState::new();
        assert_ne!(
            s1.session_id, s2.session_id,
            "each session must have a unique UUID"
        );
    }

    #[test]
    fn session_state_default_fields() {
        let s = SessionState::new();
        assert!(s.project_id.is_none());
        assert!(s.project_path.is_none());
        assert!(s.watch_path.is_none());
        assert!(!s.is_worktree);
        assert!(!s.daemon_connected);
        assert!(!s.cleaned);
        assert!(s.current_branch.is_none());
    }

    #[test]
    fn session_state_default_trait_matches_new() {
        let s1 = SessionState::default();
        let s2 = SessionState::new();
        // Not the same UUID (each call generates a new one), but all other
        // default fields must be identical.
        assert!(s1.project_id.is_none());
        assert!(!s1.daemon_connected);
        assert!(!s2.daemon_connected);
    }

    #[test]
    fn daemon_connected_transitions() {
        let mut s = SessionState::new();
        assert!(!s.daemon_connected);
        s.set_daemon_connected(true);
        assert!(s.daemon_connected);
        s.set_daemon_connected(false);
        assert!(!s.daemon_connected);
    }

    #[test]
    fn set_project_populates_fields() {
        let mut s = SessionState::new();
        assert!(!s.is_project_registered());
        s.set_project(
            "proj-001".to_string(),
            PathBuf::from("/home/user/proj"),
            None,
        );
        assert!(s.is_project_registered());
        assert_eq!(s.project_id.as_deref(), Some("proj-001"));
        assert_eq!(s.project_path, Some(PathBuf::from("/home/user/proj")));
        // No explicit watch_path → falls back to project_path
        assert_eq!(s.watch_path, Some(PathBuf::from("/home/user/proj")));
    }

    #[test]
    fn set_project_with_explicit_watch_path() {
        let mut s = SessionState::new();
        s.set_project(
            "proj-002".to_string(),
            PathBuf::from("/home/user/proj"),
            Some(PathBuf::from("/realpath/proj")),
        );
        assert_eq!(s.watch_path, Some(PathBuf::from("/realpath/proj")));
    }

    #[test]
    fn clear_project_resets_all_project_fields() {
        let mut s = SessionState::new();
        s.set_project("pid".to_string(), PathBuf::from("/p"), None);
        s.is_worktree = true;
        s.set_branch("main".to_string());
        s.clear_project();
        assert!(!s.is_project_registered());
        assert!(s.project_path.is_none());
        assert!(s.watch_path.is_none());
        assert!(!s.is_worktree);
        assert!(s.current_branch.is_none());
    }

    #[test]
    fn set_branch_stores_branch() {
        let mut s = SessionState::new();
        s.set_branch("feat/my-branch".to_string());
        assert_eq!(s.current_branch.as_deref(), Some("feat/my-branch"));
    }

    #[test]
    fn set_watch_path_overrides() {
        let mut s = SessionState::new();
        s.set_project("p".to_string(), PathBuf::from("/orig"), None);
        s.set_watch_path(PathBuf::from("/resolved"));
        assert_eq!(s.watch_path, Some(PathBuf::from("/resolved")));
    }

    #[test]
    fn is_project_registered_false_when_no_project() {
        let s = SessionState::new();
        assert!(!s.is_project_registered());
    }

    #[test]
    fn session_state_clone() {
        let mut s = SessionState::new();
        s.set_daemon_connected(true);
        s.set_project("p".to_string(), PathBuf::from("/p"), None);
        let s2 = s.clone();
        assert_eq!(s2.session_id, s.session_id);
        assert!(s2.daemon_connected);
        assert_eq!(s2.project_id, s.project_id);
    }
}
