name: Feature Request
description: Suggest an idea for the workspace-qdrant-mcp project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        
        Please provide as much detail as possible to help us understand and prioritize your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - MCP Server Core
        - Collection Management
        - Vector Operations
        - CLI Tools (workspace-qdrant-*)
        - Admin Interface
        - Qdrant Integration
        - FastEmbed Integration
        - Authentication/Security
        - Configuration
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case or workflow that would benefit from this feature
      placeholder: "I'm trying to accomplish..."
    validations:
      required: false

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Ideas
      description: If you have thoughts on how this could be implemented, share them here
      placeholder: "This could be implemented by..."
    validations:
      required: false

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes?
      options:
        - "No - Backward compatible"
        - "Maybe - Unsure about compatibility"
        - "Yes - Breaking change required"
        - "Don't know"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, code examples, or links about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true