# Corrected YAML configuration that matches DaemonConfig struct exactly
# This configuration includes ALL required fields with proper naming and types

system:
  project_name: "workspace-qdrant-mcp"
  version: "v2.0"
  components:
    rust_daemon:
      enabled: true
    python_mcp_server:
      enabled: true
    cli_utility:
      enabled: true
    context_injector:
      enabled: true

memory:
  collection_name: "llm_rules"
  authority_levels:
    absolute:
      enabled: true
    default:
      enabled: true
  conversational_updates:
    enabled: true
    auto_conflict_detection: true
    immediate_activation: true
  conflict_resolution:
    strategy: "merge_conditional"
    user_prompt_timeout: "30s"  # TimeUnit - corrected field name and format
  token_management:
    max_tokens: 2000
    optimization_enabled: true
    trim_interactive: true
  rule_scope:
    all_sessions: true
    project_specific: true
    temporary_rules: true
    temporary_rule_duration: "24h"  # TimeUnit - corrected field name and format
  session_initialization:
    rule_injection_enabled: true
    conflict_detection_on_startup: true
    startup_timeout: "10s"  # TimeUnit - corrected field name and format

collections:
  root_name: "project"
  types: []
  project_content:
    enabled: true
    name: "project_content"
  naming:
    collision_detection: true
    validation_strict: true
  multi_tenancy:
    isolation_strategy: "metadata_filtering"
    cross_project_search: true
    tenant_metadata_fields:
      - "project_id"
      - "project_path"
      - "git_repository"

project_detection:
  git_detection:
    enabled: true
    priority: 1
    require_initialized: true
    scan_parent_directories: true
    max_parent_scan_depth: 10
  github_integration:
    user: ""
    submodule_handling:
      treat_as_independent_projects: true
      ignore_external_submodules: true
      track_ownership_changes: true
  custom_indicators:
    enabled: true
    priority: 2
    additional_patterns:
      custom_indicators: []
  naming:
    root_name_strategy: "directory_name"
    collection_auto_creation: true
    prevent_project_explosion: true

lsp_integration:
  enabled: true
  auto_detection: true
  auto_installation: false
  server_override:
    enabled: false
    overrides: {}
  health_monitoring:
    enabled: true
    check_interval: "30s"  # TimeUnit - corrected field name and format
    automatic_recovery: true
    max_restart_attempts: 3
  degradation:
    enabled: true
    level_1_lsp_crash:
      action: "continue_text_only"
    level_2_multiple_failures:
      action: "fallback_treesitter"
    level_3_complete_failure:
      action: "text_only_mode"

document_processing:
  supported_types:
    text:
      enabled: true
    pdf:
      enabled: true
      text_extraction: true
      ocr_required_detection: true
      store_ocr_required_in_state: true
    epub_mobi:
      enabled: true
      metadata_preservation: true
      extract_toc: true
    code:
      enabled: true
      lsp_enhanced: true
      fallback_to_treesitter: true
      fallback_to_storage_only: true
    web:
      single_page:
        enabled: true
      recursive_crawling:
        enabled: true
        max_depth: 3
        rate_limiting:
          requests_per_second: 2.0
          concurrent_connections: 3
        respect_robots_txt: true
  file_watching:
    enabled: true
    project_folders:
      auto_monitor: true
      zero_configuration: true
    library_folders:
      user_configured: true
    incremental_updates:
      content_hash_tracking: true
      modification_time_tracking: true
      process_only_changes: true
    debouncing:
      delay: "500ms"  # TimeUnit - corrected field name and format
  chunking:
    default_chunk_size: 1000
    default_chunk_overlap: 200
    max_file_size_bytes: "100MB"  # SizeUnit - already correct format
  performance:
    max_concurrent_tasks: 4
    batch_size: 100

search:
  modes:
    project:
      enabled: true
      default_mode: true
    collection:
      enabled: true
      default_mode: false
    global:
      enabled: true
      default_mode: false
    all:
      enabled: true
      default_mode: false
  hybrid:
    enabled: true
    fusion_algorithm: "rrf"
    dense_weight: 0.7
    sparse_weight: 0.3
  results:
    default_limit: 20
    max_limit: 100
    include_metadata: true
    include_snippets: true

performance:
  memory:
    max_rss: "500MB"  # SizeUnit - corrected field name and format
    warning_threshold: "400MB"  # SizeUnit - corrected field name and format
    gc_threshold: "350MB"  # SizeUnit - corrected field name and format
  startup:
    daemon_init_timeout: "2s"  # TimeUnit - corrected field name and format
    mcp_server_init_timeout: "5s"  # TimeUnit - corrected field name and format
    health_check_timeout: "1s"  # TimeUnit - corrected field name and format
  cpu:
    background_priority: "low"
    interactive_priority: "high"
    priority_boost_on_mcp_active: true
    revert_priority_on_mcp_quit: true

platform:
  xdg_compliance:
    enabled: true
    fallback_on_windows_mac: true
  directories:
    linux:
      cache: "$XDG_CACHE_HOME/workspace-qdrant-mcp"
      state: "$XDG_STATE_HOME/workspace-qdrant-mcp"
      config: "$XDG_CONFIG_HOME/workspace-qdrant-mcp"
      logs: "$XDG_STATE_HOME/workspace-qdrant-mcp/logs"
    macos:
      cache: "~/Library/Caches/workspace-qdrant-mcp"
      logs: "~/Library/Logs/workspace-qdrant-mcp"
      config: "~/Library/Application Support/workspace-qdrant-mcp"
      state: "~/Library/Application Support/workspace-qdrant-mcp/state"
    windows:
      cache: "%LOCALAPPDATA%\\workspace-qdrant-mcp\\cache"
      logs: "%LOCALAPPDATA%\\workspace-qdrant-mcp\\logs"
      config: "%APPDATA%\\workspace-qdrant-mcp"
      state: "%LOCALAPPDATA%\\workspace-qdrant-mcp\\state"
  file_patterns:
    include_patterns:
      custom: []
    exclude_patterns:
      custom: []

cli:
  behavior:
    interactive_mode: true
    default_output_format: "table"
    color_output: true
    progress_indicators: true
  commands:
    memory:
      auto_backup: true
    admin:
      confirm_destructive: true
    ingest:
      show_progress: true

grpc:
  server:
    enabled: true
    host: "127.0.0.1"
    port: 50051
    max_concurrent_streams: 100
    max_message_size: "16MB"  # SizeUnit - corrected field name and format
  client:
    connection_timeout: "5s"  # TimeUnit - corrected field name and format
    request_timeout: "30s"  # TimeUnit - corrected field name and format
    keepalive_interval: "30s"  # TimeUnit - corrected field name and format
    keepalive_timeout: "5s"  # TimeUnit - corrected field name and format
    max_retry_attempts: 3
    retry_backoff: "1s"  # TimeUnit - corrected field name and format

external_services:
  qdrant:
    url: "http://localhost:6333"
    api_key: null
    timeout: "30s"  # TimeUnit - corrected field name and format
    max_retries: 3
  embeddings:
    model: "sentence-transformers/all-MiniLM-L6-v2"
    cache_dir: null

monitoring:
  logging:
    level: "info"
    file_path: null
    json_format: false
    max_file_size_mb: 100
    max_files: 5
  metrics:
    enabled: true
    collection_interval_secs: 60
    retention_days: 30
    enable_prometheus: true
    prometheus_port: 9090
  health_checks:
    enabled: true
    check_interval: "30s"  # TimeUnit - corrected field name and format
    failure_threshold: 3