[toolchain]
# Minimum Supported Rust Version (MSRV)
# Based on sqlx 0.8 requirement (Rust 1.75+)
channel = "1.75.0"

# Components required for development
components = ["rustfmt", "clippy"]

# Targets for cross-compilation testing
targets = [
    "x86_64-unknown-linux-gnu",    # Linux x86_64
    "x86_64-apple-darwin",         # macOS Intel
    "aarch64-apple-darwin",        # macOS Apple Silicon
    "x86_64-pc-windows-msvc",      # Windows x86_64
]

# Profile for consistent behavior across developers
profile = "default"
