# Kubernetes namespace for Workspace Qdrant MCP
apiVersion: v1
kind: Namespace
metadata:
  name: workspace-qdrant-mcp
  labels:
    name: workspace-qdrant-mcp
    app.kubernetes.io/name: workspace-qdrant-mcp
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    description: "Workspace Qdrant MCP application namespace"
---
# Network policies for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: workspace-qdrant-mcp-netpol
  namespace: workspace-qdrant-mcp
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: workspace-qdrant-mcp
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  - {} # Allow all egress for now - restrict as needed
---
# Resource quota to prevent resource exhaustion
apiVersion: v1
kind: ResourceQuota
metadata:
  name: workspace-qdrant-mcp-quota
  namespace: workspace-qdrant-mcp
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
# Limit range for default resource limits
apiVersion: v1
kind: LimitRange
metadata:
  name: workspace-qdrant-mcp-limits
  namespace: workspace-qdrant-mcp
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim