# Enterprise Deployment Profile
# High security, compliance, and reliability for enterprise environments

# Server settings - enterprise grade
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  log_level: "WARNING"

# Qdrant - enterprise cluster
qdrant:
  url: "${QDRANT_CLUSTER_URL}"
  api_key: "${QDRANT_API_KEY}"
  timeout: 120
  prefer_grpc: true
  health_check_interval: 60
  retry_attempts: 10
  connection_pool_size: 25

# Embedding - enterprise configuration
embedding:
  model: "${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}"
  enable_sparse_vectors: true
  chunk_size: 1000
  chunk_overlap: 150
  batch_size: 200
  cache_embeddings: false
  embedding_timeout: 300
  max_concurrent_requests: 100

# Workspace - enterprise scale
workspace:
  collection_suffixes: ["enterprise-project"]
  global_collections: ["enterprise-docs", "compliance", "standards", "policies"]
  github_user: "${ENTERPRISE_GITHUB_USER}"
  collection_prefix: "${TENANT_ID}_"
  max_collections: 10000
  auto_create_collections: false
  cleanup_on_exit: false

# Development - completely disabled
development:
  hot_reload: false
  config_watch: false
  detailed_logging: false
  performance_metrics: false
  mock_external_services: false

# Security - maximum security
security:
  mask_sensitive_logs: true
  validate_ssl: true
  allow_http: false
  cors_enabled: true
  cors_origins: ["${ENTERPRISE_ALLOWED_ORIGINS}"]
  rate_limiting: true
  max_requests_per_minute: 50000
  request_size_limit: 52428800  # 50MB for enterprise documents
  authentication_required: true

# Monitoring - comprehensive enterprise monitoring
monitoring:
  metrics_enabled: true
  tracing_enabled: true
  health_endpoint: "/health"
  metrics_endpoint: "/metrics"
  log_structured: true
  retention_days: 90
  alerts_enabled: true

# Performance - enterprise scale
performance:
  worker_processes: 8
  max_connections: 5000
  keepalive_timeout: 75
  request_timeout: 600
  memory_limit: "8GB"
  cpu_limit: 4.0

# Enterprise-specific features
enterprise:
  tenant_isolation: true
  audit_logging: true
  compliance_mode: true
  data_retention_policy: 2555  # 7 years in days
  encryption_at_rest: true
  encryption_in_transit: true
  backup_frequency: "hourly"
  disaster_recovery: true
  
# Compliance settings
compliance:
  gdpr_enabled: true
  hipaa_enabled: "${HIPAA_REQUIRED:-false}"
  sox_enabled: "${SOX_REQUIRED:-false}"
  data_classification: true
  access_logging: true
  
# High availability
high_availability:
  multi_region: true
  failover_enabled: true
  load_balancing: true
  circuit_breaker: true
  retry_backoff: "exponential"
  
# Backup and disaster recovery
backup:
  enabled: true
  schedule: "0 */1 * * *"  # Hourly backups
  retention_days: 365
  encryption_enabled: true
  offsite_backup: true
  cross_region_replication: true
  point_in_time_recovery: true