# Kubernetes Deployment Profile
# Optimized for Kubernetes cluster deployment with service mesh

# Server settings - production ready
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  log_level: "INFO"

# Qdrant - Kubernetes service
qdrant:
  url: "${QDRANT_SERVICE_URL:-http://qdrant-service:6333}"
  api_key: "${QDRANT_API_KEY}"
  timeout: 60
  prefer_grpc: true
  health_check_interval: 30
  retry_attempts: 5
  connection_pool_size: 15

# Embedding - production settings
embedding:
  model: "${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}"
  enable_sparse_vectors: true
  chunk_size: 800
  chunk_overlap: 120
  batch_size: 100
  cache_embeddings: false
  embedding_timeout: 120
  max_concurrent_requests: 50

# Workspace - production
workspace:
  collections: ["${APP_NAME:-app}-project"]
  global_collections: ["shared-docs", "knowledge-base"]
  github_user: "${GITHUB_USER}"
  collection_prefix: "${NAMESPACE:-default}_"
  max_collections: 1000
  auto_create_collections: false
  cleanup_on_exit: false

# Development - disabled
development:
  hot_reload: false
  config_watch: false
  detailed_logging: false
  performance_metrics: true
  mock_external_services: false

# Security - Kubernetes optimized
security:
  mask_sensitive_logs: true
  validate_ssl: true
  allow_http: false
  cors_enabled: true
  cors_origins: ["${ALLOWED_ORIGINS}"]
  rate_limiting: true
  max_requests_per_minute: 10000
  authentication_required: true

# Monitoring - full observability
monitoring:
  metrics_enabled: true
  tracing_enabled: true
  health_endpoint: "/health"
  metrics_endpoint: "/metrics"
  log_structured: true
  retention_days: 30
  alerts_enabled: true

# Performance - cluster optimized
performance:
  worker_processes: "${WORKER_PROCESSES:-4}"
  max_connections: "${MAX_CONNECTIONS:-1000}"
  keepalive_timeout: 65
  request_timeout: 300
  memory_limit: "${MEMORY_LIMIT:-2GB}"
  cpu_limit: "${CPU_LIMIT:-2.0}"

# Kubernetes-specific settings
kubernetes:
  namespace: "${NAMESPACE:-default}"
  service_name: "${SERVICE_NAME:-workspace-qdrant-mcp}"
  pod_name: "${HOSTNAME}"
  cluster_name: "${CLUSTER_NAME}"
  
# Health checks for Kubernetes
health_checks:
  startup_probe_delay: 30
  startup_probe_timeout: 5
  liveness_probe_delay: 30
  liveness_probe_timeout: 5
  readiness_probe_delay: 5
  readiness_probe_timeout: 3