//! Language metadata for the code syntax highlighter.
//!
//! `src/rust/cli/src/tui/render/code_lang.rs`
//!
//! Contains the extension → language name map, per-language keyword sets, and
//! comment-prefix table. Split from `code.rs` to keep both files under the
//! 500-line limit.

// ─── Extension → language name ───────────────────────────────────────────────

/// Map a file extension (lowercase, without leading dot) to a canonical
/// language name used by `highlight_line`.
///
/// Returns `None` for unknown extensions; callers fall back to plain rendering.
pub fn language_for_extension(ext: &str) -> Option<&'static str> {
    match ext {
        "rs" => Some("rust"),
        "py" | "pyw" => Some("python"),
        "js" | "mjs" | "cjs" => Some("javascript"),
        "ts" | "mts" | "cts" => Some("typescript"),
        "jsx" => Some("jsx"),
        "tsx" => Some("tsx"),
        "go" => Some("go"),
        "c" | "h" => Some("c"),
        "cpp" | "cc" | "cxx" | "hpp" | "hh" | "hxx" => Some("cpp"),
        "java" => Some("java"),
        "rb" => Some("ruby"),
        "sh" | "bash" | "zsh" | "ksh" => Some("shell"),
        "json" => Some("json"),
        "toml" => Some("toml"),
        "yaml" | "yml" => Some("yaml"),
        "sql" => Some("sql"),
        "lua" => Some("lua"),
        "swift" => Some("swift"),
        "kt" | "kts" => Some("kotlin"),
        "cs" => Some("csharp"),
        _ => None,
    }
}

// ─── Per-language keyword sets ────────────────────────────────────────────────

/// Small keyword set for a language.
///
/// Returns a slice of lowercase keyword strings. The highlighter wraps these in
/// a word-boundary regex pattern, so they are matched as whole words only.
pub fn keywords_for(language: &str) -> &'static [&'static str] {
    match language {
        "rust" => &[
            "fn", "let", "mut", "pub", "use", "mod", "struct", "enum", "impl", "trait", "for",
            "while", "if", "else", "match", "return", "self", "Self", "super", "crate", "type",
            "where", "async", "await", "dyn", "Box", "Vec", "Option", "Result", "true", "false",
            "const", "static",
        ],
        "python" => &[
            "def", "class", "import", "from", "return", "if", "elif", "else", "for", "while",
            "with", "as", "try", "except", "finally", "raise", "pass", "break", "continue",
            "lambda", "yield", "True", "False", "None", "and", "or", "not", "in", "is", "async",
            "await",
        ],
        "javascript" | "typescript" | "jsx" | "tsx" => &[
            "function",
            "const",
            "let",
            "var",
            "return",
            "if",
            "else",
            "for",
            "while",
            "class",
            "extends",
            "import",
            "export",
            "from",
            "default",
            "new",
            "this",
            "typeof",
            "instanceof",
            "async",
            "await",
            "try",
            "catch",
            "finally",
            "throw",
            "true",
            "false",
            "null",
            "undefined",
            "type",
            "interface",
            "enum",
            "implements",
        ],
        "go" => &[
            "func",
            "var",
            "const",
            "type",
            "struct",
            "interface",
            "map",
            "chan",
            "go",
            "defer",
            "return",
            "if",
            "else",
            "for",
            "range",
            "switch",
            "case",
            "default",
            "package",
            "import",
            "select",
            "break",
            "continue",
            "fallthrough",
            "true",
            "false",
            "nil",
        ],
        "c" | "cpp" => &[
            "if",
            "else",
            "for",
            "while",
            "do",
            "return",
            "switch",
            "case",
            "break",
            "continue",
            "struct",
            "typedef",
            "enum",
            "union",
            "const",
            "static",
            "void",
            "int",
            "char",
            "float",
            "double",
            "unsigned",
            "long",
            "short",
            "bool",
            "true",
            "false",
            "NULL",
            "class",
            "public",
            "private",
            "protected",
            "virtual",
            "new",
            "delete",
            "namespace",
            "template",
            "typename",
            "auto",
        ],
        "java" => &[
            "public",
            "private",
            "protected",
            "class",
            "interface",
            "extends",
            "implements",
            "static",
            "final",
            "void",
            "new",
            "return",
            "if",
            "else",
            "for",
            "while",
            "try",
            "catch",
            "finally",
            "throw",
            "throws",
            "import",
            "package",
            "this",
            "super",
            "null",
            "true",
            "false",
        ],
        "ruby" => &[
            "def",
            "class",
            "module",
            "end",
            "do",
            "if",
            "elsif",
            "else",
            "unless",
            "while",
            "until",
            "for",
            "return",
            "yield",
            "begin",
            "rescue",
            "ensure",
            "raise",
            "true",
            "false",
            "nil",
            "self",
            "super",
            "require",
            "include",
            "attr_accessor",
        ],
        "shell" => &[
            "if", "then", "else", "elif", "fi", "for", "while", "do", "done", "case", "esac",
            "function", "return", "export", "local", "echo", "exit", "true", "false",
        ],
        "sql" => &[
            "SELECT", "FROM", "WHERE", "JOIN", "INNER", "LEFT", "RIGHT", "OUTER", "ON", "AND",
            "OR", "NOT", "INSERT", "INTO", "VALUES", "UPDATE", "SET", "DELETE", "CREATE", "TABLE",
            "INDEX", "DROP", "ALTER", "ADD", "COLUMN", "PRIMARY", "KEY", "FOREIGN", "UNIQUE",
            "NULL", "AS", "ORDER", "BY", "GROUP", "HAVING", "LIMIT", "OFFSET",
        ],
        "lua" => &[
            "function", "end", "local", "return", "if", "then", "else", "elseif", "while",
            "repeat", "until", "for", "do", "break", "nil", "true", "false", "and", "or", "not",
            "in",
        ],
        "swift" => &[
            "func",
            "var",
            "let",
            "class",
            "struct",
            "enum",
            "protocol",
            "extension",
            "import",
            "return",
            "if",
            "else",
            "for",
            "while",
            "switch",
            "case",
            "default",
            "guard",
            "defer",
            "throw",
            "try",
            "catch",
            "async",
            "await",
            "true",
            "false",
            "nil",
            "self",
            "super",
            "init",
            "deinit",
        ],
        "kotlin" => &[
            "fun",
            "val",
            "var",
            "class",
            "object",
            "interface",
            "companion",
            "return",
            "if",
            "else",
            "when",
            "for",
            "while",
            "try",
            "catch",
            "finally",
            "throw",
            "import",
            "package",
            "true",
            "false",
            "null",
            "this",
            "super",
            "is",
            "as",
            "in",
            "override",
        ],
        "csharp" => &[
            "public",
            "private",
            "protected",
            "class",
            "interface",
            "struct",
            "enum",
            "namespace",
            "using",
            "static",
            "void",
            "new",
            "return",
            "if",
            "else",
            "for",
            "while",
            "foreach",
            "try",
            "catch",
            "finally",
            "throw",
            "this",
            "base",
            "null",
            "true",
            "false",
            "async",
            "await",
            "var",
            "readonly",
            "const",
            "override",
            "virtual",
        ],
        // json / toml / yaml: no keywords — they are data formats
        _ => &[],
    }
}

// ─── Comment prefix for each language ────────────────────────────────────────

/// The single-line comment prefix for a language, if any.
pub fn comment_prefix(language: &str) -> Option<&'static str> {
    match language {
        "rust" | "javascript" | "typescript" | "jsx" | "tsx" | "go" | "c" | "cpp" | "java"
        | "swift" | "kotlin" | "csharp" => Some("//"),
        "python" | "ruby" | "shell" | "toml" | "yaml" | "yml" => Some("#"),
        "lua" => Some("--"),
        "sql" => Some("--"),
        _ => None,
    }
}
