# Default Configuration Asset
# Single source of truth for all workspace-qdrant-mcp configuration options
# Used by both Rust and Python implementations

# Server configuration
server:
  host: "127.0.0.1"
  port: 8000
  debug: false

# Qdrant database configuration
qdrant:
  url: "http://localhost:6333"
  api_key: null
  timeout: 30000  # milliseconds
  prefer_grpc: true
  transport: "grpc"

  # Connection pool configuration
  pool:
    max_connections: 10
    min_idle_connections: 2
    max_idle_time_secs: 300
    max_connection_lifetime_secs: 3600
    acquisition_timeout_secs: 30

  # Circuit breaker configuration
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    success_threshold: 3
    timeout_secs: 60
    half_open_timeout_secs: 30

  # Default collection configuration
  default_collection:
    vector_size: 384
    distance_metric: "Cosine"
    enable_indexing: true
    replication_factor: 1
    shard_number: 1
    on_disk_vectors: false

    # HNSW configuration
    hnsw:
      m: 16
      ef_construct: 100
      ef: 64
      full_scan_threshold: 10000

# Embedding service configuration
embedding:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  enable_sparse_vectors: true
  chunk_size: 800
  chunk_overlap: 120
  batch_size: 50

# Workspace management configuration
workspace:
  collection_types: []
  global_collections: []
  github_user: null
  auto_create_collections: false
  memory_collection_name: "__memory"
  code_collection_name: "__code"
  custom_include_patterns: []
  custom_exclude_patterns: []
  custom_project_indicators: {}

# gRPC communication configuration
grpc:
  enabled: true
  host: "127.0.0.1"
  port: 50051
  fallback_to_direct: true
  connection_timeout: 10000  # milliseconds
  max_retries: 3
  retry_backoff_multiplier: 1.5
  health_check_interval: 30000  # milliseconds
  max_message_length: 104857600  # 100MB in bytes
  keepalive_time: 30000  # milliseconds

# Auto-ingestion configuration
auto_ingestion:
  enabled: true
  auto_create_watches: true
  include_common_files: true
  include_source_files: false
  target_collection_suffix: "scratchbook"
  max_files_per_batch: 5
  batch_delay_seconds: 2.0
  max_file_size_mb: 52428800  # 50MB in bytes
  debounce_seconds: 10000  # milliseconds

# Logging configuration
logging:
  level: "info"
  use_file_logging: false
  log_file: null
  enable_metrics: false
  metrics_interval_secs: 60000  # milliseconds

# Performance configuration
performance:
  max_concurrent_tasks: 4
  default_timeout_ms: 30000  # milliseconds
  enable_preemption: true
  chunk_size: 1000

# Rust-specific configurations
rust:
  # Additional Rust-specific configurations that aren't shared with Python
  client:
    connection_timeout_secs: 30
    request_timeout_secs: 60
    max_retries: 3
    retry_delay_ms: 1000
    max_retry_delay_ms: 30000