# Local Development Profile
# Optimized for single-developer local development with fast iteration

# Server settings - local development
server:
  host: "127.0.0.1"
  port: 8000
  debug: true
  reload: true
  log_level: "DEBUG"

# Qdrant - local instance
qdrant:
  url: "http://localhost:6333"
  api_key: null
  timeout: 5
  prefer_grpc: false
  health_check_interval: 10
  retry_attempts: 2

# Embedding - fast processing for development
embedding:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  enable_sparse_vectors: true
  chunk_size: 400  # Smaller for faster processing
  chunk_overlap: 50
  batch_size: 5    # Small batches to reduce memory
  cache_embeddings: true
  embedding_timeout: 15

# Workspace - local collections
workspace:
  collection_suffixes: []
  global_collections: []
  github_user: null
  collection_prefix: "local_"
  max_collections: 10
  auto_create_collections: true
  cleanup_on_exit: true

# Development features - all enabled
development:
  hot_reload: true
  config_watch: true
  detailed_logging: true
  performance_metrics: true
  mock_external_services: false

# Security - relaxed for development
security:
  mask_sensitive_logs: false
  validate_ssl: false
  allow_http: true
  cors_enabled: true
  cors_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
  rate_limiting: false

# Monitoring - basic for development
monitoring:
  metrics_enabled: true
  tracing_enabled: false
  health_endpoint: "/health"
  log_structured: false

# Performance - lightweight
performance:
  worker_processes: 1
  max_connections: 10
  request_timeout: 15
  memory_limit: "256MB"