# Prometheus Alerting Rules for Backup and Disaster Recovery
# Add these rules to your Prometheus configuration

groups:
  - name: backup.alerts
    interval: 30s
    rules:
      # Full Backup Alerts
      - alert: FullBackupFailed
        expr: backup_success{type="full"} == 0
        for: 5m
        labels:
          severity: critical
          component: backup
          backup_type: full
        annotations:
          summary: "Full backup has failed"
          description: "The last full backup attempt failed. This may impact disaster recovery capability."
          runbook_url: "https://wiki.company.com/runbooks/backup-failure"

      - alert: FullBackupTooOld
        expr: (time() - backup_last_success_timestamp{type="full"}) > 86400 * 2  # 2 days
        for: 10m
        labels:
          severity: critical
          component: backup
          backup_type: full
        annotations:
          summary: "Full backup is too old"
          description: "No successful full backup in the last 2 days. Current age: {{ humanizeDuration $value }}"
          runbook_url: "https://wiki.company.com/runbooks/backup-aging"

      - alert: FullBackupSlow
        expr: backup_duration_seconds{type="full"} > 7200  # 2 hours
        for: 0m
        labels:
          severity: warning
          component: backup
          backup_type: full
        annotations:
          summary: "Full backup is taking too long"
          description: "Full backup took {{ humanizeDuration $value }} to complete, which exceeds the 2-hour threshold."

      # Incremental Backup Alerts
      - alert: IncrementalBackupFailed
        expr: qdrant_backup_success{type="incremental"} == 0
        for: 2m
        labels:
          severity: warning
          component: backup
          backup_type: incremental
        annotations:
          summary: "Incremental backup has failed"
          description: "The last incremental backup attempt failed. Data loss risk is increasing."

      - alert: IncrementalBackupTooOld
        expr: (time() - qdrant_backup_timestamp_seconds{type="incremental"}) > 14400  # 4 hours
        for: 5m
        labels:
          severity: warning
          component: backup
          backup_type: incremental
        annotations:
          summary: "Incremental backup is overdue"
          description: "No successful incremental backup in the last 4 hours. Current age: {{ humanizeDuration $value }}"

      # Backup Verification Alerts
      - alert: BackupVerificationFailed
        expr: backup_verification_success == 0
        for: 5m
        labels:
          severity: critical
          component: backup
          type: verification
        annotations:
          summary: "Backup verification has failed"
          description: "The last backup verification failed. Backup integrity is questionable."
          runbook_url: "https://wiki.company.com/runbooks/backup-verification-failure"

      - alert: BackupVerificationTooOld
        expr: (time() - backup_verification_timestamp_seconds) > 86400 * 2  # 2 days
        for: 15m
        labels:
          severity: warning
          component: backup
          type: verification
        annotations:
          summary: "Backup verification is overdue"
          description: "No backup verification performed in the last 2 days. Backup integrity is unknown."

      # Storage and Capacity Alerts
      - alert: BackupStorageUsageHigh
        expr: (backup_size_bytes / (1024^3)) > 400  # 400 GB
        for: 10m
        labels:
          severity: warning
          component: backup
          type: storage
        annotations:
          summary: "Backup storage usage is high"
          description: "Total backup storage usage is {{ humanize1024 $value }}B, approaching capacity limits."

      - alert: BackupStorageFull
        expr: (backup_size_bytes / (1024^3)) > 500  # 500 GB
        for: 0m
        labels:
          severity: critical
          component: backup
          type: storage
        annotations:
          summary: "Backup storage is nearly full"
          description: "Total backup storage usage is {{ humanize1024 $value }}B, immediate cleanup required."
          runbook_url: "https://wiki.company.com/runbooks/backup-storage-full"

      # RTO/RPO Compliance Alerts
      - alert: RTOBreachRisk
        expr: (time() - backup_last_success_timestamp{type="incremental"}) > 900  # 15 minutes (RPO target)
        for: 5m
        labels:
          severity: warning
          component: backup
          type: rto_rpo
        annotations:
          summary: "RPO target at risk"
          description: "Time since last backup ({{ humanizeDuration $value }}) approaching RPO limit of 15 minutes."

      - alert: BackupRetentionViolation
        expr: backup_count{type="full"} < 7  # Less than 7 daily backups
        for: 30m
        labels:
          severity: warning
          component: backup
          type: retention
        annotations:
          summary: "Backup retention policy violation"
          description: "Only {{ $value }} full backups available, below the required 7-day retention."

      # Qdrant-specific Backup Alerts
      - alert: QdrantCollectionBackupFailed
        expr: increase(qdrant_backup_collections_count{type="full"}[1h]) == 0 and on() backup_success{type="full"} == 1
        for: 5m
        labels:
          severity: warning
          component: backup
          type: collection
        annotations:
          summary: "No Qdrant collections backed up despite successful backup job"
          description: "Backup job succeeded but no collections were backed up. Check Qdrant connectivity."

      - alert: QdrantBackupSizeAnomalous
        expr: (
            (qdrant_backup_size_bytes{type="full"} - qdrant_backup_size_bytes{type="full"} offset 1d) / 
            qdrant_backup_size_bytes{type="full"} offset 1d
          ) > 0.5  # 50% increase
        for: 10m
        labels:
          severity: warning
          component: backup
          type: size_anomaly
        annotations:
          summary: "Backup size increased significantly"
          description: "Full backup size increased by {{ humanizePercentage $value }} compared to yesterday."

      - alert: QdrantBackupCollectionCountChanged
        expr: (
            abs(qdrant_backup_collections_count{type="full"} - qdrant_backup_collections_count{type="full"} offset 1d)
          ) > 0
        for: 15m
        labels:
          severity: info
          component: backup
          type: collection_change
        annotations:
          summary: "Collection count changed in backup"
          description: "Number of collections in backup changed from {{ $value }} collections."

  - name: disaster_recovery.alerts
    interval: 60s
    rules:
      # Service Availability for DR Planning
      - alert: QdrantServiceDown
        expr: up{job="qdrant"} == 0
        for: 1m
        labels:
          severity: critical
          component: qdrant
          type: availability
        annotations:
          summary: "Qdrant service is down"
          description: "Qdrant service has been down for {{ humanizeDuration $value }}. Disaster recovery may be needed."
          runbook_url: "https://wiki.company.com/runbooks/qdrant-down"

      - alert: QdrantHighResponseTime
        expr: histogram_quantile(0.95, http_request_duration_seconds_bucket{job="qdrant"}) > 1.0
        for: 5m
        labels:
          severity: warning
          component: qdrant
          type: performance
        annotations:
          summary: "Qdrant response time is high"
          description: "95th percentile response time is {{ humanizeDuration $value }}, indicating potential issues."

      # Data Integrity Alerts
      - alert: QdrantCollectionStatusUnhealthy
        expr: qdrant_collection_status != 3  # Assuming 3 = healthy
        for: 2m
        labels:
          severity: critical
          component: qdrant
          type: data_integrity
        annotations:
          summary: "Qdrant collection is unhealthy"
          description: "Collection {{ $labels.collection }} status is unhealthy. May require recovery."

      # Cross-Region Replication Alerts (if applicable)
      - alert: CrossRegionReplicationLag
        expr: (time() - backup_replication_timestamp) > 1800  # 30 minutes
        for: 5m
        labels:
          severity: critical
          component: backup
          type: replication
        annotations:
          summary: "Cross-region backup replication is lagging"
          description: "Replication lag is {{ humanizeDuration $value }}, exceeding 30-minute threshold."

  - name: backup_sla.alerts
    interval: 300s  # 5 minutes
    rules:
      # SLA Compliance Tracking
      - alert: BackupSLAViolation
        expr: |
          (
            rate(backup_success{type="full"}[7d]) < 0.99
          )
        for: 1h
        labels:
          severity: critical
          component: backup
          type: sla
        annotations:
          summary: "Backup SLA violation detected"
          description: "Backup success rate over 7 days is {{ humanizePercentage $value }}, below 99% SLA."

      - alert: RecoveryCapabilityDegraded
        expr: |
          (
            backup_verification_success == 0 or 
            (time() - backup_last_success_timestamp{type="full"}) > 86400
          )
        for: 30m
        labels:
          severity: critical
          component: disaster_recovery
          type: capability
        annotations:
          summary: "Disaster recovery capability is degraded"
          description: "Recent backup verification failed or backups are stale. Recovery capability compromised."
          runbook_url: "https://wiki.company.com/runbooks/dr-capability-degraded"

      # Business Impact Alerts
      - alert: BusinessContinuityAtRisk
        expr: |
          (
            (time() - backup_last_success_timestamp{type="full"}) > 86400 * 2 and
            (time() - backup_last_success_timestamp{type="incremental"}) > 14400
          )
        for: 5m
        labels:
          severity: critical
          component: business_continuity
          priority: p1
        annotations:
          summary: "Business continuity is at risk"
          description: "Both full and incremental backups are stale. Business operations at risk if disaster occurs."
          escalation: "immediate"
          runbook_url: "https://wiki.company.com/runbooks/business-continuity-risk"

  - name: backup_capacity_planning.alerts
    interval: 1800s  # 30 minutes
    rules:
      # Growth and Capacity Planning
      - alert: BackupGrowthRateHigh
        expr: |
          (
            deriv(backup_size_bytes{type="full"}[7d]) > 5368709120  # 5GB per week
          )
        for: 2h
        labels:
          severity: info
          component: backup
          type: capacity_planning
        annotations:
          summary: "Backup storage growth rate is high"
          description: "Backup storage growing at {{ humanize1024 $value }}B/week. Capacity planning review needed."

      - alert: BackupStorageProjectedFull
        expr: |
          (
            predict_linear(backup_size_bytes[14d], 86400 * 30) > 500 * 1024^3  # 500GB in 30 days
          )
        for: 4h
        labels:
          severity: warning
          component: backup
          type: capacity_planning
        annotations:
          summary: "Backup storage projected to be full"
          description: "Current growth trend predicts storage full in ~30 days. Expand storage or improve retention."