#!/usr/bin/env tsx
/**
 * Generates build-info.ts with git commit count as 4-digit hex build number.
 * Run as part of the build pipeline.
 */

import { execFileSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

let buildNumber = '0000';
try {
  const count = parseInt(
    execFileSync('git', ['rev-list', '--count', 'HEAD'], { encoding: 'utf-8' }).trim(),
    10,
  );
  buildNumber = count.toString(16).toUpperCase().padStart(4, '0');
} catch {
  // Fallback if not in a git repo
}

const content = `// Auto-generated by scripts/generate-build-info.ts — do not edit
export const BUILD_NUMBER = '${buildNumber}';
`;

writeFileSync(join(__dirname, '..', 'src', 'build-info.ts'), content);
console.log(`Build number: ${buildNumber}`);
