# Unified Configuration for Workspace Qdrant MCP
# This configuration file supports both Rust daemon and Python MCP server

# Server configuration (Python MCP server)
host: "127.0.0.1"
port: 8000
debug: false

# Qdrant database connection settings
qdrant:
  url: "http://localhost:6333"
  api_key: null  # Set via WORKSPACE_QDRANT_QDRANT__API_KEY environment variable
  timeout: 30
  prefer_grpc: false

# Daemon configuration and behavior (Rust daemon)
daemon:
  # SQLite database for state persistence
  database_path: "~/.config/workspace-qdrant/state.db"
  
  # Processing configuration
  max_concurrent_jobs: 4
  job_timeout_seconds: 300
  
  # Priority levels for task management
  priority_levels:
    mcp_server: high
    cli_commands: medium
    background_watching: low
    
  # Resource limits
  max_memory_mb: 1024
  max_cpu_percent: 80
  
  # gRPC server settings
  grpc:
    host: "127.0.0.1"
    port: 50051
    max_message_size_mb: 100

# Embedding model configuration
embedding:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  enable_sparse_vectors: true
  chunk_size: 800
  chunk_overlap: 120
  batch_size: 50

# Collection management settings
workspace:
  collection_types: ["scratchbook"]
  global_collections: []
  github_user: null  # Set via WORKSPACE_QDRANT_WORKSPACE__GITHUB_USER
  auto_create_collections: false

# Folder watching configuration
watching:
  # Default watching behavior
  auto_watch_project: true
  debounce_seconds: 5
  max_file_size_mb: 50
  
  # File patterns
  include_patterns:
    - "*.txt"
    - "*.md"
    - "*.pdf"
    - "*.epub"
    - "*.docx"
    - "*.py"
    - "*.js"
    - "*.ts"
    - "*.html"
    - "*.css"
    
  ignore_patterns:
    - "*.tmp"
    - "*.log"
    - "*.cache"
    - ".git/*"
    - "node_modules/*"
    - "__pycache__/*"
    - "*.pyc"
    - ".DS_Store"
    
  # Recursive watching settings
  recursive: true
  max_depth: 5
  follow_symlinks: false

# Chunking and processing settings
processing:
  chunk_size: 1000
  chunk_overlap: 200
  min_chunk_size: 100
  
  # File type specific settings
  pdf:
    extract_images: false
    extract_tables: true
    
  docx:
    extract_images: false
    extract_styles: false
    
  code:
    include_comments: true
    language_detection: true

# gRPC configuration for communication between components
grpc:
  enabled: true
  host: "127.0.0.1"
  port: 50051
  fallback_to_direct: true
  connection_timeout: 10.0
  max_retries: 3

# Auto-ingestion configuration
auto_ingestion:
  enabled: true
  auto_create_watches: true
  include_common_files: true
  include_source_files: false
  target_collection_suffix: "scratchbook"
  max_files_per_batch: 5
  batch_delay_seconds: 2.0
  max_file_size_mb: 50
  debounce_seconds: 10

# Logging and observability
logging:
  level: "INFO"  # DEBUG, INFO, WARN, ERROR
  format: "json"  # json, text
  file_path: "~/.config/workspace-qdrant/logs/daemon.log"
  max_file_size_mb: 10
  backup_count: 5
  
  # Component-specific log levels
  components:
    qdrant_client: "WARN"
    embedding: "INFO"
    file_watcher: "INFO"
    grpc_server: "WARN"

# Performance and monitoring settings
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval_seconds: 60
  
  # Performance thresholds
  thresholds:
    max_response_time_ms: 1000
    max_memory_usage_mb: 512
    max_cpu_usage_percent: 70

# Development and debugging settings
development:
  debug_mode: false
  profile_performance: false
  mock_embedding: false
  test_data_path: "tests/data"