# Unified Configuration for Workspace Qdrant MCP
# This configuration file supports both Rust daemon and Python MCP server

# Logging configuration
log_file = "~/.local/state/workspace-qdrant-mcp/memexd.log"

# Processing engine configuration  
max_concurrent_tasks = 4
default_timeout_ms = 30000
enable_preemption = true
chunk_size = 1000
enable_lsp = true
log_level = "info"
enable_metrics = true
metrics_interval_secs = 60

# Auto-ingestion configuration
[auto_ingestion]
enabled = true
auto_create_watches = true
include_common_files = true
include_source_files = true
target_collection_suffix = "scratchbook"
max_files_per_batch = 5
batch_delay_seconds = 2.0
max_file_size_mb = 50
recursive_depth = 5
debounce_seconds = 10

# Project path (automatically detected if not specified)
# project_path = "/path/to/your/workspace"

# Qdrant connection configuration
[qdrant]
url = "http://localhost:6333"
transport = "Http"  # Options: "Http", "Grpc"
timeout_ms = 30000
max_retries = 3
retry_delay_ms = 1000
pool_size = 10
tls = false
dense_vector_size = 1536
check_compatibility = false

# Enhanced logging configuration
[logging]
info_includes_connection_events = true
info_includes_transport_details = true
info_includes_retry_attempts = true
info_includes_fallback_behavior = true
error_includes_stack_trace = true
error_includes_connection_state = true