[toolchain]
# Use stable Rust channel for latest features and dependency support
# Minimum: Rust 1.82.0 for Cargo.lock v4 support
channel = "stable"

# Components required for development
components = ["rustfmt", "clippy"]

# Targets for cross-compilation testing
targets = [
    "x86_64-unknown-linux-gnu",    # Linux x86_64
    "x86_64-apple-darwin",         # macOS Intel
    "aarch64-apple-darwin",        # macOS Apple Silicon
    "x86_64-pc-windows-msvc",      # Windows x86_64
]

# Profile for consistent behavior across developers
profile = "default"
